force-app/main/default/objects/Case/fields/OM_SAC_Categorizacion_Incidencia__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_Categorizacion_Incidencia__c</fullName>
    <label>Categorización incidencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_CodigoModelo__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_CodigoModelo__c</fullName>
    <formula>OM_SAC_modeloYDenominacion__r.ProductCode</formula>
    <label>Código modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_Defecto__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_Defecto__c</fullName>
    <label>Defecto</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_Lista_de_distribucion__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_Lista_de_distribucion__c</fullName>
    <defaultValue>&apos;distribucion.calidad@vidrala.com;naiara.molinuevo@vidrala.com&apos;</defaultValue>
    <label>Lista de distribución</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_loteOAlbaran__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_loteOAlbaran__c</fullName>
    <label>Lote o albarán</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_VID_AccountNameAuto__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_AccountNameAuto__c</fullName>
    <formula>Account.Name</formula>
    <label>Nombre Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_VID_Planta__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Planta__c</fullName>
    <label>Planta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1010</fullName>
                <label>Aiala</label>
            </value>
            <value>
                <fullName>1020</fullName>
                <label>Crisnova</label>
            </value>
            <value>
                <fullName>1030</fullName>
                <label>Castellar</label>
            </value>
            <value>
                <fullName>1040</fullName>
                <label>Gallo</label>
            </value>
            <value>
                <fullName>1090</fullName>
                <label>Santos Barosa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Fifty_Calidad_Insatisfaccion.recordType-meta.xml
<RecordType>
    <fullName>Fifty_Calidad_Insatisfaccion</fullName>
    <active>true</active>
    <businessProcess>Grupo</businessProcess>
    <label>Fifty Calidad Insatisfacción</label>
</RecordType>

force-app/main/default/classes/OM_VID_CaseTRGHandler_Test.cls
@isTest
public class OM_VID_CaseTRGHandler_Test {
    @isTest static void testHandlerMethod_BeforeInsertMethods(){
        Test.StartTest();
        OM_VID_TestUtils.createCases(1);
        
        Case insatisfaccion = [SELECT ID, OM_SAC_Lista_de_distribucion__c FROM Case WHERE RecordTypeId =: OM_Utils.RecordTypes.getRecordTypeByDevName('Case', 'Fifty_Calidad_Insatisfaccion') limit 1];
        //Assert.areEqual(acc.Phone, '+34 523456789', 'Account phone number hasn\'t got the expected format');
        Assert.areNotEqual(insatisfaccion.OM_SAC_Lista_de_distribucion__c, '', 'La lista de distribución no puede estar vacía.');
        Test.StopTest();
    }
    
    @isTest static void testHandlerMethod_AfterInsertMethods(){
        Test.StartTest();
        OM_VID_TestUtils.createCases(1);
        
        Case insatisfaccion = [SELECT ID, Subject, OM_SAC_Categorizacion_Incidencia__c, OM_SAC_loteOAlbaran__c, OM_SAC_Defecto__c, OM_VID_AccountNameAuto__c, OM_SAC_CodigoModelo__c FROM Case WHERE RecordTypeId =: OM_Utils.RecordTypes.getRecordTypeByDevName('Case', 'Fifty_Calidad_Insatisfaccion') limit 1];
        //Assert.areEqual(acc.Phone, '+34 523456789', 'Account phone number hasn\'t got the expected format');
        Assert.areEqual(insatisfaccion.Subject, 'Apertura NC_'+insatisfaccion.OM_SAC_Categorizacion_Incidencia__c+'_'+insatisfaccion.OM_VID_AccountNameAuto__c+'_'+insatisfaccion.OM_SAC_loteOAlbaran__c+'_'+insatisfaccion.OM_SAC_CodigoModelo__c+'_'+insatisfaccion.OM_SAC_Defecto__c);
        Test.StopTest();
    }
    
	@isTest static void testHandlerMethod_AfterUpdateMethods(){
        
        OM_VID_TestUtils.createCases(1);
        
        Case insatisfaccion = [SELECT Id, Subject, OM_SAC_Categorizacion_Incidencia__c, OM_SAC_loteOAlbaran__c, OM_SAC_Defecto__c, OM_VID_AccountNameAuto__c, OM_SAC_CodigoModelo__c, OM_VID_Planta__c 
                               FROM Case 
                               WHERE RecordTypeId =: OM_Utils.RecordTypes.getRecordTypeByDevName('Case', 'Fifty_Calidad_Insatisfaccion') 
                               LIMIT 1];
        
        
        insatisfaccion.OM_SAC_Categorizacion_Incidencia__c = 'B';
        insatisfaccion.OM_SAC_loteOAlbaran__c = '4554321';
        insatisfaccion.OM_SAC_Defecto__c = 'update';
        insatisfaccion.OM_VID_Planta__c = '1090';
        
        Test.StartTest();
        update insatisfaccion;
        Test.StopTest();
        
        Case updatedCase = [SELECT Id, Subject, OM_SAC_Categorizacion_Incidencia__c, OM_SAC_loteOAlbaran__c, OM_SAC_Defecto__c, OM_VID_AccountNameAuto__c, OM_SAC_CodigoModelo__c, OM_VID_Planta__c, OM_SAC_Lista_de_distribucion__c 
                            FROM Case 
                            WHERE Id = :insatisfaccion.Id];
        
        String updatedSubject = 'Apertura NC_' + updatedCase.OM_SAC_Categorizacion_Incidencia__c + '_' +
                                 updatedCase.OM_VID_AccountNameAuto__c + '_' +
                                 updatedCase.OM_SAC_loteOAlbaran__c + '_' +
                                 updatedCase.OM_SAC_CodigoModelo__c + '_' +
                                 updatedCase.OM_SAC_Defecto__c;
                                 
        System.assertEquals(updatedSubject, updatedCase.Subject, 'El Subject no se ha actualizado correctamente.');
        
        String expectedListaDistribucion = OM_VID_CaseTRGHandlerMethods.getOrgWideEmailAddressIdFromPlant(updatedCase.OM_VID_Planta__c);
        
        System.assertEquals(expectedListaDistribucion, updatedCase.OM_SAC_Lista_de_distribucion__c, 'La lista de distribución no coincide con el email esperado.');
	}
}