force-app/main/default/objects/Drawing__c/Drawing__c.object-meta.xml
<CustomObject>
    <description>This object is the place to store all design drawings and pack specs.</description>
    <label>Drawing</label>
    <nameField>
        <label>Drawing Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drawings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OM_VID_Idioma__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Español</fullName>
            </value>
            <value>
                <fullName>Portugués</fullName>
            </value>
            <value>
                <fullName>Francés</fullName>
            </value>
            <value>
                <fullName>Inglés</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/OM_VID_Idioma__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Idioma__c</fullName>
    <description>Guarda el valor del campo Idioma de la Oportunidad relacionada</description>
    <formula>TEXT(Opportunity.OM_VID_Idioma__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Fórmula que guarda el valor del idioma de la Oportunidad relacionada</inlineHelpText>
    <label>Idioma</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OM_VID_EnviarEmailOfertaControllerTest.cls
/**
* @description       :
* @author            : mmadridp@omegacrmconsulting.com
* @group             :
* @last modified on  : 17-04-2024
* @last modified by  : mmadridp@omegacrmconsulting.com
**/
@isTest
public with sharing class OM_VID_EnviarEmailOfertaControllerTest {
    @TestSetup
    static void makeData(){
        OM_VID_TestUtils.createQuotes(1);
        Quote q = [SELECT Id FROM Quote LIMIT 1];
        List<Opportunity> oppList = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        OM_VID_TestUtils.createDrawingWithContentVersion(oppList[0].AccountId/*, oppLine.Product2Id*/);
        Drawing__c draw = [SELECT Id FROM Drawing__c LIMIT 1];
        OM_VID_TestUtils.createOpportunityLineItems(oppList, 1, draw.Id);
        OpportunityLineItem oppLine = [SELECT Id, Quantity, PricebookEntryId, Product2Id, UnitPrice, Description FROM OpportunityLineItem WHERE OpportunityId = :oppList[0].Id LIMIT 1];

        OM_VID_TestUtils.createQuoteLineItem(oppLine, q.Id);
    }
    
    @isTest
    static void validateErrorsTest(){
        Quote q = [SELECT Id, OpportunityId FROM Quote LIMIT 1];
        Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Id = : q.OpportunityId LIMIT 1];
        Contact cont = [SELECT Id FROM Contact LIMIT 1];

        System.debug('MMP QLine: ' + [SELECT Id FROM QuoteLineItem WHERE QuoteId =: q.Id LIMIT 1]);

        Test.startTest();
        String test1 = OM_VID_EnviarEmailOfertaController.validateErrors(q.Id);
        opp.OM_VID_Idioma__c = 'Español';
        opp.Contact__c = cont.Id;
        update opp;
        OM_VID_TestUtils.createContentVersion(q.Id);
        String test2 = OM_VID_EnviarEmailOfertaController.validateErrors(q.Id);
        Test.stopTest();

        System.assertNotEquals(null, test1);
        System.debug('MMP test2: ' + test2);
    }

    @isTest
    static void getTemplateNameFormulaTest(){
        System.assertEquals('ES' + OM_VID_Constants.fiftyTemplateName, OM_VID_EnviarEmailOfertaController.getTemplateNameFormula('Español'));
        System.assertEquals('FR' + OM_VID_Constants.fiftyTemplateName, OM_VID_EnviarEmailOfertaController.getTemplateNameFormula('Francés'));
        System.assertEquals('PT' + OM_VID_Constants.fiftyTemplateName, OM_VID_EnviarEmailOfertaController.getTemplateNameFormula('Portugués'));
        System.assertEquals('EN' + OM_VID_Constants.fiftyTemplateName, OM_VID_EnviarEmailOfertaController.getTemplateNameFormula('Inglés'));
    }
}