force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Any other type</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Consumer_Complaint__c/Consumer_Complaint__c.object-meta.xml
<CustomObject>
    <description>Consumer Complaints Object</description>
    <label>Consumer Complaint</label>
    <nameField>
        <label>Consumer Complaint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumer Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consumer_Complaint__c/fields/Complaint_Type_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Type_Confirmed_Date__c</fullName>
    <description>This Date field is populated when any of; 1-Manufacturing Fault Present, 2-Legal or 3-Injury have Yes selected</description>
    <label>Complaint Type Confirmed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account Object</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consumer Complaints</relationshipLabel>
    <relationshipName>Consumer_Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Independent_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Independent_Analysis__c</fullName>
    <description>Independent Analysis</description>
    <label>Independent Analysis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Injury__c.field-meta.xml
<CustomField>
    <fullName>Injury__c</fullName>
    <description>Consumer Injury</description>
    <label>Injury</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Legal__c.field-meta.xml
<CustomField>
    <fullName>Legal__c</fullName>
    <label>Legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Manufacturing_Fault_Present__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Fault_Present__c</fullName>
    <description>Is there a Manufacturing Fault Present?</description>
    <label>Manufacturing Fault Present</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <description>The Plant related to this complaint</description>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elton</fullName>
            </value>
            <value>
                <fullName>Derrylin</fullName>
            </value>
            <value>
                <fullName>Corsico</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Quality_Managers_Comments__c.field-meta.xml
<CustomField>
    <fullName>Quality_Managers_Comments__c</fullName>
    <label>Quality Managers Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Report_Complete__c.field-meta.xml
<CustomField>
    <fullName>Report_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox that needs to be checked once the internal report has been completed and attached</description>
    <label>Report Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Sample_Arrived__c.field-meta.xml
<CustomField>
    <fullName>Sample_Arrived__c</fullName>
    <description>Date the sample arrived from the Customer</description>
    <label>Sample Arrived</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ScheduledCCEmailsTest.cls
/**
 *  Apex test class of the ScheduledCCEmails.cls
 *
 *  @author  Globant 
 *  @since   July 2023
 */
@isTest
public with sharing class ScheduledCCEmailsTest {

    @TestSetup
    static void makeData(){

        Account acc = new Account();
        acc.Name = 'testAccount';
        insert acc;

        List<Consumer_Complaint__c> ccs = new List<Consumer_Complaint__c>();
        
        for (Integer i = 0; i < 25; i++) {
            Consumer_Complaint__c cc = new Consumer_Complaint__c();
            cc.Customer__c = acc.Id;
            cc.Manufacturing_Fault_Present__c = 'Yes';
            cc.Independent_Analysis__c = 'No';
            ccs.add(cc);
        }
        insert ccs;

        Integer offset = 0;

        for (Consumer_Complaint__c cc : ccs) {
            cc.Sample_Arrived__c = System.today().addDays(offset);
            cc.Complaint_Type_Confirmed_Date__c = System.today().addDays(offset);
            offset--;
        }
        update ccs;
    }

    @isTest
    static void itShouldSetupEmail(){
        
        BusinessHours hours = [SELECT ID FROM BusinessHours WHERE IsDefault = true LIMIT 1];
        List<Consumer_Complaint__c> complaints = [
            SELECT Complaint_Type_Confirmed_Date__c, Sample_Arrived__c, Manufacturing_Fault_Present__c,
                Legal__c, Injury__c, Plant__c, Quality_Managers_Comments__c, Report_Complete__c, Independent_Analysis__c, CreatedDate
            FROM Consumer_Complaint__c 
            WHERE Complaint_Type_Confirmed_Date__c = LAST_N_DAYS:10 OR Sample_Arrived__c = LAST_N_DAYS:30
        ];
        
        Test.startTest();

            Assert.areEqual(0, Limits.getEmailInvocations(), 'No emails should be sent.');

            Map<Integer, List<Consumer_Complaint__c>> ccByDays = ScheduledCCEmails.calculateWorkDays(complaints, hours);
            ScheduledCCEmails.setupEmails(ccByDays);
            
            for (Consumer_Complaint__c cc : complaints) {
                cc.Plant__c = 'Unknown';
            }

            ccByDays = ScheduledCCEmails.calculateWorkDays(complaints, hours);
            ScheduledCCEmails.setupEmails(ccByDays);
            
            for (Consumer_Complaint__c cc : complaints) {
                cc.Plant__c = 'Elton';
            }

            ccByDays = ScheduledCCEmails.calculateWorkDays(complaints, hours);
            ScheduledCCEmails.setupEmails(ccByDays);
    
            for (Consumer_Complaint__c cc : complaints) {
                cc.Plant__c = 'Derrylin';
            }

            ccByDays = ScheduledCCEmails.calculateWorkDays(complaints, hours);
            ScheduledCCEmails.setupEmails(ccByDays);
    
            for (Consumer_Complaint__c cc : complaints) {
                cc.Plant__c = 'Corsico';
            }

            ccByDays = ScheduledCCEmails.calculateWorkDays(complaints, hours);
            ScheduledCCEmails.setupEmails(ccByDays);
    
            for (Consumer_Complaint__c cc : complaints) {
                cc.Plant__c = null;
                cc.Manufacturing_Fault_Present__c = null;
            }

            ccByDays = ScheduledCCEmails.calculateWorkDays(complaints, hours);
            ScheduledCCEmails.setupEmails(ccByDays);
    
            for (Consumer_Complaint__c cc : complaints) {
                cc.Independent_Analysis__c = 'Yes';
                cc.Manufacturing_Fault_Present__c = 'Yes';
            }

            ccByDays = ScheduledCCEmails.calculateWorkDays(complaints, hours);
            ScheduledCCEmails.setupEmails(ccByDays);
    
            ScheduledCCEmails s = new ScheduledCCEmails();
            String sch = '0 0 0 31 DEC ? 2030';
            String jobId = System.schedule('Test Job', sch, s);

            // Assert that the job has been scheduled
            Assert.areNotEqual(null, jobId, 'Job Id should be create.');

            // Use other assertions as needed to check job properties, such as the job name, schedule time, etc.
            CronTrigger scheduledJob = [SELECT Id, CronExpression, NextFireTime FROM CronTrigger WHERE Id = :jobId];
            Assert.areNotEqual(null, scheduledJob, 'Job should be scheduled.');
            Assert.areEqual(7, Limits.getEmailInvocations(), 'Emails should be sent.');
        Test.stopTest();
    }

    @isTest
    static void itShouldNotSetupEmail(){
        
        Test.startTest();

            Assert.areEqual(0, Limits.getEmailInvocations(), 'No emails should be sent.');
    
            ScheduledCCEmails s = new ScheduledCCEmails();
            String sch = '0 0 0 31 DEC ? 2030';
            String jobId = System.schedule('Test Job', sch, s);

            // Assert that the job has been scheduled
            Assert.areNotEqual(null, jobId, 'Job Id should be create.');

            // Use other assertions as needed to check job properties, such as the job name, schedule time, etc.
            CronTrigger scheduledJob = [SELECT Id, CronExpression, NextFireTime FROM CronTrigger WHERE Id = :jobId];
            Assert.areNotEqual(null, scheduledJob, 'Job should be scheduled.');
            Assert.areEqual(0, Limits.getEmailInvocations(), 'Emails should be sent.');
        Test.stopTest();
    }

    @isTest
    static void itShouldCreateGroupMembersByPlantMap(){

        Test.startTest();

            Map<String, Map<Id, GroupMember>> groupMemberMap = ScheduledCCEmails.getGroupMembersMapByDeveloperName();
            Map<String, List<GroupMember>> groupNumbers = ScheduledCCEmails.createGroupMembersByPlantMap(groupMemberMap);
            
            //Assert
            Assert.areEqual(4, groupNumbers.size(), 'It should have group numbers.');
        Test.stopTest();
    }

    @isTest
    static void itShouldNotCreateGroupMembersByPlantMap(){

        String errorMessage;

        Test.startTest();

            try {
                
                Map<String, List<GroupMember>> groupNumbers = ScheduledCCEmails.createGroupMembersByPlantMap(null);
            } catch (Exception ex) {
                
                errorMessage = ex.getMessage();
            }
            
            //Assert
            Assert.areNotEqual(null, errorMessage, 'It should throw error.');
        Test.stopTest();
    }

    @isTest
    static void itShouldGetEmailTemplateMapByDeveloperName(){

        Test.startTest();

            Map<String, EmailTemplate> templates = ScheduledCCEmails.getEmailTemplateMapByDeveloperName();
            
            //Assert
            Assert.areEqual(4, templates.size(), 'It should have templates.');
        Test.stopTest();
    }

    @isTest
    static void itShouldInitiateDateTimeWith9PM(){

        DateTime now = System.now();
        now = DateTime.newInstance(now.year(), now.month(), now.day(), 21, 00, 0);

        Test.startTest();

            DateTime dt = ScheduledCCEmails.initiateDateTimeWith9PM();
            
            //Assert
            Assert.areEqual(now, dt, 'It should have initial datetime as 9 PM.');
        Test.stopTest();
    }

    @isTest
    static void itShouldAddEmailToStoredEmailTemplate(){

        BusinessHours hours = [SELECT ID FROM BusinessHours WHERE IsDefault = true LIMIT 1];
        List<Consumer_Complaint__c> complaints = [
            SELECT Complaint_Type_Confirmed_Date__c, Sample_Arrived__c, Manufacturing_Fault_Present__c,
                Legal__c, Injury__c, Plant__c, Quality_Managers_Comments__c, Report_Complete__c, Independent_Analysis__c, CreatedDate
            FROM Consumer_Complaint__c 
            WHERE Complaint_Type_Confirmed_Date__c = LAST_N_DAYS:10 OR Sample_Arrived__c = LAST_N_DAYS:30
        ];

        Map<String, EmailTemplate> templates = ScheduledCCEmails.getEmailTemplateMapByDeveloperName();
        Map<String, Map<Id, GroupMember>> groupMemberMap = ScheduledCCEmails.getGroupMembersMapByDeveloperName();
        
        Test.startTest();

            List<Messaging.SingleEmailMessage> singleMessage = ScheduledCCEmails.addEmailToStoredEmailTemplate(
                groupMemberMap.get('Consumer_Complaints_Admin').values(),
                templates.get('X3_Days_and_no_QM_Comments').Id,
                complaints.get(0)
            );
            
            //Assert
            Assert.areNotEqual(null, singleMessage, 'It should add email template.');
        Test.stopTest();
    }

    @isTest
    static void itShouldNotAddEmailToStoredEmailTemplate(){
        
        String errorMessage;

        Test.startTest();

            try {
                
                List<Messaging.SingleEmailMessage> singleMessage = ScheduledCCEmails.addEmailToStoredEmailTemplate(
                    null, null, null
                );
            } catch (Exception ex) {
                
                errorMessage = ex.getMessage();
            }
            //Assert
            Assert.areNotEqual(null, errorMessage, 'It should throw Error.');
        Test.stopTest();
    }
}