force-app/main/default/objects/Account/fields/Account_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Account_Credit_Limit__c</fullName>
    <description>Finance Department set Credit Limit for all Customer Accounts</description>
    <inlineHelpText>Finance Department set Credit Limit for all Customer Accounts</inlineHelpText>
    <label>Account Credit Limit</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <description>VAT Number Required by Spain Vidrala Users</description>
    <label>VAT Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ClienteVIP__c.field-meta.xml
<CustomField>
    <fullName>ClienteVIP__c</fullName>
    <description>Vidrala require - this is how they score clients at the end of the year i.e. yes we want them</description>
    <label>Scoring</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESPECIAL</fullName>
            </value>
            <value>
                <fullName>PREFERENTE</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Block__c.field-meta.xml
<CustomField>
    <fullName>Credit_Block__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This account has been flagged by Encirc Finance as blocked for credit.</inlineHelpText>
    <label>Credit Block</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Service__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Service</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market that holds the Budget</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_AgreedTerms__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_AgreedTerms__c</fullName>
    <label>Agreed Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZD</fullName>
                <label>Daily Invoicing</label>
            </value>
            <value>
                <fullName>ZM</fullName>
                <label>Monthly Invoicing</label>
            </value>
            <value>
                <fullName>ZQ</fullName>
                <label>Bi-weekly invoicing</label>
            </value>
            <value>
                <fullName>ZS</fullName>
                <label>Weekly invoicing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_Blocked__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_ClaseRiesgo__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_ClaseRiesgo__c</fullName>
    <label>Clase de riesgo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z01</fullName>
                <label>Orders new customer 2 years</label>
            </value>
            <value>
                <fullName>Z02</fullName>
                <label>New customer</label>
            </value>
            <value>
                <fullName>Z03</fullName>
                <label>Standard customer</label>
            </value>
            <value>
                <fullName>Z04</fullName>
                <label>High Risk Sales Orders</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_CustomerClass__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_CustomerClass__c</fullName>
    <label>Customer Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z1</fullName>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Z2</fullName>
                <label>Distributor</label>
            </value>
            <value>
                <fullName>Z3</fullName>
                <label>Competitor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_Industry__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Industry</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>B01 Wines</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>B02 Waters</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>B03 Cava, spark,cidr</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>B04 Dairy products</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>B05 Soft and non-alc</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>B06 Spirits alcohol</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>B07 Oils</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>B08 Vinegars</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>B09 Juicesnarrowmout</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>B10 Returnable beers</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>B11 Various</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>B12 Port</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>B13 FAB&apos;s</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>T01 Olives</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>T02 Juiceswidemouth</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>T03 Dairy products</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>T04 Baby Food</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>T05 Preserves</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>T06 Sundries</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_NIF__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_NIF__c</fullName>
    <label>NIF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_PaymentMethods__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_PaymentMethods__c</fullName>
    <label>Payment Methods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Immediate payment without deduction</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Cash against documents</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Documentary remittance to 60 days against delivery</label>
            </value>
            <value>
                <fullName>AF00</fullName>
                <label>C. conf al contado</label>
            </value>
            <value>
                <fullName>AF15</fullName>
                <label>C. conf a 15 días</label>
            </value>
            <value>
                <fullName>AF30</fullName>
                <label>C. conf a 30 días</label>
            </value>
            <value>
                <fullName>AF35</fullName>
                <label>C. conf a 35 días</label>
            </value>
            <value>
                <fullName>AF3B</fullName>
                <label>C. conf a 30 días (20)</label>
            </value>
            <value>
                <fullName>AF3C</fullName>
                <label>C. conf a 30 días (15)</label>
            </value>
            <value>
                <fullName>AF4A</fullName>
                <label>C. conf a 45 días (30)</label>
            </value>
            <value>
                <fullName>AF4B</fullName>
                <label>C. conf a 45 días (10,25)</label>
            </value>
            <value>
                <fullName>AF5B</fullName>
                <label>C. conf a 55 días (30)</label>
            </value>
            <value>
                <fullName>AF60</fullName>
                <label>C. conf a 60 días</label>
            </value>
            <value>
                <fullName>AF6A</fullName>
                <label>C. conf a 60 días (1,15)</label>
            </value>
            <value>
                <fullName>AF6B</fullName>
                <label>C. conf a 60 días (15)</label>
            </value>
            <value>
                <fullName>AF6C</fullName>
                <label>C. conf a 60 días (15,30)</label>
            </value>
            <value>
                <fullName>AF6D</fullName>
                <label>C. conf a 60 días (25)</label>
            </value>
            <value>
                <fullName>AF6E</fullName>
                <label>C. conf a 60 días (10,20,30)</label>
            </value>
            <value>
                <fullName>AF6F</fullName>
                <label>C. conf a 60 días (10,25)</label>
            </value>
            <value>
                <fullName>AF6G</fullName>
                <label>C. conf a 60 días (10)</label>
            </value>
            <value>
                <fullName>AF6I</fullName>
                <label>C. conf a 65 días (25)</label>
            </value>
            <value>
                <fullName>AF6J</fullName>
                <label>C. conf a 60 días (12,27)</label>
            </value>
            <value>
                <fullName>AF6K</fullName>
                <label>C. conf a 60 días (12,26)</label>
            </value>
            <value>
                <fullName>AF6L</fullName>
                <label>C. conf a 60 días (20)</label>
            </value>
            <value>
                <fullName>AF6M</fullName>
                <label>C. conf a 60 días (5,20)</label>
            </value>
            <value>
                <fullName>AF6N</fullName>
                <label>Confirminf a 60 días, día fijo 30</label>
            </value>
            <value>
                <fullName>AF6O</fullName>
                <label>C. conf a 60 días (17)</label>
            </value>
            <value>
                <fullName>AF70</fullName>
                <label>C. conf a 70 días</label>
            </value>
            <value>
                <fullName>AF75</fullName>
                <label>C. conf a 75 días (5,15,25)</label>
            </value>
            <value>
                <fullName>AF7A</fullName>
                <label>C. conf a 75 días (5,20)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_SalesOrganizations__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_SalesOrganizations__c</fullName>
    <label>Sales Organizations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VD10</fullName>
            </value>
            <value>
                <fullName>VD50</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_SyncStamp__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_SyncStamp__c</fullName>
    <label>Sync Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_SyncStatus__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Admin_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Sales_Admin_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Admin</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Office</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesOffices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customers.recordType-meta.xml
<RecordType>
    <fullName>Customers</fullName>
    <active>true</active>
    <description>Past or Present</description>
    <label>Customers</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>Distributors for Vidrala (Encirc &amp; Fifty)</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/OM_VID_Destinatario.recordType-meta.xml
<RecordType>
    <fullName>OM_VID_Destinatario</fullName>
    <active>true</active>
    <label>Ship to party</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/OM_VID_Grupo.recordType-meta.xml
<RecordType>
    <fullName>OM_VID_Grupo</fullName>
    <active>true</active>
    <label>Grupo</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Any other type</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/User/fields/SAP_UserNumber__c.field-meta.xml
<CustomField>
    <fullName>SAP_UserNumber__c</fullName>
    <externalId>true</externalId>
    <label>SAP User Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>NM</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>RM</fullName>
        <isActive>false</isActive>
        <label>RM</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <isActive>false</isActive>
        <label>RO</label>
    </customValue>
    <description>geographically sales are divided in 4 markets</description>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OM_SAP_UpsertCustomerWS.cls
@RestResource(urlMapping='/upsertCustomerInSf')
global with sharing class OM_SAP_UpsertCustomerWS {
    
    // WRAPPER PARA LA RESPUESTA DEL WS DE SF
    public class SFWS_Response {
        public boolean status;
        public String msg;
        public String accountId;
        public String sapCode;
        public String code;
        public List<String> salesforceErrors;
        public String successMessage;
    }
    
    public static SFWS_Response createResponse(Boolean status, String msg, String accountId, String code, List<String> errors, String successMessage, String sapCode, String requestParam) {
        
        // Generate the response        
        SFWS_Response respWrapper = new SFWS_Response();
        respWrapper.status = status;
        respWrapper.msg = msg;
        respWrapper.accountId = accountId;
        respWrapper.sapCode = sapCode;
        respWrapper.code = code;
        respWrapper.salesforceErrors = errors;
        respWrapper.successMessage = successMessage;

        if(!String.isBlank(accountId) && accountId.startsWith('001')){
            // set the sync status -> yes I know it's a double update, but I don't find any other easy way to do
            OM_Utils.shouldSkipTriggerGlobal = true; // Ignore the triggers in this update to accelerate the execution
            try{
                update new Account(Id = accountId, OM_VID_SyncStatus__c = (status ? 'Sync' : 'Failed'), OM_VID_SyncStamp__c = System.now()); 
            }catch(DmlException e){
                status = false; // Set the failure in the integration record
                respWrapper.salesforceErrors.add('Error setting the Sync Status in the Account record: ' + accountId);
            }
            
            OM_Utils.shouldSkipTriggerGlobal = false;
        }

        // Write the integration Message
        OM_Utils.IntegrationMsg.createRESTIntegrationMsg(OM_Utils.IntegrationMsg.INBOUND, '/upsertCustomerInSf', 'POST');
        OM_Utils.IntegrationMsg.addBody(requestParam, JSON.serialize(respWrapper));
        OM_Utils.IntegrationMsg.addStatusAndRecord((status ? OM_Utils.IntegrationMsg.SUCCESS : OM_Utils.IntegrationMsg.ERROR), accountId, null, sapCode );
        OM_Utils.IntegrationMsg.insertRecord();
        
        return respWrapper;
    }
    
    @HttpPost
    global static void handlePostRequest(){
        // Method to return to SAP always the same kind of response 
        // This will catch any kind of error 
        
        RestRequest req = RestContext.request;
        String requestString = req.requestBody.toString();
        try{
            processRequest(requestString);
        }catch(Exception e){
            RestContext.response.addHeader('Content-Type', 'application/json');
            SFWS_Response responseObj = createResponse(false, 'Error not known', null, '400', new list<String>{e.getMessage(), e.getStackTraceString()}, null, 'Bad request', requestString);
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseObj));
            return;
        }
    }
    
    global static void processRequest(String requestString) {
        List<String> salesforceErrors = new List<String>();
        String responseMessage = '';
        String successMessage = 'Upserts operations completed successfully.';
        SFWS_Response responseObj;
        List<String> validRecordTypes = new List<String>{'Z010','Z011','Z018','Z016'};
        List<String> customersToExclude = new List<String>{'300126', '300830', '300130','300660','300827','300038','301021','300829','15987','17380','20380','21366',
            '21470','23927','24974','25628','28505','28561','32083','33034','16592'};

        OM_SAP_Wrappers.CustomerWrapper wrapperInstance;
        try {// Deserialization block
            wrapperInstance = (OM_SAP_Wrappers.CustomerWrapper)JSON.deserialize(requestString, OM_SAP_Wrappers.CustomerWrapper.class);
            System.debug('INBOUND PAYLOAD ' + JSON.serialize(wrapperInstance));
        } catch (Exception e) {
            salesforceErrors.add('Error during deserialization: ' + e.getMessage());
            RestContext.response.statusCode = 400; // Bad Request
            RestContext.response.addHeader('Content-Type', 'application/json');
            responseObj = createResponse(false, responseMessage, null, '400', salesforceErrors, null, 'Bad request', requestString);
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseObj));
            return;
        }
        
        List<Account> accountsToUpsert = new List<Account>(); // When reduce technical debt, change this into only 1 record
        
        if(wrapperInstance != null && !String.isBlank(wrapperInstance.customerCode)){
            if((!String.isBlank(wrapperInstance.recordType) && validRecordTypes.contains(wrapperInstance.recordType)) && (wrapperInstance.recordType.equalsIgnoreCase('Z018') ||
              (!customersToExclude.contains(wrapperInstance.customerCode) && !customersToExclude.contains(wrapperInstance.parentCustomer)))){
                  System.debug('***wrapperInstance.customerClass: '+!String.isBlank(wrapperInstance.customerClass));
                  System.debug('***wrapperInstance.customerClass: '+wrapperInstance.customerClass.equalsIgnoreCase('Z4'));
                  System.debug('***wrapperInstance.customerClass: '+wrapperInstance.customerClass);
                  
   
                    /** Start building the account record */
                    Account accountUpsert = new Account();
                    accountUpsert.SAP_Account_Number__c = wrapperInstance.customerCode;
                    accountUpsert.Name = wrapperInstance.customerName;
                    if(!String.isBlank(wrapperInstance.blocked)) accountUpsert.OM_VID_Blocked__c = true; //Si viene un valor es que está bloqueado.
                    if(!String.isBlank(wrapperInstance.parentCustomer) && !wrapperInstance.parentCustomer.replaceFirst('^0+', '').equals(wrapperInstance.customerCode)){
                        accountUpsert.Parent = new Account(SAP_Account_Number__c = wrapperInstance.parentCustomer.replaceFirst('^0+', ''));
                    } 
                    
                    // Address information
                    if (wrapperInstance.address != null) {
                        String billingStreetAux = 
                            (wrapperInstance.address.street  != null ? wrapperInstance.address.street +  '\n' : '');
                        accountUpsert.BillingStreet = OM_Utils.Strings.abbreviate(billingStreetAux, Schema.Account.BillingStreet.getDescribe().getLength());
                        accountUpsert.BillingPostalCode = wrapperInstance.address.postalCode;
                        accountUpsert.BillingCountry = wrapperInstance.address.country;
                        accountUpsert.BillingState = wrapperInstance.address.state;
                        accountUpsert.BillingCity = wrapperInstance.address.city;
                        accountUpsert.BillingLongitude = wrapperInstance.address.coordX;
                        accountUpsert.BillingLatitude = wrapperInstance.address.coordY;
                        
                    }
                    
                    accountUpsert.CIF__c = wrapperInstance.vatNumber;
                    if(!wrapperInstance.nif.equalsIgnoreCase('/') && !wrapperInstance.nif.equalsIgnoreCase('"/\"')) accountUpsert.OM_VID_NIF__c = wrapperInstance.nif; 
                    if(wrapperInstance.phone != null) {
                        accountUpsert.Phone = wrapperInstance.phone; 
                    }
                    
                    if(wrapperInstance.industry != null && !wrapperInstance.industry.equalsIgnoreCase('/')){
                        accountUpsert.OM_VID_Industry__c = wrapperInstance.industry; //METER EN SALES ORGANIZATION
                    }
                    
                     
                    if(wrapperInstance.recordType != null){
                        switch on wrapperInstance.recordType {
                            when 'Z010', 'Z011' {
                                accountUpsert.RecordTypeId = OM_Utils.RecordTypes.getRecordTypeByDevName('Account', 'Customers');
                                //if(!String.isBlank(wrapperInstance.parentCustomer)) accountUpsert.Parent = new Account(SAP_Account_Number__c = wrapperInstance.parentCustomer.replaceFirst('^0+', ''));
                                if(!String.isBlank(wrapperInstance.customerClass) && !wrapperInstance.customerClass.equalsIgnoreCase('Z4')){
                                    accountUpsert.OM_VID_CustomerClass__c = wrapperInstance.customerClass;
                                }else{
                                    salesforceErrors.add('Error with data. Customer class "Z4" is not allowed on Customers: '+ wrapperInstance.customerClass);
                                    RestContext.response.statusCode = 400; // Bad Request
                                    RestContext.response.addHeader('Content-Type', 'application/json');
                                    responseObj = createResponse(false, 'Wrong Data', null, '400', salesforceErrors, null, wrapperInstance.customerCode, requestString);
                                    RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseObj));
                                      
                                }
                            }
                            when 'Z018' {
                                accountUpsert.RecordTypeId = OM_Utils.RecordTypes.getRecordTypeByDevName('Account', 'OM_VID_Destinatario');
                                //if(!String.isBlank(wrapperInstance.parentCustomer)) accountUpsert.Parent = new Account(SAP_Account_Number__c = wrapperInstance.parentCustomer.replaceFirst('^0+', ''));
                            }
                            when 'Z016' {
                                accountUpsert.RecordTypeId = OM_Utils.RecordTypes.getRecordTypeByDevName('Account', 'OM_VID_Grupo');
                            }
                        } 
                        //ZO10, Z011 --> CLIENTE , Z018 --> Destinatario de mercancías, Z016 --> Grupo //Record type distributor lo vamos a meter en cliente (Mirar como afecta)
                    }
                    
                    if(wrapperInstance.creditSegment != null){ 
                        //De momento solo vamos a tratar los creditSegment del array que tengan TerritoryCode = Z001 (Vidrala). Más adelante se cogerán todos y se fragmentarán en los nuevos objetos del modelo de datos
                        for(OM_SAP_Wrappers.CreditSegment crSeg : wrapperInstance.creditSegment){
                            if(crSeg.territoryCode.equalsIgnoreCase('Z001')){
                                if(crSeg.creditLimit != null && crSeg.creditLimit != 0) accountUpsert.Account_Credit_Limit__c = crSeg.creditLimit;//PDTE CAMBIO
                                accountUpsert.OM_VID_ClaseRiesgo__c = crSeg.creditStatus; //Clase de riesgo nuevo campo - mapearlo con el campo de la estructura creditStatus
                                accountUpsert.Credit_Block__c = crSeg.creditBlock;
                            }
                        }
                    }
                    
                    if(wrapperInstance.salesOrganizations != null){ 
                        String salesOrganizations = '';
                        //De momento solo vamos a tratar los valores del elemento de Sales Organization que tenga VD10. Con el nuevo modelado de datos trataremos todos
                        for(OM_SAP_Wrappers.SalesOrganization salesOrg : wrapperInstance.salesOrganizations){
                            if(String.isBlank(salesOrganizations)) salesOrganizations = salesOrg.organizationCode;
                               else salesOrganizations = salesOrganizations + ';'+salesOrg.organizationCode;
                            if(salesOrg.organizationCode.equalsIgnoreCase('VD10')){
                                if(salesOrg.claseABC.equals('99') || salesOrg.claseABC.equals('98')) accountUpsert.ClienteVIP__c = salesOrg.claseABC;
                                if(!String.isBlank(salesOrg.market)){
                                    switch on salesOrg.market {
                                        when 'ES', 'PT', 'FR' {
                                            accountUpsert.Market__c = salesOrg.market;
                                        }
                                        when else {
                                            accountUpsert.Market__c = 'NM';
                                        }
                                    } 
                                }
                                if(salesOrg.financials != null){
                                    accountUpsert.CurrencyIsoCode = salesOrg.financials.currencyCode;
                                    accountUpsert.OM_VID_AgreedTerms__c = salesOrg.financials.agreedTerms; 
                                    accountUpsert.OM_VID_PaymentMethods__c = salesOrg.financials.paymentMethod;
                                }
                                System.debug('***salesOrg.CustomerTeam: '+salesOrg.CustomerTeam);
                                if(salesOrg.customerTeam != null){
                                    if(salesOrg.customerTeam.salesAdmin != null && !String.isBlank(salesOrg.customerTeam.salesAdmin)) accountUpsert.Sales_Admin_Lookup__r = new User(SAP_UserNumber__c = salesOrg.customerTeam.salesAdmin);
                                    if(salesOrg.customerTeam.customerManager != null && !String.isBlank(salesOrg.customerTeam.customerManager)){
                                        accountUpsert.Account_Manager__r = new User(SAP_UserNumber__c = salesOrg.customerTeam.customerManager);
                                        accountUpsert.Owner = new User(SAP_UserNumber__c = salesOrg.customerTeam.customerManager);
                                    }
                                    
                                    if(salesOrg.customerTeam.customerService != null && !String.isBlank(salesOrg.customerTeam.customerService)) accountUpsert.Customer_Service__r = new User(SAP_UserNumber__c = salesOrg.customerTeam.customerService);
                                    if(salesOrg.customerTeam.salesOffice != null && !String.isBlank(salesOrg.customerTeam.salesOffice)) accountUpsert.Sales_Office__r = new User(SAP_UserNumber__c = salesOrg.customerTeam.salesOffice);
                                }                    
                            }
                        }
                        
                        if(!String.isBlank(salesOrganizations)) accountUpsert.OM_VID_SalesOrganizations__c = salesOrganizations; 
                    }
        
                    accountsToUpsert.add(accountUpsert);
                    // Upsert accounts
                    Database.DMLOptions dml = new Database.DMLOptions(); 
                    dml.DuplicateRuleHeader.AllowSave = true;
                    Schema.SObjectField sapCode = Account.SAP_Account_Number__c;
                    Database.UpsertResult[] accountUpsertResults = Database.upsert(accountsToUpsert, sapCode, false); //Database.upsert(accountsToUpsert, f, false); 
                    Map<String, String> upsertErrors = OM_Utils.DmlResults.getErrorsMap(accountUpsertResults, accountsToUpsert, 'SAP_Account_Number__c');
        
                    if(!upsertErrors.isEmpty()){ // manage the errors
                        salesforceErrors.add('Exception trying to upsert Account: ' + JSON.serialize(upsertErrors));
                    }else{ // If no errors for accounts, we can continue with the junction records
                        /** Start building the account SalesArea Junction record */
                        
                        /** End building the account SalesArea Junction record */
                        
                    }
                    /** End building the account record */
        
                    // Determine response based on errors
                    if (salesforceErrors.isEmpty()) {
                        RestContext.response.statusCode = 200;
                        responseObj = createResponse(true, responseMessage, !accountsToUpsert.isEmpty() ? accountsToUpsert.get(0).Id : null, '200', salesforceErrors, successMessage, wrapperInstance.customerCode, requestString);
                        // RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseObj));
                    } else {
                        RestContext.response.statusCode = 500;
                        responseObj = createResponse(false, responseMessage, !accountsToUpsert.isEmpty() ? accountsToUpsert.get(0).Id : null, '500', salesforceErrors, null, wrapperInstance.customerCode, requestString);
                        
                    }
        
                    RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseObj));
                    RestContext.response.addHeader('Content-Type', 'application/json');
                  
                  
            }else{
                salesforceErrors.add('Error with data. RecordType is empty or doesn\'t match the record type value list (Z010, Z011, Z016, Z018), or the customer belongs to the customer exclusion list: ' + wrapperInstance.recordType + ' - '+wrapperInstance.customerCode);
                RestContext.response.statusCode = 400; // Bad Request
                RestContext.response.addHeader('Content-Type', 'application/json');
                responseObj = createResponse(false, 'Wrong Data', null, '400', salesforceErrors, null, wrapperInstance.customerCode, requestString);
                RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseObj));
            }

        }else{
            salesforceErrors.add('Error with data. Customer code is empty or doesn\'t match the expected format ' + wrapperInstance.customerCode);
            RestContext.response.statusCode = 400; // Bad Request
            RestContext.response.addHeader('Content-Type', 'application/json');
            responseObj = createResponse(false, 'Wrong Data', null, '400', salesforceErrors, null, 'Bad request', requestString);
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseObj));
        }
    }

}