force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/Actual_Sales_History__c.object-meta.xml
<CustomObject>
    <description>Historic report to store, display and report on historic deal summaries with customers</description>
    <label>Actual Sales History</label>
    <nameField>
        <displayFormat>Deal Summary No. {0000}</displayFormat>
        <label>Deal Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Sales History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Actual_Sales_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Deal_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bottle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bottle__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>Actual Sales History</relationshipLabel>
    <relationshipName>Actual_Sales_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>DATEVALUE( TEXT(Year__c)&amp;&quot;-&quot;&amp;
CASE( Month__c,
&apos;Jan&apos;,&apos;01&apos;,
&apos;Feb&apos;,&apos;02&apos;,
&apos;Mar&apos;,&apos;03&apos;,
&apos;Apr&apos;,&apos;04&apos;,
&apos;May&apos;,&apos;05&apos;,
&apos;Jun&apos;,&apos;06&apos;,
&apos;Jul&apos;,&apos;07&apos;,
&apos;Aug&apos;,&apos;08&apos;,
&apos;Sep&apos;,&apos;09&apos;,
&apos;Oct&apos;,&apos;10&apos;,
&apos;Nov&apos;,&apos;11&apos;,
&apos;Dec&apos;,&apos;12&apos;,
&apos;Error&apos;

)



&amp;&quot;-01&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>Jun</fullName>
            </value>
            <value>
                <fullName>Jul</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sep</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SAP Material Code</label>
    <referenceTo>SAP_Material_Code__c</referenceTo>
    <relationshipLabel>Actual Sales History</relationshipLabel>
    <relationshipName>Actual_Sales_History_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Tonnes__c.field-meta.xml
<CustomField>
    <fullName>Tonnes__c</fullName>
    <label>Tonnes</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Volume_000_s__c.field-meta.xml
<CustomField>
    <fullName>Volume_000_s__c</fullName>
    <description>Number of bottles in thousands</description>
    <inlineHelpText>Number of bottles in thousands</inlineHelpText>
    <label>Volume (000&apos;s)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bottle__c/Bottle__c.object-meta.xml
<CustomObject>
    <description>Unique Product Identifiers and Descriptions</description>
    <label>Bottle</label>
    <nameField>
        <label>Bottle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bottle__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <description>Product Code</description>
    <externalId>true</externalId>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>Bottle Identifier</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <label>SAP Material Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Month__c/Month__c.object-meta.xml
<CustomObject>
    <description>Delivery Budgets and Forecasts by Account and Month</description>
    <label>Month Forecast</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Material_Code__c/SAP_Material_Code__c.object-meta.xml
<CustomObject>
    <label>SAP Material Code</label>
    <nameField>
        <label>SAP Material Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Material Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Material_Code__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <label>Bottle</label>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>SAP Material Codes</relationshipLabel>
    <relationshipName>SAP_Material_Codes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <label>Bottle Identifier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesHistoryProvider.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        SalesHistoryProvider.cls
   Description: Provider class for the Actual_Sales_History__c object

   Date         Version Author              Summary of Changes
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Nov 2017     1.0     M.Witchalls(Ciber)  Initial Release
   Sep 2024     1.1     Globant             In Progress(To be Updated)
------------------------------------------------------------------------------------------------------------------------ */

public with sharing class SalesHistoryProvider{

    /**
     * Retrieves `Actual_Sales_History__c` records filtered by account IDs, product names, and year,
     * and organizes them into a map grouped by account ID and product name.
     *
     * @param accountIdSet Set<Id> - A set of account IDs to filter the records.
     * @param prodNameSet Set<String> - A set of product names to filter the records.
     * @param year String - The year to filter the records.
     * @return Map<String, List<Actual_Sales_History__c>> - A map where the key is a combination of account ID and product name,
     *         and the value is a list of `Actual_Sales_History__c` records that match the criteria.
     */
    public Map<String, List<Actual_Sales_History__c>> getSalesHistorysByAccountProduct2(Set<ID> accountIdSet, Set<String> prodNameSet, String year){
        if (accountIdSet == null || accountIdSet.isEmpty()) {
            return new Map<String, List<Actual_Sales_History__c>>();
        }

        if (prodNameSet == null || prodNameSet.isEmpty()) {
            return new Map<String, List<Actual_Sales_History__c>>();
        }

        if (String.isBlank(year)) {
            return new Map<String, List<Actual_Sales_History__c>>();
        }

        Map<String, List<Actual_Sales_History__c>> returnMap = new Map<String, List<Actual_Sales_History__c>>();

        for (List<Actual_Sales_History__c> sList : [
            SELECT
                Id, Name, Account__c, Month__c, Item__c,
                SAP_Material_Code__c, SAP_Material_Code__r.Name, 
                SAP_Material_Code__r.Bottle__c, Bottle__r.Bottle_Identifier__c,
                Date__c, Year__c, Volume_000_s__c, Tonnes__c
            FROM 
                Actual_Sales_History__c
            WHERE
                Account__c IN :accountIdSet
            AND
                Item__c IN :prodNameSet
            AND
                Year__c = :year
        ]) {
            for (Actual_Sales_History__c s : sList) {
                String keyString = s.Account__c + ':' + s.Item__c;

                if (s.Account__c != null && s.Item__c != null) {
                    List<Actual_Sales_History__c> ashList = returnMap.get(keyString);
                    if (ashList == null) {
                        ashList = new List<Actual_Sales_History__c>();
                    }
                    ashList.add(s);
                    returnMap.put(keyString, ashList);
                }
            }
        }

        return returnMap;
    }
}



/*public with sharing class SalesHistoryProvider {
    
    public Map<String, List<Actual_Sales_History__c>> getSalesHistorysByAccountProduct2(
        Set<ID> accountIdSet, Set<String> prodNameSet, String year
    ) {
        Map<String, List<Actual_Sales_History__c>> returnMap = new Map<String, List<Actual_Sales_History__c>>();
        for (List<Actual_Sales_History__c> sList: [
            SELECT
                Id, Name, Account__c, Month__c, Item__c, 
                SAP_Material_Code__c, SAP_Material_Code__r.Name, SAP_Material_Code__r.Bottle__c, Bottle__r.Bottle_Identifier__c,
                Date__c, Year__c, Volume_000_s__c, Tonnes__c             
            FROM 
                Actual_Sales_History__c 
            WHERE
                Account__c IN :accountIdSet
            AND
                Item__c IN :prodNameSet
            AND
                Year__c = :year
        ]) {
            for (Actual_Sales_History__c s: sList) {
                String keyString = s.Account__c + ':' + s.Item__c;
                
                List<Actual_Sales_History__c> ashList = returnMap.get(keyString);
                if (ashList == null) ashList = new List<Actual_Sales_History__c>();
                ashList.add(s);
                returnMap.put(keyString, ashList);
            }
        }
        return returnMap;
    }
    
}*/