force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market that holds the Budget</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Rebate__c.field-meta.xml
<CustomField>
    <fullName>Rebate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Existing rebate on the Account</description>
    <label>Existing Rebate</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rebate__c.Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account_Id_Copy__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rebate__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/Rebate__c.object-meta.xml
<CustomObject>
    <description>Stores and manages information relating to Rebates which have been given to Accounts.</description>
    <label>Rebate</label>
    <nameField>
        <displayFormat>Rebate-{00000}</displayFormat>
        <label>Rebate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rebate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Reason_for_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Rebate__c</fullName>
    <description>Please enter a description of the Rebate including the reason why it is being requested.</description>
    <inlineHelpText>Please enter a description of the Rebate including the reason why it is being requested.</inlineHelpText>
    <label>Reason for Rebate</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Rebate_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Commencement_Date__c</fullName>
    <label>Rebate Commencement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Rebate_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Expiry_Date__c</fullName>
    <label>Rebate Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>NM</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>RM</fullName>
        <isActive>false</isActive>
        <label>RM</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <isActive>false</isActive>
        <label>RO</label>
    </customValue>
    <description>geographically sales are divided in 4 markets</description>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotePDFControllerExtensionTest.cls
@isTest
private class QuotePDFControllerExtensionTest {
    
    @IsTest private static void testController() {
        Quote testQuote = TestDataFactory.createQuote();
        Account testAcc = [
            SELECT Id, Name, Market__c 
            FROM Account
            LIMIT 1
        ];
        Rebate__c reb = new Rebate__c(
            Account__c = testAcc.Id,
            Rebate_Commencement_Date__c = System.today(),
            Rebate_Expiry_Date__c = System.today() + 1,
            Reason_for_Rebate__c = 'Reason'
        );
        insert reb;
       
        PageReference pageRef = Page.QuotePDF; 
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(testQuote.Id));
        ApexPages.StandardController quoteController = new ApexPages.StandardController(testQuote);
        
        QuotePDFControllerExtension testQuotePDF = new QuotePDFControllerExtension(quoteController);
        QuotePDFControllerExtension.QuoteItemWrapper testWrapper = new QuotePDFControllerExtension.QuoteItemWrapper('', '', '', '', 0);

        System.assertEquals('VIDRALA FRANCE', testQuotePDF.accountName);
        
        testAcc.Market__c = 'PT';
        update testAcc;

        QuotePDFControllerExtension testQuotePDFPT = new QuotePDFControllerExtension(quoteController);
        System.assertEquals('VIDRALA, S.A.', testQuotePDFPT.accountName);

        testAcc.Market__c = 'ES';
        update testAcc;

        QuotePDFControllerExtension testQuotePDFES = new QuotePDFControllerExtension(quoteController);
        System.assertEquals('VIDRALA, S.A.', testQuotePDFES.accountName);

        testAcc.Market__c = 'FR';
        update testAcc;

        QuotePDFControllerExtension testQuotePDFRM = new QuotePDFControllerExtension(quoteController);
        System.assertEquals('commercial@vidrala.com', testQuotePDFRM.accountEmail);

        testAcc.Market__c = 'NM';
        update testAcc;

        QuotePDFControllerExtension testQuotePDFNM = new QuotePDFControllerExtension(quoteController);
        System.assertEquals('export@vidrala.com', testQuotePDFNM.accountEmail);
        
    }
}