force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recalculate_Apex_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Apex_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables a System Administrator to redo the Apex Sharing on Child Objects</description>
    <label>Recalculate Apex Sharing on Save</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Commercial_Contracts__c/Commercial_Contracts__c.object-meta.xml
<CustomObject>
    <label>Commercial Contract</label>
    <nameField>
        <label>Commercial Contracts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Commercial_Contracts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commercial Contracts</relationshipLabel>
    <relationshipName>Commercial_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tender_Stroke_Quotes__c/Customer_Tender_Stroke_Quotes__c.object-meta.xml
<CustomObject>
    <label>Customer Tender / Quotes</label>
    <nameField>
        <label>Customer Tender Stroke Quotes  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Tender / Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tender_Stroke_Quotes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Tender_Stroke_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/Pricing_Model__c.object-meta.xml
<CustomObject>
    <description>Object use for each Pricing Model request.</description>
    <label>Pricing Model</label>
    <nameField>
        <displayFormat>PrM-{0000}</displayFormat>
        <label>Pricing Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Model__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales field</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Models</relationshipLabel>
    <relationshipName>Pricing_Models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/Rebate__c.object-meta.xml
<CustomObject>
    <description>Stores and manages information relating to Rebates which have been given to Accounts.</description>
    <label>Rebate</label>
    <nameField>
        <displayFormat>Rebate-{00000}</displayFormat>
        <label>Rebate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rebate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        AccountTriggerHandler.cls
   Description: Handler class for processing of the Accounts
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Oct 2024     1.0     globant             After update, recalculate child object Apex sharing if Account Owner has changed 
                                            or Recalculate_Apex_Sharing__c = true
------------------------------------------------------------------------------------------------------------------------ */        
public with sharing class AccountTriggerHandler {

    public static void processAccountRecords(List<Account> triggerNew, Map<Id, Account> triggerOldMap) {

        //Change Month Forecast Owners if Owner has changed
        ForecastHandler handler = new ForecastHandler();
        handler.copyChangedAccountOwner(triggerNew, triggerOldMap);
        
        //Sharing changes on change of Account Owner
        //In all cases below, action only if Owner has changed or Recalculate_Apex_Sharing__c = true
        ApexSharingManager sharingManager1 = new ApexSharingManager(
            Schema.SObjectType.Rebate__c.Name, 
            Schema.Rebate__Share.rowCause.Apex__c
        );
        sharingManager1.newAccountOwner(Schema.SObjectType.Rebate__c.Fields.Account__c.RelationshipName, triggerNew, triggerOldMap); 
        
        ApexSharingManager sharingManager2 = new ApexSharingManager(
            Schema.SObjectType.Commercial_Contracts__c.Name, 
            Schema.Commercial_Contracts__Share.rowCause.Apex__c
        );
        sharingManager2.newAccountOwner(Schema.SObjectType.Commercial_Contracts__c.Fields.Account__c.RelationshipName, triggerNew, triggerOldMap); 
        
        ApexSharingManager sharingManager3 = new ApexSharingManager(
            Schema.SObjectType.Customer_Tender_Stroke_Quotes__c.Name, 
            Schema.Commercial_Contracts__Share.rowCause.Apex__c
        );
        sharingManager3.newAccountOwner(Schema.SObjectType.Customer_Tender_Stroke_Quotes__c.Fields.Account__c.RelationshipName, triggerNew, triggerOldMap); 
        
        ApexSharingManager sharingManager4 = new ApexSharingManager(
            Schema.SObjectType.Pricing_Model__c.Name, 
            Schema.Commercial_Contracts__Share.rowCause.Apex__c
        );
        sharingManager4.newAccountOwner(Schema.SObjectType.Pricing_Model__c.Fields.Account__c.RelationshipName, triggerNew, triggerOldMap); 
    }
}