force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commercial_Contracts__c/Commercial_Contracts__c.object-meta.xml
<CustomObject>
    <label>Commercial Contract</label>
    <nameField>
        <label>Commercial Contracts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Commercial_Contracts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commercial Contracts</relationshipLabel>
    <relationshipName>Commercial_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Tender_Stroke_Quotes__c/Customer_Tender_Stroke_Quotes__c.object-meta.xml
<CustomObject>
    <label>Customer Tender / Quotes</label>
    <nameField>
        <label>Customer Tender Stroke Quotes  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Tender / Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Tender_Stroke_Quotes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Tender_Stroke_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet__c/Deal_Sheet__c.object-meta.xml
<CustomObject>
    <label>Deal Sheet</label>
    <nameField>
        <label>Deal Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Sheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Sheet__c/fields/ACCOUNT__c.field-meta.xml
<CustomField>
    <fullName>ACCOUNT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Sheets</relationshipLabel>
    <relationshipName>Deal_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Increases__c/Price_Increases__c.object-meta.xml
<CustomObject>
    <label>Price Increases</label>
    <nameField>
        <label>Price Increases Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Increases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Increases__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Increases</relationshipLabel>
    <relationshipName>Price_Increases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Increases__c/fields/Budgeted_Increase__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Increase__c</fullName>
    <label>Budgeted Increase %</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/Pricing_Model__c.object-meta.xml
<CustomObject>
    <description>Object use for each Pricing Model request.</description>
    <label>Pricing Model</label>
    <nameField>
        <displayFormat>PrM-{0000}</displayFormat>
        <label>Pricing Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Model__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales field</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Models</relationshipLabel>
    <relationshipName>Pricing_Models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Bottle_Description__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Description__c</fullName>
    <description>Sales field</description>
    <label>Bottle Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beer</fullName>
            </value>
            <value>
                <fullName>FAB</fullName>
            </value>
            <value>
                <fullName>Foods</fullName>
            </value>
            <value>
                <fullName>Mineral water</fullName>
            </value>
            <value>
                <fullName>Soft drink</fullName>
            </value>
            <value>
                <fullName>Spirits</fullName>
            </value>
            <value>
                <fullName>Wine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <description>Sales field</description>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flint</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Malacca</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Autumn Leaf</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Date_Customer_Requires_the_Bottles__c.field-meta.xml
<CustomField>
    <fullName>Date_Customer_Requires_the_Bottles__c</fullName>
    <description>Sales field</description>
    <label>Date Customer Requires the Bottles</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Date_Sales_Require_a_Response__c.field-meta.xml
<CustomField>
    <fullName>Date_Sales_Require_a_Response__c</fullName>
    <description>Sales field</description>
    <label>Date Sales Require a Response</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Delivery_Location__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Location__c</fullName>
    <label>Delivery Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABBEY - Abbeyleix - ABBEY</fullName>
            </value>
            <value>
                <fullName>ABER - Aberdeen - ABER</fullName>
            </value>
            <value>
                <fullName>GLAS - Airdrie - GLAS</fullName>
            </value>
            <value>
                <fullName>DUND - Arbroath - DUND</fullName>
            </value>
            <value>
                <fullName>BAIL - Baileborough - BAIL</fullName>
            </value>
            <value>
                <fullName>BALLY - Ballymena - BALLY</fullName>
            </value>
            <value>
                <fullName>BEL - Belfast - BEL</fullName>
            </value>
            <value>
                <fullName>BARN - Barnsley - BARN</fullName>
            </value>
            <value>
                <fullName>BEDFO - Bedford - BEDFO</fullName>
            </value>
            <value>
                <fullName>BELG - Belgium - BELG</fullName>
            </value>
            <value>
                <fullName>BIRM - Birmingham - BIRM</fullName>
            </value>
            <value>
                <fullName>BRIS - Bristol - BRIS</fullName>
            </value>
            <value>
                <fullName>BURT - Burton on Trent - BURT</fullName>
            </value>
            <value>
                <fullName>BUSH - Bushmills - BUSH</fullName>
            </value>
            <value>
                <fullName>CAM - Cambridgeshire - CAM</fullName>
            </value>
            <value>
                <fullName>WESTS - Chichester - WESTS</fullName>
            </value>
            <value>
                <fullName>CLON - Clonmel - CLON</fullName>
            </value>
            <value>
                <fullName>CUMN - Cumnock - CUMN</fullName>
            </value>
            <value>
                <fullName>DER - Derry - DER</fullName>
            </value>
            <value>
                <fullName>DEV - Devon - DEV</fullName>
            </value>
            <value>
                <fullName>DONE - Donegal - DONE</fullName>
            </value>
            <value>
                <fullName>DUB - Dublin - DUB</fullName>
            </value>
            <value>
                <fullName>DURHA - Durham - DURHA</fullName>
            </value>
            <value>
                <fullName>GLAS - East Kilbride - GLAS</fullName>
            </value>
            <value>
                <fullName>ENNI - Enniscorthy - ENNI</fullName>
            </value>
            <value>
                <fullName>FAVE - Faversham - FAVE</fullName>
            </value>
            <value>
                <fullName>GLAS - Glasgow - GLAS</fullName>
            </value>
            <value>
                <fullName>GLOUC - Gloucestershire - GLOUC</fullName>
            </value>
            <value>
                <fullName>GLAS - Grangemouth - GLAS</fullName>
            </value>
            <value>
                <fullName>HAMP - Hampshire - HAMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/For_Export__c.field-meta.xml
<CustomField>
    <fullName>For_Export__c</fullName>
    <label>For Export</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None of the volume will be exported outside of UK/ROI</fullName>
            </value>
            <value>
                <fullName>Some of the volume will be exported outside of UK/ROI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Sales_volume_per_annum_000s_bottles__c.field-meta.xml
<CustomField>
    <fullName>Sales_volume_per_annum_000s_bottles__c</fullName>
    <description>Sales field</description>
    <label>Sales volume per annum (&apos;000s bottles)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Shape__c.field-meta.xml
<CustomField>
    <fullName>Shape__c</fullName>
    <description>Sales field</description>
    <label>Shape</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flask (Concave)</fullName>
            </value>
            <value>
                <fullName>Flask (Oval)</fullName>
            </value>
            <value>
                <fullName>Squares</fullName>
            </value>
            <value>
                <fullName>Rounds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Sales</fullName>
                <default>true</default>
                <label>1 Sales</label>
            </value>
            <value>
                <fullName>2 Planning</fullName>
            </value>
            <value>
                <fullName>3 Design</fullName>
            </value>
            <value>
                <fullName>4 Distribution</fullName>
            </value>
            <value>
                <fullName>5 Finance</fullName>
            </value>
            <value>
                <fullName>6 Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Model__c/fields/Years_per_contract__c.field-meta.xml
<CustomField>
    <fullName>Years_per_contract__c</fullName>
    <description>Sales field</description>
    <label>Years per contract</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rebate__c/Rebate__c.object-meta.xml
<CustomObject>
    <description>Stores and manages information relating to Rebates which have been given to Accounts.</description>
    <label>Rebate</label>
    <nameField>
        <displayFormat>Rebate-{00000}</displayFormat>
        <label>Rebate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rebate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestApexSharing.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        TestApexSharing.cls
   Description: Test ApexSharingManager class via associated triggers
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Dec 2016     1.0     M.Witchalls(Ciber)  Initial Release 
   Mar 2017     1.1     M.Witchalls(Cloud9) Also tests change of Month Forecast Owners when Account Owner changed
------------------------------------------------------------------------------------------------------------------------ */        
@isTest
private class TestApexSharing {
    private static String rowCause = 'Apex__c';
    private static String encircProfile = 'Encirc Standard User';
    private static String encircFinanceProfile = 'Encirc Finance/Legal User';
    private static List<User> encircUsers = [SELECT Id FROM User WHERE (Profile.Name = :encircProfile OR Profile.Name = :encircFinanceProfile) AND IsActive = true LIMIT 2];
     
    @isTest static void testShares() {      
        List<Account> aList;
        
        System.runAs (encircUsers[0]) {
            // create one Account
            aList = TestDataFactory.createAccountsWithMonths(1, 10001);
        }
        
        String acctNum = aList[0].SAP_Account_Number__c;
        ID accountId = aList[0].Id;
        ID accountOwnerId = aList[0].ownerId;       

        // create one Commercial Contract
        Commercial_Contracts__c con = new Commercial_Contracts__c(
            Account__c = accountId,
            Name = 'Commercial Contract for '+acctNum
        );
        insert con;
        
        // create one Customer Tender
        Customer_Tender_Stroke_Quotes__c ten = new Customer_Tender_Stroke_Quotes__c(
            Account__c = accountId,
            Name = 'Customer Tender for '+acctNum
        );
        insert ten;
        
        // create one Deal Sheet
        Deal_Sheet__c deal = new Deal_Sheet__c(
            ACCOUNT__c = accountId,
            Name = 'Deal Sheet for '+acctNum
        );
        insert deal;
        
        // create one Price Increases record
        Price_Increases__c pi = new Price_Increases__c(
            Account__c = accountId,
            Name = 'Price Increases for '+acctNum,
            Budgeted_increase__c = 0.2
        );
        insert pi;
        
        Schema.DescribeFieldResult fr1 = Schema.SObjectType.Pricing_Model__c.fields.Status__c;
        Schema.DescribeFieldResult fr2 = Schema.SObjectType.Pricing_Model__c.fields.For_Export__c;
        Schema.DescribeFieldResult fr3 = Schema.SObjectType.Pricing_Model__c.fields.Bottle_Description__c;
        Schema.DescribeFieldResult fr4 = Schema.SObjectType.Pricing_Model__c.fields.Colour__c;
        Schema.DescribeFieldResult fr5 = Schema.SObjectType.Pricing_Model__c.fields.Shape__c;
        Schema.DescribeFieldResult fr6 = Schema.SObjectType.Pricing_Model__c.fields.Delivery_Location__c;

        String status = fr1.getPickListValues()[0].getValue();
        String forExport = fr2.getPickListValues()[0].getValue();
        String bottleDesc = fr3.getPickListValues()[0].getValue();
        String colour = fr4.getPickListValues()[0].getValue();
        String shape = fr5.getPickListValues()[0].getValue();
        String location = fr6.getPickListValues()[0].getValue();
        
        // create one Pricing Model
        Pricing_Model__c mod = new Pricing_Model__c(
            Account__c = accountId,
            Status__c = status,
            Sales_volume_per_annum_000s_bottles__c = 10000,
            Years_per_Contract__c = 10,
            For_Export__c = forExport,
            Date_Customer_Requires_the_Bottles__c = System.today(),
            Date_Sales_Require_a_Response__c = System.today(),
            New_Bottle__c = 'No',
            Bottle_Description__c = bottleDesc,
            Bottle_Segment__c = 'Segment',
            Colour__c = colour,
            Shape__c = shape,
            Bottle_Weight_Grms__c = 200,
            Requires_Engraving__c = 'No',
            General_Sale_Item__c = 'No',
            Drawing_Used__c = 'No',
            Drawing_Attached__c = 'No',
            Pack_Spec_Attached__c = 'Yes',
            Customer_has_Max_Pallet_Height__c = 'No',
            Additional_Buffer_Requirements__c = 'No',           
            Exceptional_Packaging_Requirements__c = 'No',           
            Number_of_Shrink_Wraps__c = '1',
            Strapping__c = 'No',
            Additional_Production_Staff_Required__c = 10
        );
        insert mod;
        
        // create one Rebate
        Rebate__c reb = new Rebate__c(
            Account__c = accountId,
            Rebate_Commencement_Date__c = System.today(),
            Rebate_Expiry_Date__c = System.today() + 1,
            Reason_for_Rebate__c = 'Reason'
        );
        insert reb;
            
        Rebate__Share rebShare = [SELECT Id, AccessLevel, UserOrGroupId, RowCause FROM Rebate__Share WHERE ParentId = :reb.Id AND RowCause = :rowCause];
        System.assertEquals(rebShare.UserOrGroupId, encircUsers[0].Id);

        // Change Account Owner
        aList[0].ownerId = encircUsers[1].Id;
        update aList;
        
        rebShare = [SELECT Id, AccessLevel, UserOrGroupId, RowCause FROM Rebate__Share WHERE ParentId = :reb.Id AND RowCause = :rowCause];
        System.assertEquals(rebShare.UserOrGroupId, encircUsers[1].Id);
        
        // Check Month Owners have changed
        Integer count = [SELECT count() FROM Month__c where OwnerId = :encircUsers[1].Id];
        System.assertEquals(12, count);
    }
    
}