force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agreed_Terms__c.field-meta.xml
<CustomField>
    <fullName>Agreed_Terms__c</fullName>
    <label>Agreed Terms</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Forma_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pago__c</fullName>
    <description>Payment method field used by Vidrala Spain</description>
    <label>Payment method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market that holds the Budget</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <displayFormat>Dcto - {0000}</displayFormat>
        <label>Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/EUR__c.field-meta.xml
<CustomField>
    <fullName>EUR__c</fullName>
    <label>EUR</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/TYPE__c.field-meta.xml
<CustomField>
    <fullName>TYPE__c</fullName>
    <label>TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZDES - Descuento especial</fullName>
            </value>
            <value>
                <fullName>ZDUN - Descuento unitario</fullName>
            </value>
            <value>
                <fullName>ZDVR - Descuento sobre vidrio</fullName>
            </value>
            <value>
                <fullName>ZSKT - Descuento por pronto pago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOT</fullName>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Price_Includes_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Price_Includes_Delivery__c</fullName>
    <description>Define whether the price being offered includes delivery, and if not which ex-works location the price refers to the description above is legacy this field was repurposed by Fifty there is a automation linked to it.</description>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAP</fullName>
                <default>true</default>
                <label>DAP</label>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>EX WORKS</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/Packaging_Agreement__c.object-meta.xml
<CustomObject>
    <description>Vidrala Fifty Spain Object From Org Migration 2021
&quot;Objetivo que agrupa los convenios de embalaje de los materiales de los clientes&quot;</description>
    <label>Packaging Agreement</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Packaging Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packaging Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Packaging_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Packaging Agreements</relationshipLabel>
    <relationshipName>Packaging_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Credit_Price__c.field-meta.xml
<CustomField>
    <fullName>Credit_Price__c</fullName>
    <label>Credit Price</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Debit_Price__c.field-meta.xml
<CustomField>
    <fullName>Debit_Price__c</fullName>
    <label>Debit Price</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Portes_Devolucion__c.field-meta.xml
<CustomField>
    <fullName>Portes_Devolucion__c</fullName>
    <label>Portes Devolución</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Portes Cliente</fullName>
                <default>true</default>
                <label>Portes Cliente</label>
            </value>
            <value>
                <fullName>Portes Vidrala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cuenta__c in spanish org</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fifty_Colour</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo_modelo__c</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusivo</fullName>
            </value>
            <value>
                <fullName>Estandar</fullName>
            </value>
            <value>
                <fullName>Personalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Packaging_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Packaging Agreement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account_Id_Copy__c</field>
            <operation>equals</operation>
            <valueField>Packaging_Agreement__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Packaging_Agreement__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Rebate__c.field-meta.xml
<CustomField>
    <fullName>Rebate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Existing rebate on the Account</description>
    <label>Existing Rebate</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rebate__c.Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account_Id_Copy__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rebate__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scales</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Product and Scales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rebate__c/Rebate__c.object-meta.xml
<CustomObject>
    <description>Stores and manages information relating to Rebates which have been given to Accounts.</description>
    <label>Rebate</label>
    <nameField>
        <displayFormat>Rebate-{00000}</displayFormat>
        <label>Rebate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rebate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Acuerdo__c</description>
    <label>Code</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/EUR__c.field-meta.xml
<CustomField>
    <fullName>EUR__c</fullName>
    <label>EUR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>Condicion__c</description>
    <label>Percentage</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product lookup on Rebate</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Spaing migration User story EVM-115 Rebates on Quotes</description>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Rebate_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Commencement_Date__c</fullName>
    <label>Rebate Commencement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Rebate_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Expiry_Date__c</fullName>
    <label>Rebate Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Scales__c.field-meta.xml
<CustomField>
    <fullName>Scales__c</fullName>
    <description>Escala</description>
    <label>Scales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOT</fullName>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Signature__c.field-meta.xml
<CustomField>
    <fullName>Signature__c</fullName>
    <label>Signature</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/Fifty_Colour.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dark Amber</fullName>
    </customValue>
    <customValue>
        <fullName>Flint</fullName>
    </customValue>
    <customValue>
        <fullName>Dead leaf</fullName>
    </customValue>
    <customValue>
        <fullName>Antique</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Olive Green</fullName>
    </customValue>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>Amber</fullName>
    </customValue>
    <customValue>
        <fullName>Emerald Green</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Half white</fullName>
    </customValue>
    <masterLabel>Fifty Colour</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>NM</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>RM</fullName>
        <isActive>false</isActive>
        <label>RM</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <isActive>false</isActive>
        <label>RO</label>
    </customValue>
    <description>geographically sales are divided in 4 markets</description>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotePDFControllerExtension.cls
public class QuotePDFControllerExtension {
     
    public Quote quot {get; set;}
    public String accountInfo {get; set;}
    public String userQuoteInfo {get; set;}
    public List<QuoteItemWrapper> lineItems {get; set;}
    public List<Rebate__c> rebates {get; set;}
    public List<Rebate__c> childRebates {get; set;}
    public List<Packaging_Agreement__c> packageAgreements {get; set;}
    public List<Rebate__c> accountRebates {get; set;}
    public List<Discount__c> discounts {get; set;}
    public String accountName {get; set;}
    public String accountAddress {get; set;}
    public String accountStreet {get; set;}
    public String accountPhone {get; set;}
    public String accountEmail {get; set;}
    public String accountWebsite {get; set;}
    public String renderDiscount {get; set;}
    public String renderRebates {get; set;}
    public String renderDiscountTitle {get; set;}
    public String renderRebatesAccount {get; set;}
    public String renderThirdPage {get; set;}
    public String renderOnSecondPage {get; set;}
    public String dateFrom {get; set;}
    public String dateTo {get; set;}
    public String signature {get; set;}
    public String userInformation {get; set;}
    public String transporationCost {get; set;}
    public String expireDate {get; set;}
    public String endOfYear {get; set;}
    public Integer rowNumbers {get; set;}
	 
    public QuotePDFControllerExtension(ApexPages.StandardController stdController) {
        rowNumbers = 0;
        renderDiscountTitle = 'none';
        renderDiscount = 'none';
        renderRebates = 'none';
        renderRebatesAccount = 'none';
        renderThirdPage = 'none';
        renderOnSecondPage = '';
        endOfYear = date.newinstance(Date.today().year(), 12, 31).format();
        expireDate = Date.today().addDays(30).format();
    	Quote recordQuote = (Quote)stdController.getRecord();
    	lineItems = new List<QuoteItemWrapper>();
        quot = getRecord(recordQuote.Id);
        getQuoteUser(quot.Account.OwnerId);
        lineItems = getLineItems(recordQuote.Id, quot.OpportunityId);
        getRebates(quot.Id, quot.AccountId);
        getDiscounts(quot.AccountId);
        packageAgreements = getPackages(quot.AccountId);
        if (packageAgreements != null && !packageAgreements.isEmpty()) {
            transporationCost = packageAgreements[0].Portes_Devolucion__c;
        } 
        if (quot.Type__c == 'Scales') {
            renderRebatesAccount = '';
            renderDiscountTitle = '';
        } else if (quot.Type__c == 'Product') {
            renderRebates = '';
            renderDiscountTitle = '';
        } else if (quot.Type__c == 'Product and Scales') {
            renderRebatesAccount = '';
            renderRebates = '';
            renderDiscountTitle = '';
            renderThirdPage = '';
            renderOnSecondPage = 'none';
        }
        
        prepareHeader(quot.Account.Market__c);
        getUserInfo();
        accountInfo = quot.Account.Name + '\n ' + (quot.Account.BillingStreet != null ? quot.Account.BillingStreet + '\n ' : '') + 
            (quot.Account.BillingPostalCode != null ? quot.Account.BillingPostalCode + ' ' : '') +
            (quot.Account.BillingCity != null ? quot.Account.BillingCity + '\n ' : '') + (quot.Account.Phone != null ? 'Tel.' + quot.Account.Phone : '');
    }
	     
    private void getUserInfo() {
        User myUser = [SELECT Id, Username, LastName, Street, City FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        if (String.isNotEmpty(myUser.City)) {
        	userInformation = myUser.City + ', ';
        } else {
            userInformation = '';
        }
	}  
    
    private void getQuoteUser(String userId) {
        User myUser = [SELECT Id, Name, Title, Email, MobilePhone, Signature__c FROM User WHERE Id = :userId LIMIT 1];
        if (String.isNotBlank(myUser.Signature__c)) {
            String stringStyle = 'style="' + myUser.Signature__c.substringBetween('style="','"') + '"';
        	signature = myUser.Signature__c.replace(stringStyle, 'style="width:150px;height:150px"');
        }
        userQuoteInfo = ' \n ' + myUser.Name + ' \n ' + (myUser.Title != null ? myUser.Title + ' \n ' : '') + 
            (myUser.MobilePhone != null ? 'Tel.' + myUser.MobilePhone + ' \n ' : '') + myUser.Email;
	}
    
    private Quote getRecord(String recordId) {
        return [
            SELECT Id, Name, TotalPrice, Subtotal, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Description,
            	BillingAddress, Email, Phone, Account.Name, AccountId, Account.Market__c, Account.Agreed_Terms__c, Account.Forma_de_pago__c,
            	Account.Phone, Account.BillingStreet, Account.BillingCity, Account.BillingPostalCode, Rebate__r.Rebate_Commencement_Date__c,
            	Rebate__r.Rebate_Expiry_Date__c, CreatedById, QuoteNumber, OpportunityId, Account.CreatedById, Account.OwnerId, Type__c 
            FROM Quote 
            WHERE Id = :recordId
            LIMIT 1
        ];
    }
    
    private void getDiscounts(String accountId) {
        discounts = new List<Discount__c>();
        discounts = [
            SELECT Id, Account__c, TYPE__c, Product__r.ProductCode, 
            	Percentage__c, EUR__c, Quantity__c, Unit_Type__c 
            FROM Discount__c
            WHERE Account__c = :accountId
        ];
        if (discounts != null && !discounts.isEmpty()) {
            renderDiscount = '';
            renderDiscountTitle = '';
        }
    }
    
    private List<QuoteItemWrapper> getLineItems(String recordId, String opportunityId) {
        Map<String, QuoteItemWrapper> wrapperMap = new Map<String, QuoteItemWrapper>();
        List<QuoteLineItem> quoteItems = [
            SELECT Id, Product2.Colour__c, Product2.ProductCode, Product2.Name, UnitPrice, Product2Id, QuoteId
            FROM QuoteLineItem
            WHERE QuoteId = :recordId
        ];
        List<OpportunityLineItem> oppItems = [
            SELECT Id, OpportunityId, Product2Id, Price_Includes_Delivery__c 
            FROM OpportunityLineItem
            WHERE OpportunityId = :opportunityId
        ];
        for(QuoteLineItem item: quoteItems) {
            QuoteItemWrapper itemWrapper = new QuoteItemWrapper(item.Product2.ProductCode, item.Product2.Name, item.Product2.Colour__c, null, item.UnitPrice);
            wrapperMap.put(item.Product2Id, itemWrapper);
        }
        for(OpportunityLineItem item: oppItems) {
            QuoteItemWrapper itemWrapper = wrapperMap.get(item.Product2Id);
            if (itemWrapper != null) {
            	itemWrapper.incoterm = item.Price_Includes_Delivery__c;
            }  
        }
        return wrapperMap.values();
    }
    
    private void getRebates(String quoteId, String accountId) {
        accountRebates = new List<Rebate__c>();
        childRebates = new List<Rebate__c>();
        rebates = [
            SELECT Id, Name, Account__c, Quote__c, Code__c, Percentage__c, Product__c, Product__r.Name, 
            	Scales__c, Product__r.ProductCode, Rebate_Expiry_Date__c, Rebate_Commencement_Date__c  
            FROM Rebate__c
            WHERE Account__c = :accountId
        ];
        for(Rebate__c item: rebates) {
            if (item.Product__c != null) {
                accountRebates.add(item); 
            }
            else {
                childRebates.add(item);
            }
        }
        if (rebates != null && !rebates.isEmpty()) {
        	if (rebates[0].Rebate_Commencement_Date__c != null) {
            	dateFrom = rebates[0].Rebate_Commencement_Date__c.format();
        	}
        	if (rebates[0].Rebate_Expiry_Date__c != null) {
            	dateTo = rebates[0].Rebate_Expiry_Date__c.format();
        	}
        } 
    }
    
    private List<Packaging_Agreement__c> getPackages(String accountId) {
        return [
            SELECT Id, Name, Debit_Price__c, Credit_Price__c, Material__c, Portes_Devolucion__c 
            FROM Packaging_Agreement__c
            WHERE Account__c = :accountId
        ];
    }
    
    private void prepareHeader(String accountMarket) {
        switch on accountMarket {
            when 'FR' {		
                accountName = 'VIDRALA FRANCE';
                accountAddress = '1, Quai Wilson La Porte De Bègles';
                accountStreet = '33130 Bègles, Gironde (France)';
                accountPhone = 'Tel. 05 56 20 59 89';
                accountEmail = 'commercial@vidrala.com';
                accountWebsite = 'www.vidrala.com';
            }	
            when 'PT'  {
                accountName = 'VIDRALA, S.A.';
                accountAddress = 'Barrio Munegazo, 22';
                accountStreet = '01400 Llodio, Alava (Spain)';
                accountPhone = 'Tel. 244 555 010';
                accountEmail = 'vendas@vidrala.com';
                accountWebsite = 'www.vidrala.com';
            }
            when 'ES' {
                accountName = 'VIDRALA, S.A.';
                accountAddress = 'Barrio Munegazo, 22';
                accountStreet = '01400 Llodio, Alava (Spain)';
                accountPhone = 'Tel. 94 671 97 10';
                accountEmail = 'comercial@vidrala.com';
                accountWebsite = 'www.vidrala.com';
            }
            when 'RM' {
                accountName = 'VIDRALA, S.A.';
                accountAddress = 'Barrio Munegazo, 22';
                accountStreet = '01400 Llodio, Alava (Spain)';
                accountPhone = 'Tel. 94 671 97 15';
                accountEmail = 'export@vidrala.com';
                accountWebsite = 'www.vidrala.com';
            }
            when 'NM' {
                accountName = 'VIDRALA, S.A.';
                accountAddress = 'Barrio Munegazo, 22';
                accountStreet = '01400 Llodio, Alava (Spain)';
                accountPhone = 'Tel. 94 671 97 15';
                accountEmail = 'export@vidrala.com';
                accountWebsite = 'www.vidrala.com';
            }
        }
    }
    
    public class QuoteItemWrapper {
        public String code {get; set;}
        public String name {get; set;}
        public String colour {get; set;}
        public String incoterm {get; set;}
        public Decimal price {get; set;}
 
        public QuoteItemWrapper(String code, String name, String colour, String incoterm, Decimal price) {
            this.code = code;
            this.name = name;
            this.colour = colour;
            this.incoterm = incoterm;
            this.price = price;
        }
    }

}