force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Month__c/Month__c.object-meta.xml
<CustomObject>
    <description>Delivery Budgets and Forecasts by Account and Month</description>
    <label>Month Forecast</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OM_VID_TAM__c/OM_VID_TAM__c.object-meta.xml
<CustomObject>
    <description>Total Addressable Market</description>
    <label>TAM</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>TAM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OM_VID_TAM__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TAM</relationshipLabel>
    <relationshipName>TAM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/OM_AccountText__c.field-meta.xml
<CustomField>
    <fullName>OM_AccountText__c</fullName>
    <label>Account Text</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/OM_ModelRef__c.field-meta.xml
<CustomField>
    <fullName>OM_ModelRef__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>TAM</relationshipLabel>
    <relationshipName>TAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/OM_ProductCodeText__c.field-meta.xml
<CustomField>
    <fullName>OM_ProductCodeText__c</fullName>
    <label>Product Code Text</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/OM_VID_EuroTonnePrevious__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_EuroTonnePrevious__c</fullName>
    <label>Euro/Ton DAP Previous</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/OM_VID_EuroTonneVar__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_EuroTonneVar__c</fullName>
    <label>Euro/Ton DAP Var</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/OM_VID_EuroTonneVarPercent__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_EuroTonneVarPercent__c</fullName>
    <label>Euro/Ton DAP Variation Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/Precio_FF__c.field-meta.xml
<CustomField>
    <fullName>Precio_FF__c</fullName>
    <label>Euro/Ton FF</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/PrecioFFPrev__c.field-meta.xml
<CustomField>
    <fullName>PrecioFFPrev__c</fullName>
    <label>Euro/Ton FF Previous</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/PrecioFFVar__c.field-meta.xml
<CustomField>
    <fullName>PrecioFFVar__c</fullName>
    <label>Euro/Ton FF Variation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/PrecioFFVarPercent__c.field-meta.xml
<CustomField>
    <fullName>PrecioFFVarPercent__c</fullName>
    <label>Euro/Ton FF Variation Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/RevenuePrev__c.field-meta.xml
<CustomField>
    <fullName>RevenuePrev__c</fullName>
    <label>Revenue Previous</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/RevenueVar__c.field-meta.xml
<CustomField>
    <fullName>RevenueVar__c</fullName>
    <label>Revenue Variation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/RevenueVarPercentage__c.field-meta.xml
<CustomField>
    <fullName>RevenueVarPercentage__c</fullName>
    <label>Revenue Variation Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/Tonnes__c.field-meta.xml
<CustomField>
    <fullName>Tonnes__c</fullName>
    <label>Tonnes</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/TonnesPrev__c.field-meta.xml
<CustomField>
    <fullName>TonnesPrev__c</fullName>
    <label>Tonnes Previous</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/TonnesVar__c.field-meta.xml
<CustomField>
    <fullName>TonnesVar__c</fullName>
    <label>Tonnes Variation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/TonnesVarPercent__c.field-meta.xml
<CustomField>
    <fullName>TonnesVarPercent__c</fullName>
    <label>Tonnes Variation Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/Volume000sPrev__c.field-meta.xml
<CustomField>
    <fullName>Volume000sPrev__c</fullName>
    <label>Volume (000&apos;s) Previous</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/Volume000sVar__c.field-meta.xml
<CustomField>
    <fullName>Volume000sVar__c</fullName>
    <label>Volume (000&apos;s) Variation</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/Volume000sVarPercent__c.field-meta.xml
<CustomField>
    <fullName>Volume000sVarPercent__c</fullName>
    <label>Volume Variation Percentage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OM_VID_TAM__c/fields/Volume_000_s__c.field-meta.xml
<CustomField>
    <fullName>Volume_000_s__c</fullName>
    <description>Number of bottles in thousands</description>
    <label>Volume (000&apos;s)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cuenta__c in spanish org</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OM_Product_Code_SIP__c.field-meta.xml
<CustomField>
    <fullName>OM_Product_Code_SIP__c</fullName>
    <externalId>true</externalId>
    <label>Product Code SIP</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OM_BW_InsertTAMReport.cls
public class OM_BW_InsertTAMReport {

    // WRAPPER PARA LA RESPUESTA DEL WS DE SF
    public class SFWS_Response {
        public Boolean status;
        public String msg;
        public List<String> salesforceErrors;
        public String successMessage;
    }

    @future(callout=true)
    public static void insertTAM(String jsonFilter){ 
        OM_BW_Wrapper.BWFilter filterWrapper = (OM_BW_Wrapper.BWFilter) JSON.deserialize(jsonFilter, OM_BW_Wrapper.BWFilter.class);
        tamCalloutBW(filterWrapper);
    }

    public static void tamCalloutBW(OM_BW_Wrapper.BWFilter filterWrapper){
        String infoProvider = 'ZMSDF_11';
        String query = 'ZMSDF_11_PYGTAM_SF';
        Integer VAR_NAME = 1; 

        OM_SapFunctionsStyle.CDSS cdss = new OM_SapFunctionsStyle.CDSS();
        List<OM_SapFunctionsStyle.W3query> itemList = new List<OM_SapFunctionsStyle.W3query>();

        OM_SapFunctionsStyle.W3query item1 = new OM_SapFunctionsStyle.W3query();
        item1.Name = 'VAR_NAME_' + VAR_NAME;
        item1.Value = '0CALTAM';
        itemList.add(item1);

        OM_SapFunctionsStyle.W3query item2 = new OM_SapFunctionsStyle.W3query();
        item2.Name = 'VAR_VALUE_EXT_' + VAR_NAME;
        item2.Value = filterWrapper.monthFrom + '.' + filterWrapper.yearFrom;
        itemList.add(item2);
        VAR_NAME++;

        if (filterWrapper.salesGroup != null) {
            OM_SapFunctionsStyle.W3query item3 = new OM_SapFunctionsStyle.W3query();
            item3.Name = 'VAR_NAME_' + VAR_NAME;
            item3.Value = 'VAR_20241220095416';
            itemList.add(item3);

            OM_SapFunctionsStyle.W3query item4 = new OM_SapFunctionsStyle.W3query();
            item4.Name = 'VAR_VALUE_EXT_' + VAR_NAME;
            item4.Value = filterWrapper.salesGroup;
            itemList.add(item4);
            VAR_NAME++;
        }

        OM_SapFunctionsStyle.Rrxw3tquery parameter = new OM_SapFunctionsStyle.Rrxw3tquery();
        parameter.item = itemList;
        String requestString = parameter.toString();

        try {
            OM_SapFunctionsStyle.GetQueryViewDataResponse_element response = cdss.GetQueryViewData(infoProvider, parameter, query, null);
            if(response != null && response.axisData != null){
                processActualTAMCalloutResponse(response, requestString, filterWrapper);
            }
        } catch(Exception e) {
            createResponse(false, 'Error en callout TAM', null, '400', new List<String>{e.getMessage()}, null, null, requestString);
        }
    }

    public static void processActualTAMCalloutResponse(OM_SapFunctionsStyle.GetQueryViewDataResponse_element response, String requestString, OM_BW_Wrapper.BWFilter filterWrapper){
        List<OM_VID_TAM__c> temporaryList = new List<OM_VID_TAM__c>();
        List<String> salesforceErrors = new List<String>();
        Integer cellOrdinalCounter = 0; 

        // Preparamos el valor del mes una sola vez fuera del bucle para ahorrar CPU
        String salesforceMonth = getPicklistMonth(filterWrapper.monthFrom);

        for(OM_SapFunctionsStyle.RrwsSxAxisData axis : response.AxisData.item){
            if(axis.axis == '001'){ 
                Integer tupleCounter = 0;
                OM_VID_TAM__c tamRec = new OM_VID_TAM__c();

                for(OM_SapFunctionsStyle.RrwsSxTuple item : axis.Set_x.item){
                    if(tupleCounter == Integer.valueOf(item.TupleOrdinal)){
                        
                        // INYECCIÓN DE FECHA (Picklist compatible)
                        if(tamRec.Year__c == null) {
                            tamRec.Year__c = filterWrapper.yearFrom;
                            tamRec.Month__c = salesforceMonth;
                        }

                        if (item.Chanm == '0SOLD_TO') {
                            tamRec.OM_AccountText__c = item.Chavl.replaceFirst('^0+', '').toUpperCase();
                        } 
                        else if (item.Chanm == '0MATERIAL__ZISDMODEL') {
                            if(String.isNotBlank(item.ChavlExt) && item.ChavlExt != '#') {
                                tamRec.OM_ProductCodeText__c = item.ChavlExt.toUpperCase();
                            }

                            if(String.isNotBlank(tamRec.OM_AccountText__c)){
                                fillNumericData(tamRec, response.cellData.item, cellOrdinalCounter);
                                temporaryList.add(tamRec);
                                cellOrdinalCounter += 20; 
                            }
                            
                            tamRec = new OM_VID_TAM__c();
                            tupleCounter++;
                        }
                    }        
                }
            }
        }

        if(temporaryList.isEmpty()) return;

        validateAndLinkMasterData(temporaryList, salesforceErrors);

        if(!salesforceErrors.isEmpty()){
            createResponse(false, 'Master data validation error', null, '400', salesforceErrors, null, null, requestString);
            return;
        }

        Database.insert(temporaryList, true);
        createResponse(true, null, null, '200', new List<String>(), 'Insert TAM completado correctamente.', null, requestString);
    }

    private static String getPicklistMonth(String monthNum) {
        if(String.isBlank(monthNum)) return null;
        Integer m = Integer.valueOf(monthNum);
        Map<Integer, String> monthMap = new Map<Integer, String>{
            01 => 'Jan', 02 => 'Feb', 03 => 'Mar', 04 => 'Apr', 05 => 'May', 06 => 'Jun',
            07 => 'Jul', 08 => 'Aug', 09 => 'Sep', 10 => 'Oct', 11 => 'Nov', 12 => 'Dec'
        };
        return monthMap.get(m);
    }

    private static void validateAndLinkMasterData(List<OM_VID_TAM__c> records, List<String> errors) {
        Set<String> accCodes = new Set<String>();
        Set<String> modCodes = new Set<String>();

        for(OM_VID_TAM__c r : records) {
            if(r.OM_AccountText__c != null) accCodes.add(r.OM_AccountText__c);
            if(r.OM_ProductCodeText__c != null) modCodes.add(r.OM_ProductCodeText__c);
        }

        Map<String, Id> accMap = new Map<String, Id>();
        for(Account a : [SELECT Id, SAP_Account_Number__c FROM Account WHERE SAP_Account_Number__c IN :accCodes]) 
            accMap.put(a.SAP_Account_Number__c.toUpperCase(), a.Id);

        Map<String, Id> modMap = new Map<String, Id>();
        for(Product2 p : [SELECT Id, OM_Product_Code_SIP__c FROM Product2 WHERE OM_Product_Code_SIP__c IN :modCodes]) 
            modMap.put(p.OM_Product_Code_SIP__c.toUpperCase(), p.Id);

        List<String> missA = new List<String>();
        for(String s : accCodes) if(!accMap.containsKey(s)) missA.add(s);
        if(!missA.isEmpty()) errors.add('ACCOUNTS NOT FOUND: ' + String.join(missA, ', '));
        
        List<String> missM = new List<String>();
        for(String s : modCodes) if(!modMap.containsKey(s)) missM.add(s);
        if(!missM.isEmpty()) errors.add('MODELS NOT FOUND: ' + String.join(missM, ', '));

        if(errors.isEmpty()) {
            for(OM_VID_TAM__c r : records) {
                r.Account__c = accMap.get(r.OM_AccountText__c);
                r.OM_ModelRef__c = modMap.get(r.OM_ProductCodeText__c);
            }
        }
    }

    private static void fillNumericData(OM_VID_TAM__c record, List<OM_SapFunctionsStyle.RrwsSCell> cells, Integer index){     
        record.Revenue__c = parseDecimal(cells.get(index).Value);
        record.RevenuePrev__c = parseDecimal(cells.get(index + 1).Value);
        record.RevenueVar__c = parseDecimal(cells.get(index + 2).Value);
        record.RevenueVarPercentage__c = parseDecimal(cells.get(index + 3).Value);
        
        record.Tonnes__c = parseDecimal(cells.get(index + 4).Value);
        record.TonnesPrev__c = parseDecimal(cells.get(index + 5).Value);
        record.TonnesVar__c = parseDecimal(cells.get(index + 6).Value);
        record.TonnesVarPercent__c = parseDecimal(cells.get(index + 7).Value);
        
        record.Volume_000_s__c = parseDecimal(cells.get(index + 8).Value);
        record.Volume000sPrev__c = parseDecimal(cells.get(index + 9).Value);
        record.Volume000sVar__c = parseDecimal(cells.get(index + 10).Value);
        record.Volume000sVarPercent__c = parseDecimal(cells.get(index + 11).Value);
        
        record.Precio__c = parseDecimal(cells.get(index + 12).Value);
        record.OM_VID_EuroTonnePrevious__c = parseDecimal(cells.get(index + 13).Value);
        record.OM_VID_EuroTonneVar__c = parseDecimal(cells.get(index + 14).Value);
        record.OM_VID_EuroTonneVarPercent__c = parseDecimal(cells.get(index + 15).Value);
        
        record.Precio_FF__c = parseDecimal(cells.get(index + 16).Value);
        record.PrecioFFPrev__c = parseDecimal(cells.get(index + 17).Value);
        record.PrecioFFVar__c = parseDecimal(cells.get(index + 18).Value);
        record.PrecioFFVarPercent__c = parseDecimal(cells.get(index + 19).Value);
    }

    private static Decimal parseDecimal(String value) {
        return String.isBlank(value) ? 0 : Decimal.valueOf(value.trim().replace(',', '.')).setScale(2, RoundingMode.HALF_UP);
    }

    public static void createResponse(Boolean status, String msg, String accountId, String code, List<String> errors, String successMessage, String sapCode, String requestParam) {
        SFWS_Response respWrapper = new SFWS_Response();
        respWrapper.status = status;
        respWrapper.msg = msg;
        respWrapper.salesforceErrors = errors;
        respWrapper.successMessage = successMessage;
        OM_Utils.IntegrationMsg.createRESTIntegrationMsg(OM_Utils.IntegrationMsg.INBOUND, '/actualTAMCalloutBW', 'INSERT');
        OM_Utils.IntegrationMsg.addBody(requestParam, JSON.serialize(respWrapper));
        OM_Utils.IntegrationMsg.addStatusAndRecord((status ? OM_Utils.IntegrationMsg.SUCCESS : OM_Utils.IntegrationMsg.ERROR), accountId, null, null);
        OM_Utils.IntegrationMsg.insertRecord();
    }
    
    public static String createJsonBWWrapper(String yearFrom, String monthFrom, String salesGroup) {
        OM_BW_Wrapper.BWFilter filterWrapper = new OM_BW_Wrapper.BWFilter(yearFrom, monthFrom, salesGroup);
        return JSON.serialize(filterWrapper);
    }
}