force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/Actual_Sales_History__c.object-meta.xml
<CustomObject>
    <description>Historic report to store, display and report on historic deal summaries with customers</description>
    <label>Actual Sales History</label>
    <nameField>
        <displayFormat>Deal Summary No. {0000}</displayFormat>
        <label>Deal Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Sales History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Actual_Sales_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Deal_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bottle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bottle__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>Actual Sales History</relationshipLabel>
    <relationshipName>Actual_Sales_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>Jun</fullName>
            </value>
            <value>
                <fullName>Jul</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sep</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Tonnes__c.field-meta.xml
<CustomField>
    <fullName>Tonnes__c</fullName>
    <label>Tonnes</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Volume_000_s__c.field-meta.xml
<CustomField>
    <fullName>Volume_000_s__c</fullName>
    <description>Number of bottles in thousands</description>
    <inlineHelpText>Number of bottles in thousands</inlineHelpText>
    <label>Volume (000&apos;s)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bottle__c/Bottle__c.object-meta.xml
<CustomObject>
    <description>Unique Product Identifiers and Descriptions</description>
    <label>Bottle</label>
    <nameField>
        <label>Bottle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <description>Delivery Forecasts by Account, Month and Product (Bottle)</description>
    <label>Forecast</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Forecast</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>Forecast at Month level within Account</description>
    <label>Month</label>
    <referenceTo>Month__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Prior_Month_Actual_Total__c.field-meta.xml
<CustomField>
    <fullName>Prior_Month_Actual_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Prior month actual units total, updated by a trigger</description>
    <label>Prior Month Actual Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Prior_Year__c.field-meta.xml
<CustomField>
    <fullName>Prior_Year__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This month actual units, prior year</description>
    <label>Prior Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>Month__r.Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Month__c/Month__c.object-meta.xml
<CustomObject>
    <description>Delivery Budgets and Forecasts by Account and Month</description>
    <label>Month Forecast</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast</label>
    <summarizedField>Forecast__c.Forecast__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Prior_Month_Actual_Total__c.field-meta.xml
<CustomField>
    <fullName>Prior_Month_Actual_Total__c</fullName>
    <label>Prior Month Actual Total</label>
    <summarizedField>Forecast__c.Prior_Month_Actual_Total__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Prior_Year__c.field-meta.xml
<CustomField>
    <fullName>Prior_Year__c</fullName>
    <label>Prior Year</label>
    <summarizedField>Forecast__c.Prior_Year__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EN60</fullName>
            </value>
            <value>
                <fullName>VD30</fullName>
            </value>
            <value>
                <fullName>VD10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ForecastSalesHistoryUpdatesTest.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        ForecastSalesHistoryUpdatesTest.cls
   Description: Test updating of Forecast records from Sales History
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Dec 2017     1.0     M.Witchalls(Ciber)  Initial Release 
   Sept 2024    2.0     Globant             Code Refactoring

------------------------------------------------------------------------------------------------------------------------ */              

@isTest
private class ForecastSalesHistoryUpdatesTest {
    private static String approvedRecordType = 'Approved_Rejected';
    
    @testSetup
    static void setupData() {
        List<Account> aList = TestDataFactory.createAccountsWithMonths(1, 10001);
        String acctNum = aList[0].SAP_Account_Number__c;
        ID accountId = aList[0].Id;
        
        List<Forecast__c> fList = TestDataFactory.createForecasts(8, acctNum, 800, 1000);
        delete new List<Forecast__c>{fList[0], fList[94], fList[95]};
        
        List<Actual_Sales_History__c> sList = TestDataFactory.createSalesHistory(8, accountId, 1000);
    }
    
    @isTest
    static void testSalesUpdatesPriorYear() {
        Test.startTest();
        
        List<Forecast__c> fList = [SELECT Id, Prior_Year__c FROM Forecast__c LIMIT 1];
        List<Actual_Sales_History__c> sList = [SELECT Volume_000_s__c FROM Actual_Sales_History__c LIMIT 2];
        
        Double lastYearSales = sList[0].Volume_000_s__c;
        Forecast__c forecast = fList[0];
        
        System.assertEquals(lastYearSales, forecast.Prior_Year__c);
        
        Test.stopTest();
    }


    @isTest
    static void testForecastDeletionAndCreation() {
        Test.startTest();
        
        List<Forecast__c> fList = [SELECT Id FROM Forecast__c];
        delete fList;
        
        fList = [SELECT Id FROM Forecast__c];
        System.assertEquals(0, fList.size());
        
        Actual_Sales_History__c asRecord = [SELECT Account__c, Bottle__c, Month__c, Item__c, Volume_000_s__c, Tonnes__c, Revenue__c, Year__c, Sales_Organization__c 
                                            FROM Actual_Sales_History__c 
                                            LIMIT 1];
        Actual_Sales_History__c asCopy = new Actual_Sales_History__c(
            Account__c = asRecord.Account__c, 
            Month__c = asRecord.Month__c,
            Item__c = asRecord.Item__c,
            Volume_000_s__c = asRecord.Volume_000_s__c,
            Tonnes__c = asRecord.Tonnes__c,
            Revenue__c = asRecord.Revenue__c,
            Year__c = asRecord.Year__c,
            Sales_Organization__c = asRecord.Sales_Organization__c
        );
        insert asCopy;
        
        fList = [SELECT Id FROM Forecast__c];
        System.assertEquals(1, fList.size());
        
        Test.stopTest();
    }
}


/*
@isTest
private class TestForecastSalesHistoryUpdates {
    private static String approvedRecordType = 'Approved_Rejected';
    
    private static testMethod void testSalesUpdates() {  
        // create one Account
        List<Account> aList = TestDataFactory.createAccountsWithMonths(1, 10001);
        String acctNum = aList[0].SAP_Account_Number__c;
        ID accountId = aList[0].Id;
        
        // create 96 forecast records (8 x 12 months)
        List<Forecast__c> fList = TestDataFactory.createForecasts(8, acctNum, 800, 1000);
        // delete some forecasts
        delete new List<Forecast__c>{fList[0],fList[94],fList[95]};
        
        // create corresponding Sales History records (this year and last year)
        List<Actual_Sales_History__c> sList = TestDataFactory.createSalesHistory(8, accountId, 1000);
        
        Forecast__c f = [select Prior_Year__c, Prior_Month_Actual_Total__c from Forecast__c where Id = :fList[2].Id];
        Double lastYearSales = sList[2].Volume_000_s__c;
        Double thisYearSales = sList[96].Volume_000_s__c + sList[97].Volume_000_s__c;
        
        System.debug('lastYearSales, thisYearSales: '+lastYearSales+','+thisYearSales);
        System.debug('Forecast__c: '+f);
        
        System.assertEquals(lastYearSales, f.Prior_Year__c);
        System.assertEquals(thisYearSales, f.Prior_Month_Actual_Total__c);
        Actual_Sales_History__c asRecord = [SELECT Account__c, Bottle__c, Month__c, Item__c, Volume_000_s__c, Tonnes__c, Revenue__c, Year__c, Sales_Organization__c 
                                            FROM Actual_Sales_History__c 
                                            LIMIT 1];
        fList = [SELECT Id FROM Forecast__c];
        delete fList;
        Actual_Sales_History__c asCopy = new Actual_Sales_History__c(Account__c = asRecord.Account__c, 
                                                                    Month__c = asRecord.Month__c,
                                                                    Item__c = asRecord.Item__c,
                                                                    Volume_000_s__c = asRecord.Volume_000_s__c,
                                                                    Tonnes__c = asRecord.Tonnes__c,
                                                                    Revenue__c = asRecord.Revenue__c,
                                                                    Year__c = asRecord.Year__c,
                                                                    Sales_Organization__c = asRecord.Sales_Organization__c);
        insert asCopy;
        fList = [SELECT Id FROM Forecast__c];
        System.assertEquals(1, fList.size(), 'Forecast record should be created');
    }
}*/