force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <displayFormat>Dcto - {0000}</displayFormat>
        <label>Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/EUR__c.field-meta.xml
<CustomField>
    <fullName>EUR__c</fullName>
    <label>EUR</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/TYPE__c.field-meta.xml
<CustomField>
    <fullName>TYPE__c</fullName>
    <label>TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZDES - Descuento especial</fullName>
            </value>
            <value>
                <fullName>ZDUN - Descuento unitario</fullName>
            </value>
            <value>
                <fullName>ZDVR - Descuento sobre vidrio</fullName>
            </value>
            <value>
                <fullName>ZSKT - Descuento por pronto pago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/Packaging_Agreement__c.object-meta.xml
<CustomObject>
    <description>Vidrala Fifty Spain Object From Org Migration 2021
&quot;Objetivo que agrupa los convenios de embalaje de los materiales de los clientes&quot;</description>
    <label>Packaging Agreement</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Packaging Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packaging Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Packaging_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Packaging Agreements</relationshipLabel>
    <relationshipName>Packaging_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abono buenos y a reparar</fullName>
            </value>
            <value>
                <fullName>Abono buenos y a reparar Italia</fullName>
            </value>
            <value>
                <fullName>Abono todos</fullName>
            </value>
            <value>
                <fullName>Depósito</fullName>
            </value>
            <value>
                <fullName>Gratuito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Agreement_Code__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Code__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Credit_Price__c.field-meta.xml
<CustomField>
    <fullName>Credit_Price__c</fullName>
    <label>Credit Price</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Debit_Price__c.field-meta.xml
<CustomField>
    <fullName>Debit_Price__c</fullName>
    <label>Debit Price</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <description>From Vidrala Spain Picklist</description>
    <label>Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8001378 PALETA ANIFE RETORNABLE 1200X1000X155</fullName>
                <default>true</default>
                <label>PALETA ANIFE RETORNABLE 1200X1000X155</label>
            </value>
            <value>
                <fullName>8001392 PALETA VMF RETORNABLE 1200X1000X154</fullName>
                <label>PALETA VMF RETORNABLE 1200X1000X154</label>
            </value>
            <value>
                <fullName>8000355 PLANCHA PP CARTONPLAST PCA 1200X1000 ALV</fullName>
                <label>PLANCHA PP CARTONPLAST PCA 1200X1000 ALV</label>
            </value>
            <value>
                <fullName>8000385 PLANCHA PP VIDRALA PVE EXPORT 1200X1000</fullName>
                <label>PLANCHA PP VIDRALA PVE EXPORT 1200X1000</label>
            </value>
            <value>
                <fullName>8000042 PALETA RG01 RETORNAB. ALIG 1200X1000X125</fullName>
                <label>PALETA RG01 RETORNAB. ALIG 1200X1000X125</label>
            </value>
            <value>
                <fullName>8003618 PLACA PP SMARTPAD 1200X1000 2,6 -3mm PSM</fullName>
                <label>PLACA PP SMARTPAD 1200X1000 2,6 -3mm PSM</label>
            </value>
            <value>
                <fullName>8003625 Top Frame - 25 mm</fullName>
                <label>TOP FRAME - 25 mm</label>
            </value>
            <value>
                <fullName>8003835 PALETES HK RETORNABLE 1200X1000X162</fullName>
                <label>PALETES HK RETORNABLE 1200X1000X162</label>
            </value>
            <value>
                <fullName>8002589 PALETA TF RETORNABLE 1200X1000X145</fullName>
                <label>PALETA TF RETORNABLE  1200X1000X145</label>
            </value>
            <value>
                <fullName>8002626 PALETA DIN (T5) RETORNABLE 1200X1000X134</fullName>
                <label>PALETA DIN (T5) RETORNABLE 1200X1000X134</label>
            </value>
            <value>
                <fullName>8002627 PALETA EURO RETORNABLE 1200X 800X144</fullName>
                <label>PALETA EURO RETORNABLE     1200X 800X144</label>
            </value>
            <value>
                <fullName>8002628 PALETA UK 1200X1000X150</fullName>
                <label>PALETA UK 1200X1000X150</label>
            </value>
            <value>
                <fullName>8000350 PLACA 1200X1000 PP VIDRALA AKY 3.5mm PVE</fullName>
                <label>PLACA 1200X1000 PP VIDRALA AKY 3.5mm PVE</label>
            </value>
            <value>
                <fullName>8000360 PLACA 1200X1000 PP CPL 3mm SANDWICH PCS</fullName>
                <label>PLACA 1200X1000 PP CPL 3mm SANDWICH PCS</label>
            </value>
            <value>
                <fullName>8000397 PLACA 1200X1000 PP CPL 3mm SDW TROQ PCST</fullName>
                <label>PLACA 1200X1000 PP CPL 3mm SDW TROQ PCST</label>
            </value>
            <value>
                <fullName>8003021 PALETA EQ ENCIRC RET 1200X1000X157</fullName>
                <label>PALETA EQ ENCIRC RET 1200X1000X157</label>
            </value>
            <value>
                <fullName>8002598 INTERFAL.PVI ALVEOL 1200X1000X3.4 VERDE</fullName>
                <label>INTERFAL.PVI ALVEOL 1200X1000X3.4 VERDE</label>
            </value>
            <value>
                <fullName>8003836 TAPA PP MACIZA SMARTCAP 1200X1000 TSM</fullName>
                <label>TAPA PP MACIZA SMARTCAP 1200X1000 TSM</label>
            </value>
            <value>
                <fullName>8002517 PALETA DE MADERA CHEP RECUPERABLE</fullName>
                <label>PALETA DE MADERA CHEP RECUPERABLE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Account_Id_Copy__c.field-meta.xml
<CustomField>
    <fullName>Account_Id_Copy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to look up and filter the account</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Packaging_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Packaging Agreement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account_Id_Copy__c</field>
            <operation>equals</operation>
            <valueField>Packaging_Agreement__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Packaging_Agreement__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scales</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Product and Scales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomRelatedListControllerTest.cls
@isTest
private class CustomRelatedListControllerTest {

    @TestSetup
    private static void setupTestData() {
        
        Account testAcc = TestDataFactory.createActiveCustomerAccount();
        Quote testQuote = TestDataFactory.createQuote();

        Discount__c discount1 = new Discount__c(
            Account__c = testQuote.Account_Id_Copy__c,
            Status__c = 'Approved',
            CurrencyIsoCode = 'EUR',
            TYPE__c = 'ZDUN - Descuento unitario',
            Quantity__c = 100,
            Percentage__c = 10,
            EUR__c = 500
        );
        insert discount1;

        Packaging_Agreement__c agreement1 = new Packaging_Agreement__c(
            Account__c = testQuote.Account_Id_Copy__c,
            Agreement__c = 'Depósito',
            Material__c = '8003625 Top Frame - 25 mm',
            Agreement_Code__c = 'AG001',
            Credit_Price__c = 50,
            Debit_Price__c = 70
        );
        insert agreement1;
    }

    @IsTest 
    private static void testGetDiscounts() {
        Test.startTest();
        Quote testQuote = [SELECT Id, AccountId FROM Quote LIMIT 1];
        
        List<Discount__c> discounts = CustomRelatedListController.getDiscounts(testQuote.Id);
        
        // Assert the results
        System.assertNotEquals(null, discounts, 'Discount list should not be null.');
        System.assertEquals(1, discounts.size(), 'There should be one discount associated.');

        // Assert fields of the discount
        Discount__c discount = discounts[0];
        System.assertEquals('Approved', discount.Status__c, 'Discount status should be Approved.');
        System.assertEquals('EUR', discount.CurrencyIsoCode, 'Currency should be EUR.');
        System.assertEquals(10, discount.Percentage__c, 'Discount percentage should be 10.');
        
        Test.stopTest();
    }

    @IsTest 
    private static void testGetAgreements() {
        Test.startTest();
        Quote testQuote = [SELECT Id, AccountId FROM Quote LIMIT 1]; 
        
        List<Packaging_Agreement__c> agreements = CustomRelatedListController.getAgreements(testQuote.Id);
        
        // Assert the results
        System.assertNotEquals(null, agreements, 'Agreement list should not be null.');
        System.assertEquals(1, agreements.size(), 'There should be one agreement associated.');

        // Assert fields of the agreement
        Packaging_Agreement__c agreement = agreements[0];
        System.assertEquals('Depósito', agreement.Agreement__c, 'Agreement name should match.');
        System.assertEquals('8003625 Top Frame - 25 mm', agreement.Material__c, 'Material should be Plastic.');
        System.assertEquals(50, agreement.Credit_Price__c, 'Credit price should be 50.');
        
        Test.stopTest();
    }
}

/*
@isTest
private class CustomRelatedListControllerTest {
    
    @IsTest private static void testGetDiscounts() {
        Quote testQuote = TestDataFactory.createQuote();
        List<Discount__c> discounts = CustomRelatedListController.getDiscounts(testQuote.Id);
        System.assertEquals(0, discounts.size());
    }

    @IsTest private static void testGetAgreements() {
        Quote testQuote = TestDataFactory.createQuote();
        List<Packaging_Agreement__c>  agreements = CustomRelatedListController.getAgreements(testQuote.Id);
        System.assertEquals(0, agreements.size());
    }
}*/