force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cuenta__c in spanish org</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Rebate__c.field-meta.xml
<CustomField>
    <fullName>Rebate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Existing rebate on the Account</description>
    <label>Existing Rebate</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rebate__c.Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account_Id_Copy__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rebate__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/Rebate__c.object-meta.xml
<CustomObject>
    <description>Stores and manages information relating to Rebates which have been given to Accounts.</description>
    <label>Rebate</label>
    <nameField>
        <displayFormat>Rebate-{00000}</displayFormat>
        <label>Rebate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rebate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>Condicion__c</description>
    <label>Percentage</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product lookup on Rebate</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <description>Provision field on Rebate</description>
    <label>Provision</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Reason_for_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Rebate__c</fullName>
    <description>Please enter a description of the Rebate including the reason why it is being requested.</description>
    <inlineHelpText>Please enter a description of the Rebate including the reason why it is being requested.</inlineHelpText>
    <label>Reason for Rebate</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Scales__c.field-meta.xml
<CustomField>
    <fullName>Scales__c</fullName>
    <description>Escala</description>
    <label>Scales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RebateSearchOnAccount.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        RebateSearchOnAccount.cls
   Description: Class to search for Rebate records based on the associated Account of a given Quote record.
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Sept 2024    1.0     Globant             Initial Release 
------------------------------------------------------------------------------------------------------------------------ */        

/**
 * The RebateSearchOnAccount class provides a method to search for rebates related to a specific quote.
 * It retrieves the AccountId from the provided Quote and then queries the related Rebate records.
 */
public class RebateSearchOnAccount {
    /**
     * Searches for Rebate__c records associated with the account related to the provided Quote record.
     * 
     * @param quoteRecordId The Id of the Quote record. It cannot be null.
     * @return List<Rebate__c> A list of Rebate__c records related to the account in the Quote.
     * @throws CustomException If the quoteRecordId is null, or if no records are found in the queries.
     */
    @AuraEnabled
    public static List<Rebate__c> searchRebate(Id quoteRecordId) {
        if (quoteRecordId == null) {
            throw new CustomException('Quote record ID cannot be null.');
        }
        
        List<Rebate__c> rebates = new List<Rebate__c>();
        try {
            Quote qc = [SELECT Id, AccountId FROM Quote WHERE Id = :quoteRecordId];
            rebates = [SELECT Id, Name, Product__r.Name, Scales__c, Percentage__c, Provision__c,Reason_for_Rebate__c
                       FROM Rebate__c 
                       WHERE Account__c = :qc.AccountId];

        } catch (Exception e) {
            throw new CustomException('No records found in Quote/Rebate query');
        }

        return rebates;
    }
    
    public class CustomException extends Exception {}

}


/*public class RebateSearchOnAccount {
	@AuraEnabled
    public static List<Rebate__c> searchRebate(Id quoteRecordId){
    	List< Rebate__c> rebates = new List<Rebate__c>();
        Quote qc = [SELECT Id,AccountId FROM Quote WHERE Id =: quoteRecordId];        
        rebates = [SELECT Id,Name,Product__r.Name,Scales__c,Percentage__c,Provision__c FROM Rebate__c WHERE Account__c =: qc.AccountId];
        return rebates;
        
    }
}*/