force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Commercial_Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Contract_Status__c</fullName>
    <inlineHelpText>Roll up from the commercial contract status</inlineHelpText>
    <label>Commercial Contract Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Expire_Date__c</fullName>
    <label>Contract Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customers.recordType-meta.xml
<RecordType>
    <fullName>Customers</fullName>
    <active>true</active>
    <description>Past or Present</description>
    <label>Customers</label>
</RecordType>

force-app/main/default/objects/Commercial_Contract_Status__c/Commercial_Contract_Status__c.object-meta.xml
<CustomObject>
    <description>The current status of the accounts commercial contract</description>
    <label>Commercial Contract Status</label>
    <nameField>
        <label>Commercial Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Contract Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commercial_Contract_Status__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commercial Contract Status</relationshipLabel>
    <relationshipName>Commercial_Contract_Status</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract_Status__c/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commercial_Contract_Status__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date the contract ends</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commercial_Contract_Status__c/fields/Start_date__c.field-meta.xml
<CustomField>
    <fullName>Start_date__c</fullName>
    <inlineHelpText>Date contract starts</inlineHelpText>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AccountContractStatusUpdateTest.cls
@IsTest
public with sharing class AccountContractStatusUpdateTest {

    @TestSetup
    static void initData(){
        TestDataFactory.createTestAccountsWithContracts();
    }
    
    @isTest
    static void testAccountContractStatus(){
        Test.startTest();
        Database.executeBatch(new AccountContractStatusUpdateBatch(), 200);
        Test.stopTest();
        
        List<Account> accounts = [SELECT Contract_Expire_Date__c, Commercial_Contract_Status__c FROM Account WHERE Name IN ('Test account', 'Test account 2')];
        Account acc1 = accounts[0];
        Account acc2 = accounts[1];

        System.assertEquals('Red', acc2.Commercial_Contract_Status__c, 'Test account 2 status should be equal to Red');
        System.assertEquals(null, acc2.Contract_Expire_Date__c, 'Test account 2 contract expire date should be updated to null');
        System.assertEquals('Amber', acc1.Commercial_Contract_Status__c, 'Test account 1 status should be equal to Amber');
        System.assertNotEquals(null, acc1.Contract_Expire_Date__c, 'Test account 1 contract expire date should be updated');
    }

    @isTest
    static void testAccountContractStatusScheduled(){
        Test.startTest();
        AccountContractStatusUpdateScheduler.startScheduler();
        Test.stopTest();

        List<CronTrigger> cronJobs = [SELECT Id FROM CronTrigger];
        System.assertNotEquals(0, cronJobs.size(), 'The job should be scheduled');
    }
}
    


/*@IsTest
public with sharing class AccountContractStatusUpdateTest {
    @TestSetup
    static void initData(){
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customers').getRecordTypeId();
        Account acc = new Account(RecordTypeId = accRecordTypeId,
                                    Name = 'Text account',
                                    CurrencyIsoCode = 'GBP');
        insert acc;
        Account acc2 = new Account(RecordTypeId = accRecordTypeId,
                                    Name = 'Text account 2',
                                    CurrencyIsoCode = 'GBP',
                                    Contract_Expire_Date__c = Date.today().addDays(-2),
                                    Commercial_Contract_Status__c = 'Green');
        insert acc2;
        Commercial_Contract_Status__c cc1 = new Commercial_Contract_Status__c(Name = 'test 1', 
                                                                                Account__c = acc.Id, 
                                                                                Contract_Status__c = 'Amber',
                                                                                Start_date__c = Date.today().addDays(-2),
                                                                                End_Date__c = Date.today().addDays(2));
        insert cc1;
        Commercial_Contract_Status__c cc2 = new Commercial_Contract_Status__c(Name = 'test 2', 
                                                                                Account__c = acc.Id, 
                                                                                Contract_Status__c = 'Amber',
                                                                                Start_date__c = Date.today().addDays(-4),
                                                                                End_Date__c = Date.today().addDays(-3));
        insert cc2;
    }

    @isTest
    static void testAccountContractStatus(){
        Test.startTest();
        //AccountContractStatusUpdateScheduler.startScheduler();
        Database.executeBatch(new AccountContractStatusUpdateBatch(), 200);
        Test.stopTest();
        Account acc1 = [SELECT Contract_Expire_Date__c, Commercial_Contract_Status__c FROM Account WHERE Name = 'Text account'];
        Account acc2 = [SELECT Contract_Expire_Date__c, Commercial_Contract_Status__c FROM Account WHERE Name = 'Text account 2'];
        System.assertEquals('Red', acc2.Commercial_Contract_Status__c, 'Text account 2 status should be equal to Red');
        System.assertEquals(null, acc2.Contract_Expire_Date__c, 'Test account 2 contract expire date should be updated to null');
        System.assertEquals('Amber', acc1.Commercial_Contract_Status__c, 'Text account status should be equal to Amber');
        System.assertNotEquals(null, acc1.Contract_Expire_Date__c, 'Test account contract expire date should be updated');
    }
    
    @isTest
    static void testAccountContractStatusScheduled(){
        Test.startTest();
        AccountContractStatusUpdateScheduler.startScheduler();
        List<CronTrigger> crn = [SELECT Id FROM CronTrigger];
        Test.stopTest();
        System.assertNotEquals(0, crn.size(), 'Job schold be scheduled');
    }
}*/