force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Rebate__c.field-meta.xml
<CustomField>
    <fullName>Rebate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Existing rebate on the Account</description>
    <label>Existing Rebate</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rebate__c.Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account_Id_Copy__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rebate__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/Rebate__c.object-meta.xml
<CustomObject>
    <description>Stores and manages information relating to Rebates which have been given to Accounts.</description>
    <label>Rebate</label>
    <nameField>
        <displayFormat>Rebate-{00000}</displayFormat>
        <label>Rebate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rebate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rebates</relationshipLabel>
    <relationshipName>Rebates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Reason_for_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Rebate__c</fullName>
    <description>Please enter a description of the Rebate including the reason why it is being requested.</description>
    <inlineHelpText>Please enter a description of the Rebate including the reason why it is being requested.</inlineHelpText>
    <label>Reason for Rebate</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Rebate_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Commencement_Date__c</fullName>
    <label>Rebate Commencement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rebate__c/fields/Rebate_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Expiry_Date__c</fullName>
    <label>Rebate Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/rebateSearchOnAccount_Test.cls
@isTest
public class rebateSearchOnAccount_Test {
	@isTest
    public static void testMethod1(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.CurrencyIsoCode = 'GBP';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.AccountId = acc.Id;
        opp.StageName = 'Introduction';
        opp.CurrencyIsoCode = 'GBP';
        opp.CloseDate = System.today();
        insert opp;
        
        Quote qc = new Quote();
        qc.Name = 'Test Quote';
        qc.OpportunityId = opp.Id;
        qc.ExpirationDate = system.today();
        qc.Status = 'Draft';
        insert qc;
        
        Rebate__c reb = new Rebate__c();
        reb.Account__c = acc.Id;
        reb.Reason_for_Rebate__c = 'Test';
        reb.Rebate_Commencement_Date__c = System.today() ;
        reb.Rebate_Expiry_Date__c = System.today().addDays(7);
        insert reb;
        
        Test.startTest();
        rebateSearchOnAccount.searchRebate(qc.Id);
        Test.stopTest();
    }
}