force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market that holds the Budget</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_SalesOrganizations__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_SalesOrganizations__c</fullName>
    <label>Sales Organizations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VD10</fullName>
            </value>
            <value>
                <fullName>VD50</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customers.recordType-meta.xml
<RecordType>
    <fullName>Customers</fullName>
    <active>true</active>
    <description>Past or Present</description>
    <label>Customers</label>
</RecordType>

force-app/main/default/objects/Bottle__c/Bottle__c.object-meta.xml
<CustomObject>
    <description>Unique Product Identifiers and Descriptions</description>
    <label>Bottle</label>
    <nameField>
        <label>Bottle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bottle__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <description>Product Code</description>
    <externalId>true</externalId>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>Bottle Identifier</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <label>SAP Material Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/SAP_Model_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Model_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Model Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/Weight_per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Weight_per_Unit__c</fullName>
    <description>Weight per unit in grams</description>
    <label>Weight per Unit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_Categorizacion_Incidencia__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_Categorizacion_Incidencia__c</fullName>
    <label>Categorización incidencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_Defecto__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_Defecto__c</fullName>
    <label>Defecto</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_DetectadasEnClienteDeCuantas__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_DetectadasEnClienteDeCuantas__c</fullName>
    <label>Detectadas en cliente de cuantas</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_loteOAlbaran__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_loteOAlbaran__c</fullName>
    <label>Lote o albarán</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_SAC_modeloYDenominacion__c.field-meta.xml
<CustomField>
    <fullName>OM_SAC_modeloYDenominacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo y denominación</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_VID_EAN__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_EAN__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>EAN</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SAP_Material_Code__c.OM_ProductRef__c</field>
            <operation>equals</operation>
            <valueField>$Source.OM_SAC_modeloYDenominacion__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SAP_Material_Code__c</referenceTo>
    <relationshipLabel>Insatisfacciones</relationshipLabel>
    <relationshipName>Insatisfacciones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OM_VID_Planta__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Planta__c</fullName>
    <label>Planta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1010</fullName>
                <label>Aiala</label>
            </value>
            <value>
                <fullName>1020</fullName>
                <label>Crisnova</label>
            </value>
            <value>
                <fullName>1030</fullName>
                <label>Castellar</label>
            </value>
            <value>
                <fullName>1040</fullName>
                <label>Gallo</label>
            </value>
            <value>
                <fullName>1090</fullName>
                <label>Santos Barosa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Insatisfacciones (Product)</relationshipLabel>
    <relationshipName>Insatisfacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawing__c/Drawing__c.object-meta.xml
<CustomObject>
    <description>This object is the place to store all design drawings and pack specs.</description>
    <label>Drawing</label>
    <nameField>
        <label>Drawing Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drawings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawing__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drawings</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawing__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bottle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bottle__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>Drawings</relationshipLabel>
    <relationshipName>Drawings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawing__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product look-up Fifty</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Drawings</relationshipLabel>
    <relationshipName>Drawings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawing__c/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <formula>Account__r.SAP_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawing__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SAP Material Code</label>
    <referenceTo>SAP_Material_Code__c</referenceTo>
    <relationshipLabel>Drawings</relationshipLabel>
    <relationshipName>Drawings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market Fifty field</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Volume_000_s__c.field-meta.xml
<CustomField>
    <fullName>Volume_000_s__c</fullName>
    <description>Please enter total number of units in thousands</description>
    <inlineHelpText>Please enter total number of units in thousands</inlineHelpText>
    <label>Volume (000&apos;s)</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cuenta__c in spanish org</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Drawing__c.field-meta.xml
<CustomField>
    <fullName>Drawing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawing ID</label>
    <referenceTo>Drawing__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OM_VID_DetallesAdicionales__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_DetallesAdicionales__c</fullName>
    <label>Detalles Adicionales</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/SAP_Material_Code__c.object-meta.xml
<CustomObject>
    <label>SAP Material Code</label>
    <nameField>
        <label>SAP Material Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Material Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Material_Code__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <label>Bottle</label>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>SAP Material Codes</relationshipLabel>
    <relationshipName>SAP_Material_Codes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <label>Bottle Identifier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/Material_Code_Key__c.field-meta.xml
<CustomField>
    <fullName>Material_Code_Key__c</fullName>
    <description>Copy of SAP Material Code Name</description>
    <externalId>true</externalId>
    <label>Material Code Key</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/OM_ProductRef__c.field-meta.xml
<CustomField>
    <fullName>OM_ProductRef__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SAP Material Codes</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/SAP_Model_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Model_Number__c</fullName>
    <formula>Bottle__r.SAP_Model_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Model Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>NM</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>RM</fullName>
        <isActive>false</isActive>
        <label>RM</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <isActive>false</isActive>
        <label>RO</label>
    </customValue>
    <description>geographically sales are divided in 4 markets</description>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OM_VID_TestUtils.cls
@isTest
public class OM_VID_TestUtils {
    
    //Test Methods to create Users with profile
    public static User createVidralaUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Fifty Sales Office Profile'];
        User u = new User(Alias = 'vidUser', Email='vidralauser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='vidralauser@testorg.com');
        
        return u;
        
    }
    
    public static void createAccountsWithContacts(Integer accNumber){
        	Id customerRecordType = OM_Utils.RecordTypes.getRecordTypeByDevName('Account', 'Customers');
            List<Account> accListToInsert = new List<Account>();
            for(Integer i = 0; i < accNumber; i++){
                Account objAccount = new Account(Name = 'mockAcckount' + i.toString(), BillingCity = 'Test City', BillingState = 'Test State', 
                BillingStreet = 'Test Street', BillingPostalCode = '12345', Market__c = 'ES', RecordTypeId = customerRecordType, OM_VID_SalesOrganizations__c = 'VD10',
                BillingCountry = 'Test Country', Phone = '90909009'+i.toString(), SAP_Account_Number__c = '1234'+i.toString());
    
                accListToInsert.add(objAccount);
            }
            
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true; 
            Database.insert(accListToInsert, dml); 
    
            //insert accListToInsert;
            createContacts(accListToInsert);
    }
    
    public static void createContacts(List<Account> accList){
        List<Contact> conListToInsert = new List<Contact>();
        for(Account acc : accList){
            Contact cont = new Contact(FirstName = 'Test', LastName = acc.Name, Phone = acc.Phone, Email = 'test@test.com', AccountId = acc.Id);
            conListToInsert.add(cont);
        }

        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true; 
        Database.insert(conListToInsert, dml);
        //insert conListToInsert;
    }

    public static void createDrawingWithContentVersion(String accountId/*, String productId*/){
        Drawing__c draw = new Drawing__c();
        draw.Account__c = accountId;
        //draw.Product__c = productId;
        draw.Name = '1234';
        insert draw;

        createContentVersion(draw.Id);
    }

    public static void createQuoteLineItem(OpportunityLineItem oppLine, String quoteId){
        QuoteLineItem qLine = new QuoteLineItem();
        qLine.OpportunityLineItemId = oppLine.Id;
        qLine.QuoteId = quoteId;
        qLine.Quantity = oppLine.Quantity;
        qLine.PricebookEntryId = oppLine.PricebookEntryId;
        qLine.Product2Id = oppLine.Product2Id;
        qLine.UnitPrice = oppLine.UnitPrice;
        qLine.Description = oppLine.Description;

        insert qLine;
    }

    public static void createContentVersion(String quoteId){
        ContentVersion contentVersion = new ContentVersion(Title = 'oferta cliente test', PathOnClient = 'Pic.jpg', VersionData = Blob.valueOf('Test Content'), IsMajorVersion = true);

        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        //create ContentDocumentLink  record

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = quoteId;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
    }

    public static void createQuotes(Integer quoteNum){
        List<Quote> quoteToInsert = new List<Quote>();
        List<Opportunity> oppList = createOpportunities(1);
        String recordTypeId = [SELECT Id from RecordType where SobjectType = :OM_VID_Constants.quoteName and DeveloperName = :OM_VID_Constants.quoteRTFifty].Id;
        for(Integer i = 0; i < quoteNum; i++){
            Quote q = new Quote(Name = 'Quote' + i.toString(),
            OpportunityId = oppList[0].Id,
            recordTypeId = recordTypeId,
            ExpirationDate = Date.today() + 30,
            OM_VID_DetallesAdicionales__c = 'Test');

            quoteToInsert.add(q);
        }

        insert quoteToInsert;
    }

    public static List<Opportunity> createOpportunities(Integer numOpp){
        String recordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = :OM_VID_Constants.oppName AND DeveloperName =: OM_VID_Constants.opportunityRTFifty LIMIT 1].Id;

        createAccountsWithContacts(1);

        Account objAccount = [SELECT Id FROM ACCOUNT LIMIT 1];
        Id pricebookId = Test.getStandardPricebookId();

        List<Opportunity> oppsToInsert = new List<Opportunity>();
        for(Integer i = 0; i < numOpp; i++){
            Opportunity opp = new Opportunity(Name = 'Test Opp v' + i.toString(), pricebook2Id  = pricebookId, AccountId = objAccount.Id, StageName = 'Introduction', RecordTypeId = recordTypeId, CloseDate = Date.today() + 1, CurrencyIsoCode = 'EUR');
            opp.Market__c = 'ES';
            oppsToInsert.add(opp);
        }

        insert oppsToInsert;
        return [
            SELECT 
                Id, Name
            FROM Opportunity
            WHERE RecordTypeId = :recordTypeId
        ];
    }

    public static void createOpportunityLineItems(List<Opportunity> listOpps, Integer numOppLines, String drawId){
        // Use pricebookId to setup PricebookEntry records
        PricebookEntry pb = createPriceBookEntry();
        Product2 producto = [SELECT Id FROM Product2 LIMIT 1];
        if(drawId != '') producto.Drawing__c = drawId;
        update producto;

        List<OpportunityLineItem> oppLineToInsert = new List<OpportunityLineItem>();
        for(Opportunity opp : listOpps){
            for(Integer i = 0; i < numOppLines; i++){
                OpportunityLineItem oppLine = new OpportunityLineItem(OpportunityId = opp.Id, Product2Id = producto.iD, UnitPrice = 100, Volume_000_s__c = 3, PricebookEntryId = pb.Id, Description = 'Test', Quantity = 1);
                oppLineToInsert.add(oppLine);
            }
        }

        insert oppLineToInsert;
    }

    public static PricebookEntry createPriceBookEntry(){
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;
        
        Integer randomCode = Math.round(Math.random() * 8999) + 1000; 
        String codeStr = String.valueOf(randomCode);

        Product2 producto =new Product2();
        producto.Name='test';
        producto.productCode= codeStr;
        producto.isActive = true;
        producto.CurrencyIsoCode='EUR';        
        insert producto;

        PricebookEntry one = [SELECT ID, UnitPrice, IsActive, CurrencyISOCode FROM PricebookEntry WHERE CurrencyISOCode = 'EUR' LIMIT 1];
	    // one.pricebook2Id = standardPricebook.id;
	    // one.product2id =[SELECT Id FROM Product2 LIMIT 1].Id;
	    // one.unitprice = 1249.0;
	    // one.isactive = true;
	    // insert one;

        return one;
    }
    
    public static void createCases(Integer caseNum){
        List<Case> caseToInsert = new List<Case>();
        createAccountsWithContacts(1);
        Account objAccount = [SELECT Id FROM ACCOUNT LIMIT 1];
        
        String recordTypeId = [SELECT Id from RecordType where SobjectType = :OM_VID_Constants.caseName and DeveloperName = :OM_VID_Constants.insatisfaccionRTVidrala].Id;
        Product2 producto =new Product2();
        producto.Name='test';
        producto.productCode='1234';
        producto.isActive = true;
        producto.CurrencyIsoCode='EUR';        
        insert producto;
        
        Bottle__c botella = new Bottle__c(
                    Name = 'Bottle1',
                    Bottle_Identifier__c = '12324a',
                    SAP_Material_Code__c = '1234b',
                    SAP_Model_Number__c = '1234',
                    Weight_per_Unit__c = 200
                );
        insert botella;
        
        SAP_Material_Code__c material = new SAP_Material_Code__c(Material_Code_Key__c = '1234b');
        material.OM_ProductRef__c = producto.Id;
        material.Bottle__c = botella.Id;
        insert material;
        
        for(Integer i = 0; i < caseNum; i++){
            Case ins = new Case(
            	AccountId = objAccount.Id,
            	RecordTypeId = recordTypeId,
                OM_SAC_Categorizacion_Incidencia__c = 'A',
                OM_SAC_loteOAlbaran__c = '1234554',
                OM_SAC_Defecto__c = 'test',
                OM_SAC_modeloYDenominacion__c = producto.Id,
                OM_VID_Planta__c = '1030',
                OM_SAC_DetectadasEnClienteDeCuantas__c = '2',
                OM_VID_EAN__c = material.Id
			);

            caseToInsert.add(ins);
        }

        insert caseToInsert;
    }
}