force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The distributor of which competitor? Indicate</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <displayFormat>Dcto - {0000}</displayFormat>
        <label>Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/EUR__c.field-meta.xml
<CustomField>
    <fullName>EUR__c</fullName>
    <label>EUR</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProductName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/TYPE__c.field-meta.xml
<CustomField>
    <fullName>TYPE__c</fullName>
    <label>TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZDES - Descuento especial</fullName>
            </value>
            <value>
                <fullName>ZDUN - Descuento unitario</fullName>
            </value>
            <value>
                <fullName>ZDVR - Descuento sobre vidrio</fullName>
            </value>
            <value>
                <fullName>ZSKT - Descuento por pronto pago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOT</fullName>
            </value>
            <value>
                <fullName>PAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/Packaging_Agreement__c.object-meta.xml
<CustomObject>
    <description>Vidrala Fifty Spain Object From Org Migration 2021
&quot;Objetivo que agrupa los convenios de embalaje de los materiales de los clientes&quot;</description>
    <label>Packaging Agreement</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Packaging Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packaging Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Packaging_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Packaging Agreements</relationshipLabel>
    <relationshipName>Packaging_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abono buenos y a reparar</fullName>
            </value>
            <value>
                <fullName>Abono buenos y a reparar Italia</fullName>
            </value>
            <value>
                <fullName>Abono todos</fullName>
            </value>
            <value>
                <fullName>Depósito</fullName>
            </value>
            <value>
                <fullName>Gratuito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Agreement_Code__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Code__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Credit_Price__c.field-meta.xml
<CustomField>
    <fullName>Credit_Price__c</fullName>
    <label>Credit Price</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Debit_Price__c.field-meta.xml
<CustomField>
    <fullName>Debit_Price__c</fullName>
    <label>Debit Price</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Packaging_Agreement__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <description>From Vidrala Spain Picklist</description>
    <label>Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8001378 PALETA ANIFE RETORNABLE 1200X1000X155</fullName>
                <default>true</default>
                <label>PALETA ANIFE RETORNABLE 1200X1000X155</label>
            </value>
            <value>
                <fullName>8001392 PALETA VMF RETORNABLE 1200X1000X154</fullName>
                <label>PALETA VMF RETORNABLE 1200X1000X154</label>
            </value>
            <value>
                <fullName>8000355 PLANCHA PP CARTONPLAST PCA 1200X1000 ALV</fullName>
                <label>PLANCHA PP CARTONPLAST PCA 1200X1000 ALV</label>
            </value>
            <value>
                <fullName>8000385 PLANCHA PP VIDRALA PVE EXPORT 1200X1000</fullName>
                <label>PLANCHA PP VIDRALA PVE EXPORT 1200X1000</label>
            </value>
            <value>
                <fullName>8000042 PALETA RG01 RETORNAB. ALIG 1200X1000X125</fullName>
                <label>PALETA RG01 RETORNAB. ALIG 1200X1000X125</label>
            </value>
            <value>
                <fullName>8003618 PLACA PP SMARTPAD 1200X1000 2,6 -3mm PSM</fullName>
                <label>PLACA PP SMARTPAD 1200X1000 2,6 -3mm PSM</label>
            </value>
            <value>
                <fullName>8003625 Top Frame - 25 mm</fullName>
                <label>TOP FRAME - 25 mm</label>
            </value>
            <value>
                <fullName>8003835 PALETES HK RETORNABLE 1200X1000X162</fullName>
                <label>PALETES HK RETORNABLE 1200X1000X162</label>
            </value>
            <value>
                <fullName>8002589 PALETA TF RETORNABLE 1200X1000X145</fullName>
                <label>PALETA TF RETORNABLE  1200X1000X145</label>
            </value>
            <value>
                <fullName>8002626 PALETA DIN (T5) RETORNABLE 1200X1000X134</fullName>
                <label>PALETA DIN (T5) RETORNABLE 1200X1000X134</label>
            </value>
            <value>
                <fullName>8002627 PALETA EURO RETORNABLE 1200X 800X144</fullName>
                <label>PALETA EURO RETORNABLE     1200X 800X144</label>
            </value>
            <value>
                <fullName>8002628 PALETA UK 1200X1000X150</fullName>
                <label>PALETA UK 1200X1000X150</label>
            </value>
            <value>
                <fullName>8000350 PLACA 1200X1000 PP VIDRALA AKY 3.5mm PVE</fullName>
                <label>PLACA 1200X1000 PP VIDRALA AKY 3.5mm PVE</label>
            </value>
            <value>
                <fullName>8000360 PLACA 1200X1000 PP CPL 3mm SANDWICH PCS</fullName>
                <label>PLACA 1200X1000 PP CPL 3mm SANDWICH PCS</label>
            </value>
            <value>
                <fullName>8000397 PLACA 1200X1000 PP CPL 3mm SDW TROQ PCST</fullName>
                <label>PLACA 1200X1000 PP CPL 3mm SDW TROQ PCST</label>
            </value>
            <value>
                <fullName>8003021 PALETA EQ ENCIRC RET 1200X1000X157</fullName>
                <label>PALETA EQ ENCIRC RET 1200X1000X157</label>
            </value>
            <value>
                <fullName>8002598 INTERFAL.PVI ALVEOL 1200X1000X3.4 VERDE</fullName>
                <label>INTERFAL.PVI ALVEOL 1200X1000X3.4 VERDE</label>
            </value>
            <value>
                <fullName>8003836 TAPA PP MACIZA SMARTCAP 1200X1000 TSM</fullName>
                <label>TAPA PP MACIZA SMARTCAP 1200X1000 TSM</label>
            </value>
            <value>
                <fullName>8002517 PALETA DE MADERA CHEP RECUPERABLE</fullName>
                <label>PALETA DE MADERA CHEP RECUPERABLE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Packaging_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Packaging Agreement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account_Id_Copy__c</field>
            <operation>equals</operation>
            <valueField>Packaging_Agreement__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Packaging_Agreement__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scales</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Product and Scales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomRelatedListController.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        CustomRelatedListController.cls
   Description: Controller class for fetching related records based on the provided record ID. Provides methods to retrieve
                discounts and packaging agreements associated with an account derived from the given record ID.
   
   Date         Version Author    Summary of Changes
   -----------  ------- --------- ------------------------------------------------------------------------------
   Sep 2024     1.0     Globant   Initial Release
----------------------------------------------------------------------------------------------------------------------- */

public with sharing class CustomRelatedListController {
    /**
     * Retrieves a list of Discount__c records associated with the account derived from the provided record ID.
     * 
     * @param recordId String - The record ID from which the account ID will be derived.
     * @return List<Discount__c> - A list of Discount__c records related to the account.
     */
    @AuraEnabled(Cacheable = true)
    public static List<Discount__c> getDiscounts(String recordId) {
        if (String.isEmpty(recordId)) {
            return new List<Discount__c>();
        }

        String accountId = getAccountId(recordId);
        List<Discount__c> discounts = new List<Discount__c>();

        if (String.isNotEmpty(accountId)) {
            discounts = [
                SELECT Id, Name, Status__c, CurrencyIsoCode, Account__c, TYPE__c, ProductName__c, Unit_Type__c, Quantity__c, Percentage__c, EUR__c 
                FROM Discount__c
                WHERE Account__c = :accountId
                WITH SECURITY_ENFORCED
            ];
        }
        
        return discounts; 
    }

    /**
     * Retrieves a list of Packaging_Agreement__c records associated with the account derived from the provided record ID.
     * 
     * @param recordId String - The record ID from which the account ID will be derived.
     * @return List<Packaging_Agreement__c> - A list of Packaging_Agreement__c records related to the account.
     */
    @AuraEnabled(Cacheable = true)
    public static List<Packaging_Agreement__c> getAgreements(String recordId) {
        if (String.isEmpty(recordId)) {
            return new List<Packaging_Agreement__c>();
        }

        String accountId = getAccountId(recordId);
        List<Packaging_Agreement__c> agreements = new List<Packaging_Agreement__c>();

        if (String.isNotEmpty(accountId)) {
            agreements = [
                SELECT Id, Name, Material__c, Agreement__c, Account__c, Agreement_Code__c, Credit_Price__c, Debit_Price__c 
                FROM Packaging_Agreement__c 
                WHERE Account__c = :accountId
                WITH SECURITY_ENFORCED
            ];
        }
        
        return agreements; 
    }

    /**
     * Retrieves the AccountId associated with a given Quote record ID.
     * 
     * @param quoteId String - The Quote record ID.
     * @return String - The Account ID associated with the provided Quote ID.
     */
    private static String getAccountId(String quoteId) {
        if (String.isEmpty(quoteId)) {
            return null;
        }

        Quote quoteRecord;
        try {
            quoteRecord = [
                SELECT Id, Name, AccountId 
                FROM Quote
                WHERE Id = :quoteId
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
        } catch (QueryException e) {
            return null;
        }

        if (quoteRecord == null) {
            return null;
        }

        return quoteRecord.AccountId;    
    }
}





// TODO remove once it has been tested/validated/QA-ed
/*public with sharing class CustomRelatedListController {

    private static String accountId;

    @AuraEnabled(Cacheable = true)
    public static List<Discount__c> getDiscounts(String recordId) {
        //quoteId = recordId;
        accountId = getAccountId(recordId);
        List<Discount__c> discounts = new List<Discount__c>();

        if (String.isNotEmpty(accountId)) {
            discounts = [
                SELECT Id, Name, Status__c, CurrencyIsoCode, Account__c, TYPE__c, ProductName__c, Unit_Type__c, Quantity__c, Percentage__c, EUR__c 
                FROM Discount__c
                WHERE Account__c = :accountId
            ];
        }
        
        return discounts; 
    }

    @AuraEnabled(Cacheable = true)
    public static List<Packaging_Agreement__c> getAgreements(String recordId) {
        accountId = getAccountId(recordId);
        List<Packaging_Agreement__c> agreements = new List<Packaging_Agreement__c>();

        if (String.isNotEmpty(accountId)) {
            agreements = [
                SELECT Id, Name, Material__c, Agreement__c, Account__c, Agreement_Code__c, Credit_Price__c, Debit_Price__c 
                FROM Packaging_Agreement__c 
                WHERE Account__c = :accountId
            ];
        }
        
        return agreements; 
    }

    private static String getAccountId(String quoteId) {
        Quote quoteRecord = [
            SELECT Id, Name, AccountId 
            FROM Quote
            WHERE Id = :quoteId
            LIMIT 1
        ];
        return quoteRecord.AccountId;
    }
}*/