force-app/main/default/objects/Account/fields/Haulier__c.field-meta.xml
<CustomField>
    <fullName>Haulier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Haulier</label>
    <referenceTo>Haulier__c</referenceTo>
    <relationshipLabel>Haulier Account</relationshipLabel>
    <relationshipName>HaulierAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Haulier.recordType-meta.xml
<RecordType>
    <fullName>Haulier</fullName>
    <active>true</active>
    <description>The record type to be used for Haulier accounts.</description>
    <label>Haulier</label>
</RecordType>

force-app/main/default/objects/Dispatch__c/Dispatch__c.object-meta.xml
<CustomObject>
    <description>Dispatch records created by the daily batch load</description>
    <label>Dispatch</label>
    <nameField>
        <label>Dispatch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispatches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <description>Delivery forecast by account, month and product</description>
    <label>Forecast</label>
    <referenceTo>Forecast__c</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Haulier__c.field-meta.xml
<CustomField>
    <fullName>Haulier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to Haulier Name</description>
    <label>Haulier</label>
    <referenceTo>Haulier__c</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup relationship to the month of the forecast/budget</description>
    <label>Month</label>
    <referenceTo>Month__c</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch_Staging__c/Dispatch_Staging__c.object-meta.xml
<CustomObject>
    <description>Staging object for loading Dispatch records</description>
    <label>Dispatch Staging</label>
    <nameField>
        <displayFormat>DL{000000}</displayFormat>
        <label>Dispatch Load ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Staging</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Staging__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <formula>Month__c &amp; &quot;-&quot; &amp; Bottle_Identifier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forecast</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch_Staging__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>TEXT( Sales_Organization__c )&amp; &quot;-&quot; &amp; LPAD(Encirc_Account_Number__c, 7, &apos;0&apos;) &amp; &quot;-&quot; &amp; TEXT(YEAR( Planned_Delivery_Date__c )) &amp; &quot;-&quot; &amp; LPAD(TEXT(MONTH( Planned_Delivery_Date__c )), 2, &apos;0&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <description>Delivery Forecasts by Account, Month and Product (Bottle)</description>
    <label>Forecast</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Forecast</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>Forecast at Month level within Account</description>
    <label>Month</label>
    <referenceTo>Month__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Haulier__c/Haulier__c.object-meta.xml
<CustomObject>
    <label>Haulier</label>
    <nameField>
        <label>Haulier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hauliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month__c/Month__c.object-meta.xml
<CustomObject>
    <description>Delivery Budgets and Forecasts by Account and Month</description>
    <label>Month Forecast</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast</label>
    <summarizedField>Forecast__c.Forecast__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/DispatchLoadBatchTest.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        DispatchLoadBatchTest.cls
   Description: Test the DispatchLoadBatch batch Apex class
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Dec 2017     1.0     M.Witchalls(Ciber)  Initial Release 
   Oct 2024     2.0     Globant             Refactor 
------------------------------------------------------------------------------------------------------------------------ */        

@isTest
private class DispatchLoadBatchTest  {
    private static final String HAULIER_NUM = '1234';
    private static final Integer NUM_BOTTLES = 200000;
    private static final Integer NUM_TONNES = 20;
    private static final Integer ACCOUNT_FIRST_NUM = 10001;
    private static final Integer FORECAST_NUM_BOTTLES = 1;
    private static final Integer FORECAST_BUDGET = 800;
    private static final Integer FORECAST_AMOUNT = 1000;
    private static final Integer DISPATCH_MONTHS = 1;

    @isTest static void testBatch() {
        
        
        // Use Test Data Factory to create Account and related records
        List<Account> accountList = TestDataFactory.createAccountsWithMonths(1, ACCOUNT_FIRST_NUM);
        String accountNumber = accountList[0].SAP_Account_Number__c;

        // Create forecast and dispatch staging records
        List<Forecast__c> forecastList = TestDataFactory.createForecasts(FORECAST_NUM_BOTTLES, accountNumber,FORECAST_BUDGET, FORECAST_AMOUNT);
        
        
        List<Month__c> mList = [SELECT Id from Month__c LIMIT 2];
        delete mList;
        
        List<Dispatch_Staging__c> dispatchStagingList = TestDataFactory.createDispatchStaging(DISPATCH_MONTHS, accountNumber, HAULIER_NUM, NUM_BOTTLES, NUM_TONNES);

        // Start test
        Test.startTest();
        DispatchLoadSchedulable schedulableJob = new DispatchLoadSchedulable();
        schedulableJob.execute(null);
        Test.stopTest();
        

        // Retrieve counts for assertions
        Integer dispatchCount = [SELECT COUNT() FROM Dispatch__c];
        Integer forecastCount = [SELECT COUNT() FROM Forecast__c];
        Integer haulierCount = [SELECT COUNT() FROM Haulier__c];


        // Assertions
        //System.assertEquals(dispatchStagingList.size(), dispatchCount, 'Dispatch count mismatch');
        System.assertEquals(forecastList.size(), forecastCount, 'Forecast count mismatch');
        System.assertEquals(1, haulierCount, 'Haulier count mismatch');

    }
    
    

    @isTest static void testScheduler() {
        Test.startTest();
        DispatchLoadScheduler dispatchLoadScheduler = new DispatchLoadScheduler();
        String scheduleExpression = '0 0 23 * * ?';
        system.schedule('TestDispatchLoadScheduler', scheduleExpression, dispatchLoadScheduler);
        Test.stopTest();
    }
}


/*@isTest
private class TestDispatchLoadBatch  {
    private static String haulierNum = '1234';
    private static Integer numBottles = 200000;
    private static Integer numTonnes = 20;
 
    @isTest static void testBatch() {
        // create one Account
        List<Account> aList = TestDataFactory.createAccountsWithMonths(1, 10001);
        String acctNum = aList[0].SAP_Account_Number__c;
        
        // create 96 forecast records (8 x 12 months)
        List<Forecast__c> fList = TestDataFactory.createForecasts(8, acctNum, 800, 1000);
        
        //  // delete some months
        //  List<Month__c> mList = [SELECT Id from Month__c LIMIT 2];
        //  delete mList;
        
        // create 120 dispatch staging records (10 x 12 months)
        List<Dispatch_Staging__c> dList = TestDataFactory.createDispatchStaging(10, acctNum, haulierNum, numBottles, numTonnes);
        
        
        
        Test.startTest();
        DispatchLoadBatch dlb = new DispatchLoadBatch();
        ID jobId = Database.executeBatch(dlb);
        Test.stopTest();
        
        Integer dispatchCount = [select count() from Dispatch__c];
        Integer forecastCount = [select count() from Forecast__c];
        Integer haulierCount = [select count() from Haulier__c];
        
        //system.assertEquals(dispatchCount, 122);
        //system.assertEquals(forecastCount, 120);
        //system.assertEquals(haulierCount, 1);       
     }
    
    @isTest static void testScheduler() {
        Test.StartTest();
        DispatchLoadScheduler sh1 = new DispatchLoadScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, sh1);
        Test.stopTest();
    }
    
}*/