force-app/main/default/objects/Account/fields/Haulier__c.field-meta.xml
<CustomField>
    <fullName>Haulier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Haulier</label>
    <referenceTo>Haulier__c</referenceTo>
    <relationshipLabel>Haulier Account</relationshipLabel>
    <relationshipName>HaulierAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bottle__c/Bottle__c.object-meta.xml
<CustomObject>
    <description>Unique Product Identifiers and Descriptions</description>
    <label>Bottle</label>
    <nameField>
        <label>Bottle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bottle__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <description>Product Code</description>
    <externalId>true</externalId>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>Bottle Identifier</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/Weight_per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Weight_per_Unit__c</fullName>
    <description>Weight per unit in grams</description>
    <label>Weight per Unit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/Dispatch__c.object-meta.xml
<CustomObject>
    <description>Dispatch records created by the daily batch load</description>
    <label>Dispatch</label>
    <nameField>
        <label>Dispatch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispatches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Reference to Bottle Description</description>
    <label>Bottle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bottle__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <formula>Bottle__r.Bottle_Identifier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bottle Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Collapsed__c.field-meta.xml
<CustomField>
    <fullName>Collapsed__c</fullName>
    <formula>Collapsed_Loads__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Collapsed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Collapsed_Loads__c.field-meta.xml
<CustomField>
    <fullName>Collapsed_Loads__c</fullName>
    <description>Number of collapsed loads for this dispatch (normally 0 or 1)</description>
    <label>Collapsed Loads</label>
    <summaryFilterItems>
        <field>Late_Load__c.Collapsed__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Late_Load__c.Dispatch__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>The Encirc Account Number of the associated account</description>
    <formula>Customer__r.Encirc_Account_Number__c &amp; &quot;/&quot; &amp;  Customer__r.SAP_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Delivery_Code__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Code__c</fullName>
    <label>Delivery Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <formula>IF( Late_Loads__c &gt; 0, &apos;Late&apos;, 
  IF( Early_Loads__c &gt; 0, &apos;Early&apos;, &apos;On Time&apos; )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Dispatch_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Date__c</fullName>
    <description>Date of the dispatch</description>
    <label>Dispatch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Dispatch_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Date_Time__c</fullName>
    <description>Date and time of dispatch</description>
    <label>Dispatch Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Dispatch_ID__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_ID__c</fullName>
    <description>Semi-unique identifier of Dispatch; requires the addition of Pack Specification to make it unique</description>
    <externalId>true</externalId>
    <label>Dispatch ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Dispatch_Time__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Time__c</fullName>
    <label>Dispatch Time</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Early_Late_Collapsed_Loads__c.field-meta.xml
<CustomField>
    <fullName>Early_Late_Collapsed_Loads__c</fullName>
    <description>Early, Late or Collapsed Loads for this Dispatch</description>
    <inlineHelpText>Early, Late or Collapsed Loads for this Dispatch</inlineHelpText>
    <label>Number of Early/Late/Collapsed Loads</label>
    <summaryForeignKey>Late_Load__c.Dispatch__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Early_Loads__c.field-meta.xml
<CustomField>
    <fullName>Early_Loads__c</fullName>
    <description>Number of early deliveries for this dispatch (normally 0 or 1)</description>
    <inlineHelpText>Number of early deliveries for this dispatch (normally 0 or 1)</inlineHelpText>
    <label>Early Loads</label>
    <summaryFilterItems>
        <field>Late_Load__c.Status__c</field>
        <operation>equals</operation>
        <value>Early</value>
    </summaryFilterItems>
    <summaryForeignKey>Late_Load__c.Dispatch__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Early_or_Late_Loads__c.field-meta.xml
<CustomField>
    <fullName>Early_or_Late_Loads__c</fullName>
    <formula>Early_Loads__c +  Late_Loads__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Early or Late Loads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Freight_Reference__c.field-meta.xml
<CustomField>
    <fullName>Freight_Reference__c</fullName>
    <label>Freight Reference</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Haulier__c.field-meta.xml
<CustomField>
    <fullName>Haulier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to Haulier Name</description>
    <label>Haulier</label>
    <referenceTo>Haulier__c</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Haulier_Code__c.field-meta.xml
<CustomField>
    <fullName>Haulier_Code__c</fullName>
    <formula>Haulier__r.Haulier_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Haulier Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Late_Loads__c.field-meta.xml
<CustomField>
    <fullName>Late_Loads__c</fullName>
    <description>Number of times delivery was delayed</description>
    <inlineHelpText>Number of times delivery was delayed</inlineHelpText>
    <label>Late Loads</label>
    <summaryFilterItems>
        <field>Late_Load__c.Status__c</field>
        <operation>equals</operation>
        <value>Late</value>
    </summaryFilterItems>
    <summaryForeignKey>Late_Load__c.Dispatch__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Load_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Load_Job_Id__c</fullName>
    <description>The Job Id of the batch Apex run which created or last updated this record</description>
    <label>Load Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup relationship to the month of the forecast/budget</description>
    <label>Month</label>
    <referenceTo>Month__c</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/On_Time_Loads__c.field-meta.xml
<CustomField>
    <fullName>On_Time_Loads__c</fullName>
    <description>Load delivered on time and in full:  1 or 0</description>
    <formula>IF(AND(Delivery_Status__c == &quot;On Time&quot;, NOT(Collapsed__c)), 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OTIF Loads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Pack_Specification__c.field-meta.xml
<CustomField>
    <fullName>Pack_Specification__c</fullName>
    <description>Textual packaging information</description>
    <label>Pack Specification</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Planned_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Delivery_Date__c</fullName>
    <label>Planned Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Site_ID__c</fullName>
    <description>ID code of Site</description>
    <label>Site ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Staging_Id__c.field-meta.xml
<CustomField>
    <fullName>Staging_Id__c</fullName>
    <description>The Salesforce Id of the staging record which generated or last updated this record</description>
    <label>Staging ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Tonnage__c.field-meta.xml
<CustomField>
    <fullName>Tonnage__c</fullName>
    <description>Weight of dispatch in tonnes</description>
    <inlineHelpText>Weight of dispatch in tonnes</inlineHelpText>
    <label>Tonnage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>Quantity of units in thousands</description>
    <inlineHelpText>Quantity of units in Thousands</inlineHelpText>
    <label>Units</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Warehouse_ID__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_ID__c</fullName>
    <description>ID code of warehouse</description>
    <label>Warehouse ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <description>Week of year, which may start in the previous year</description>
    <label>Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Week_in_Month__c.field-meta.xml
<CustomField>
    <fullName>Week_in_Month__c</fullName>
    <description>Week in month, which may start in the previous month</description>
    <label>Week in Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Haulier__c/Haulier__c.object-meta.xml
<CustomObject>
    <label>Haulier</label>
    <nameField>
        <label>Haulier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hauliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Haulier__c/fields/Haulier_Code__c.field-meta.xml
<CustomField>
    <fullName>Haulier_Code__c</fullName>
    <description>Identifier of Haulier</description>
    <externalId>true</externalId>
    <label>Haulier Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Month__c/Month__c.object-meta.xml
<CustomObject>
    <description>Delivery Budgets and Forecasts by Account and Month</description>
    <label>Month Forecast</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to related customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Months</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DispatchProvider.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        DispatchProvider.cls
   Description: Provider class for the Dispatch__c object
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Nov 2017     1.0     M.Witchalls(Ciber)  Initial Release 
   Sep 2024     1.1     Globant             Code refactoring and added comments
------------------------------------------------------------------------------------------------------------------------ */        

public with sharing class DispatchProvider {
    
    /**
     * Retrieves a map of Dispatch__c records by their IDs.
     * 
     * @param idSet - Set of Dispatch__c record IDs.
     * @return A map of Dispatch__c records keyed by their IDs, or an empty map if input is null or empty.
     */
    public Map<ID, Dispatch__c> getDispatchMapById(Set<String> idSet) {
        if (idSet == null || idSet.isEmpty()) {
            return new Map<ID, Dispatch__c>();
        }
        
        return new Map<ID, Dispatch__c>([
            SELECT
                Id, Name, Month__c, Week__c, Week_in_Month__c, Dispatch_ID__c, 
                Dispatch_Date__c, Dispatch_Time__c, Dispatch_Date_Time__c, Delivery_Code__c, 
                Customer__c, Customer_ID__c, Customer__r.Name, Bottle__c, Bottle_Identifier__c, Bottle__r.Name,
                Haulier__c, Haulier_Code__c, Haulier__r.Name, Freight_Reference__c, 
                Warehouse_ID__c, Units__c, Type__c, Tonnage__c, 
                Staging_Id__c, Site_ID__c, Planned_Delivery_Date__c, Pack_Specification__c, 
                Collapsed_Loads__c, Late_Loads__c, Early_Loads__c, Early_Late_Collapsed_Loads__c, On_Time_Loads__c, Early_or_Late_Loads__c,
                Load_Job_Id__c, Collapsed__c, Delivery_Status__c,
                Weight_per_Unit__c
            FROM 
                Dispatch__c 
            WHERE
                Id in :idSet
        ]);
    }
    
    /**
     * Retrieves a Dispatch__c record by its ID.
     * 
     * @param id - ID of the Dispatch__c record.
     * @return The Dispatch__c record with the given ID, or null if input is null or empty, or if the record is not found.
     */
    public Dispatch__c getDispatchById(String id) {
        if (String.isBlank(id)) {
            return null;
        }

        Map<ID, Dispatch__c> dispatchMap = getDispatchMapById(new Set<String>{id});
        return dispatchMap.get(id);
    }
    
    /**
     * Retrieves aggregate totals of late load metrics for the current month.
     * 
     * @return A list of AggregateResult objects containing totals of various late load metrics, or an empty list if no records found.
     */
    public List<AggregateResult> currentMonthLateLoadTotals() {
        List<AggregateResult> results = [
            SELECT
                Customer__r.Name customer,
                SUM(On_Time_Loads__c) ontime,
                SUM(Early_Loads__c) early,
                SUM(Late_Loads__c) late,
                SUM(Collapsed_Loads__c) collapsed,
                SUM(Early_or_Late_Loads__c) earlyOrLate,
                SUM(Early_Late_Collapsed_Loads__c) earlyLateCollapsed
            FROM
                Dispatch__c
            WHERE
                Current_Month_Delivery__c = true
            AND
                Exclude_from_OTIF__c = false
            GROUP BY
                Customer__r.Name
            HAVING
                SUM(Early_Late_Collapsed_Loads__c) > 0
        ];
        
        if (results == null || results.isEmpty()) {
            return new List<AggregateResult>();
        } else {
            return results;
        }
    }
    
    /**
     * Retrieves aggregate totals of late load metrics for the last 48 hours.
     * 
     * @return A list of AggregateResult objects containing totals of various late load metrics for the last 48 hours, or an empty list if no records found.
     */
    public List<AggregateResult> last48hourLateLoadTotals() {
        List<AggregateResult> results = [
            SELECT
                Customer__r.Name customer,
                SUM(On_Time_Loads__c) ontime,
                SUM(Early_Loads__c) early,
                SUM(Late_Loads__c) late,
                SUM(Collapsed_Loads__c) collapsed,
                SUM(Early_or_Late_Loads__c) earlyOrLate,
                SUM(Early_Late_Collapsed_Loads__c) earlyLateCollapsed
            FROM
                Dispatch__c
            WHERE
                (Last_48_Hour_Late_Early_Delivery__c = true OR Last_48_Hour_Collapse__c = true)
            AND
                Exclude_from_OTIF__c = false
            GROUP BY
                Customer__r.Name
        ];

        if (results == null || results.isEmpty()) {
            return new List<AggregateResult>();
        } else {
            return results;
        }
    }
}


/*public with sharing class DispatchProvider {
    
    public Map<ID, Dispatch__c> getDispatchMapById(Set<String> idSet) {
        return new Map<ID, Dispatch__c> ([
            SELECT
                Id, Name, Month__c, Week__c, Week_in_Month__c, Dispatch_ID__c, 
                Dispatch_Date__c, Dispatch_Time__c, Dispatch_Date_Time__c, Delivery_Code__c, 
                Customer__c, Customer_ID__c, Customer__r.Name, Bottle__c, Bottle_Identifier__c, Bottle__r.Name,
                Haulier__c, Haulier_Code__c, Haulier__r.Name, Freight_Reference__c, 
                Warehouse_ID__c, Units__c, Type__c, Tonnage__c, 
                Staging_Id__c, Site_ID__c, Planned_Delivery_Date__c, Pack_Specification__c, 
                Collapsed_Loads__c, Late_Loads__c, Early_Loads__c, Early_Late_Collapsed_Loads__c, On_Time_Loads__c, Early_or_Late_Loads__c,
                Load_Job_Id__c, Collapsed__c, Delivery_Status__c,
                Weight_per_Unit__c
            FROM 
                Dispatch__c 
            WHERE
                Id in :idSet
        ]);
    }
    
    public Dispatch__c getDispatchById(String id) {
        Map<ID, Dispatch__c> dispatchMap = getDispatchMapById(new Set<String>{id});
        return dispatchMap.get(id);
    }
    
    public List<AggregateResult> currentMonthLateLoadTotals() {
        return [
            SELECT
                Customer__r.Name customer,
                SUM(On_Time_Loads__c) ontime,
                SUM(Early_Loads__c) early,
                SUM(Late_Loads__c) late,
                SUM(Collapsed_Loads__c) collapsed,
                SUM(Early_or_Late_Loads__c) earlyOrLate,
                SUM(Early_Late_Collapsed_Loads__c) earlyLateCollapsed
            FROM
                Dispatch__c
            WHERE
                Current_Month_Delivery__c = true
            AND
                Exclude_from_OTIF__c = false
            GROUP BY
                Customer__r.Name
            HAVING
                SUM(Early_Late_Collapsed_Loads__c) > 0
        ];
    }
    
    public List<AggregateResult> last48hourLateLoadTotals() {
        return [
            SELECT
                Customer__r.Name customer,
                SUM(On_Time_Loads__c) ontime,
                SUM(Early_Loads__c) early,
                SUM(Late_Loads__c) late,
                SUM(Collapsed_Loads__c) collapsed,
                SUM(Early_or_Late_Loads__c) earlyOrLate,
                SUM(Early_Late_Collapsed_Loads__c) earlyLateCollapsed
            FROM
                Dispatch__c
            WHERE
                (Last_48_Hour_Late_Early_Delivery__c = true OR Last_48_Hour_Collapse__c = true)
            AND
                Exclude_from_OTIF__c = false
            GROUP BY
                Customer__r.Name
        ];
    }
}*/