force-app/main/default/objects/Account/fields/Haulier__c.field-meta.xml
<CustomField>
    <fullName>Haulier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Haulier</label>
    <referenceTo>Haulier__c</referenceTo>
    <relationshipLabel>Haulier Account</relationshipLabel>
    <relationshipName>HaulierAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Haulier.recordType-meta.xml
<RecordType>
    <fullName>Haulier</fullName>
    <active>true</active>
    <description>The record type to be used for Haulier accounts.</description>
    <label>Haulier</label>
</RecordType>

force-app/main/default/objects/Dispatch_Staging__c/Dispatch_Staging__c.object-meta.xml
<CustomObject>
    <description>Staging object for loading Dispatch records</description>
    <label>Dispatch Staging</label>
    <nameField>
        <displayFormat>DL{000000}</displayFormat>
        <label>Dispatch Load ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispatch Staging</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Staging__c/fields/Dispatch_ID__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_ID__c</fullName>
    <description>Semi-unique identifier of Dispatch; requires the addition of Pack Specification to make it unique</description>
    <externalId>true</externalId>
    <label>Dispatch ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch_Staging__c/fields/Dispatch_Time__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Time__c</fullName>
    <label>Dispatch Time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch_Staging__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <formula>Month__c &amp; &quot;-&quot; &amp; Bottle_Identifier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forecast</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch_Staging__c/fields/Haulier_Code__c.field-meta.xml
<CustomField>
    <fullName>Haulier_Code__c</fullName>
    <label>Haulier Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch_Staging__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>TEXT( Sales_Organization__c )&amp; &quot;-&quot; &amp; LPAD(Encirc_Account_Number__c, 7, &apos;0&apos;) &amp; &quot;-&quot; &amp; TEXT(YEAR( Planned_Delivery_Date__c )) &amp; &quot;-&quot; &amp; LPAD(TEXT(MONTH( Planned_Delivery_Date__c )), 2, &apos;0&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch_Staging__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <label>SAP Material Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <description>Delivery Forecasts by Account, Month and Product (Bottle)</description>
    <label>Forecast</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Forecast</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>Forecast at Month level within Account</description>
    <label>Month</label>
    <referenceTo>Month__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SAP Material Code</label>
    <referenceTo>SAP_Material_Code__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Haulier__c/Haulier__c.object-meta.xml
<CustomObject>
    <label>Haulier</label>
    <nameField>
        <label>Haulier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hauliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Haulier__c/fields/Haulier_Code__c.field-meta.xml
<CustomField>
    <fullName>Haulier_Code__c</fullName>
    <description>Identifier of Haulier</description>
    <externalId>true</externalId>
    <label>Haulier Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Month__c/Month__c.object-meta.xml
<CustomObject>
    <description>Delivery Budgets and Forecasts by Account and Month</description>
    <label>Month Forecast</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast</label>
    <summarizedField>Forecast__c.Forecast__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/SAP_Material_Code__c.object-meta.xml
<CustomObject>
    <label>SAP Material Code</label>
    <nameField>
        <label>SAP Material Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Material Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DispatchStagingHandlerTest.cls
@isTest
private class DispatchStagingHandlerTest {
    // Declare parameters to avoid hardcoding
    private static final String HAULIER_NUM = '1234';
    private static final Integer NUM_BOTTLES = 200000;
    private static final Integer NUM_TONNES = 20;
    private static final Integer ACCOUNT_MONTHS = 10001;
    private static final Integer FORECAST_MONTHS = 8;
    private static final Integer FORECAST_MIN_VALUE = 800;
    private static final Integer FORECAST_MAX_VALUE = 1000;
    private static final Integer DISPATCH_MONTHS = 8;

    @isTest static void itShouldDispatchStagingHandler() {

        // Use Test Data Factory to create Account and related records
        List<Account> accountList = TestDataFactory.createAccountsWithMonths(1, ACCOUNT_MONTHS);
        String accountNumber = accountList[0].SAP_Account_Number__c;

        // Create forecast and dispatch staging records
        List<Forecast__c> forecastList = TestDataFactory.createForecasts(FORECAST_MONTHS, accountNumber, FORECAST_MIN_VALUE, FORECAST_MAX_VALUE);
        
        
        List<Month__c> mList = [SELECT Id from Month__c LIMIT 2];
        delete mList;
        
        List<Dispatch_Staging__c> dispatchStagingList = TestDataFactory.createDispatchStaging(DISPATCH_MONTHS, accountNumber, HAULIER_NUM, NUM_BOTTLES, NUM_TONNES);
        for (Dispatch_Staging__c ds : dispatchStagingList) {
            
            ds.Dispatch_ID__c = '0009991';
            ds.Haulier_Code__c = '0';
            ds.SAP_Material_Code__c = 'xxyy' + ds.Dispatch_ID__c;
            ds.Dispatch_Time__c = '11:00:00';
        }
        update dispatchStagingList;

        // Start test
        Test.startTest();
        DispatchStagingHandler dispatchStagingHandler = new DispatchStagingHandler();
        dispatchStagingHandler.handleSpuriousDups(dispatchStagingList);
        Test.stopTest();
        

        // Retrieve counts for assertions
        Integer haulierCount = [SELECT COUNT() FROM Haulier__c];

        // Assertion
        System.assertEquals(0, haulierCount, 'Haulier count mismatch');
    }
}