force-app/main/default/objects/Account/fields/OM_VID_SalesOrganizations__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_SalesOrganizations__c</fullName>
    <label>Sales Organizations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VD10</fullName>
            </value>
            <value>
                <fullName>VD50</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customers.recordType-meta.xml
<RecordType>
    <fullName>Customers</fullName>
    <active>true</active>
    <description>Past or Present</description>
    <label>Customers</label>
</RecordType>

force-app/main/default/objects/Bottle__c/Bottle__c.object-meta.xml
<CustomObject>
    <description>Unique Product Identifiers and Descriptions</description>
    <label>Bottle</label>
    <nameField>
        <label>Bottle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bottle__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <description>Product Code</description>
    <externalId>true</externalId>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>Bottle Identifier</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <label>SAP Material Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/Weight_per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Weight_per_Unit__c</fullName>
    <description>Weight per unit in grams</description>
    <label>Weight per Unit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OM_Product_Code_SIP__c.field-meta.xml
<CustomField>
    <fullName>OM_Product_Code_SIP__c</fullName>
    <externalId>true</externalId>
    <label>Product Code SIP</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/SAP_Material_Code__c.object-meta.xml
<CustomObject>
    <label>SAP Material Code</label>
    <nameField>
        <label>SAP Material Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Material Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Material_Code__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <label>Bottle</label>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>SAP Material Codes</relationshipLabel>
    <relationshipName>SAP_Material_Codes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <label>Bottle Identifier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/OM_ProductRef__c.field-meta.xml
<CustomField>
    <fullName>OM_ProductRef__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SAP Material Codes</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OM_VID_VentasAbonosTableController_Test.cls
@isTest
private class OM_VID_VentasAbonosTableController_Test {

    
    @testSetup
	static void isData() {
    
        Id customerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customers').getRecordTypeId();

    	Account acc = new Account(
        Name = 'Test Account',
        SAP_Account_Number__c = '11268',
        RecordTypeId = customerRecordTypeId,
        OM_VID_SalesOrganizations__c = 'VD10' 
    );
    insert acc;
}

    @isTest
    static void testGetOrderReasonValues() {
        List<Map<String, String>> values = OM_VID_VentasAbonosTableController.getOrderReasonValues('Account', 'Type');
        System.assertNotEquals(null, values);
    }

    @isTest
    static void testGetModelValues() {
        List<Map<String, String>> values = OM_VID_VentasAbonosTableController.getModelValues('Account', 'Type');
        System.assertNotEquals(null, values);
    }

    @isTest
    static void testGetMaterials() {
        Product2 prod = new Product2(Name='Test Product', ProductCode='P123');
        insert prod;
        
		Bottle__c  bottle = new Bottle__c(Bottle_Identifier__c  = 'A', Name='test', Weight_per_Unit__c = 1.00 );
        insert bottle;        

        SAP_Material_Code__c material = new SAP_Material_Code__c(Bottle__c = bottle.id, Name='MAT-001', OM_ProductRef__c=prod.Id);
        insert material;

        List<String> materials = OM_VID_VentasAbonosTableController.getMaterials(prod.Id);
        System.assertEquals(1, materials.size());
        System.assertEquals('MAT-001', materials[0]);
    }

    @isTest
    static void testGetProductCode() {
        Product2 prod = new Product2(Name='Product X', OM_Product_Code_SIP__c='CODE456');
        insert prod;

        Product2 result = OM_VID_VentasAbonosTableController.getProductCode(prod.Id);
        System.assertEquals('CODE456', result.OM_Product_Code_SIP__c);
    }

    @isTest
    static void testGetAccountCode() {
        Account account = [SELECT Id, Name, SAP_Account_Number__c FROM Account WHERE SAP_Account_Number__c = '11268' LIMIT 1];

        Account result = OM_VID_VentasAbonosTableController.getAccountCode(account.Id);
        System.assertEquals('11268', result.SAP_Account_Number__c);
    }

    @isTest
    static void testMakeBWVACallout() {
        Test.setMock(WebServiceMock.class, new OM_SapFunctionsMockAbonosDev_Test());
        Test.startTest();
        OM_VID_VentasAbonosTableController.makeBWVACallout(
            '2024','2024','01','01','C001','S001',
            new List<String>{'R1'}, 'ModelX', 'M001', 'B001'
        );
        Test.stopTest();
    }

      @isTest
    static void testGetTableData() {
        // Mock necesario si el método hace un callout real
        Test.setMock(WebServiceMock.class, new OM_SapFunctionsMockAbonosDev_Test());

        Test.startTest();
        OM_VID_VentasAbonosTableController.TableWrapper result =
            OM_VID_VentasAbonosTableController.getTableData(
                '2024', '2024', '01', '12',
                'CUST001', 'ADDR001',
                new List<String>{'R1'}, 'ModelX', 'MAT001', 'B001'
            );
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result.tableData);
        System.assert(result.tableData.size() > 0, 'Se esperaban datos en tableData');
    }
    
    
}