force-app/main/default/objects/Account/fields/OM_VID_AgreedTerms__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_AgreedTerms__c</fullName>
    <label>Agreed Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZD</fullName>
                <label>Daily Invoicing</label>
            </value>
            <value>
                <fullName>ZM</fullName>
                <label>Monthly Invoicing</label>
            </value>
            <value>
                <fullName>ZQ</fullName>
                <label>Bi-weekly invoicing</label>
            </value>
            <value>
                <fullName>ZS</fullName>
                <label>Weekly invoicing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_PaymentMethods__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_PaymentMethods__c</fullName>
    <label>Payment Methods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Immediate payment without deduction</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Cash against documents</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Documentary remittance to 60 days against delivery</label>
            </value>
            <value>
                <fullName>AF00</fullName>
                <label>C. conf al contado</label>
            </value>
            <value>
                <fullName>AF15</fullName>
                <label>C. conf a 15 días</label>
            </value>
            <value>
                <fullName>AF30</fullName>
                <label>C. conf a 30 días</label>
            </value>
            <value>
                <fullName>AF35</fullName>
                <label>C. conf a 35 días</label>
            </value>
            <value>
                <fullName>AF3B</fullName>
                <label>C. conf a 30 días (20)</label>
            </value>
            <value>
                <fullName>AF3C</fullName>
                <label>C. conf a 30 días (15)</label>
            </value>
            <value>
                <fullName>AF4A</fullName>
                <label>C. conf a 45 días (30)</label>
            </value>
            <value>
                <fullName>AF4B</fullName>
                <label>C. conf a 45 días (10,25)</label>
            </value>
            <value>
                <fullName>AF5B</fullName>
                <label>C. conf a 55 días (30)</label>
            </value>
            <value>
                <fullName>AF60</fullName>
                <label>C. conf a 60 días</label>
            </value>
            <value>
                <fullName>AF6A</fullName>
                <label>C. conf a 60 días (1,15)</label>
            </value>
            <value>
                <fullName>AF6B</fullName>
                <label>C. conf a 60 días (15)</label>
            </value>
            <value>
                <fullName>AF6C</fullName>
                <label>C. conf a 60 días (15,30)</label>
            </value>
            <value>
                <fullName>AF6D</fullName>
                <label>C. conf a 60 días (25)</label>
            </value>
            <value>
                <fullName>AF6E</fullName>
                <label>C. conf a 60 días (10,20,30)</label>
            </value>
            <value>
                <fullName>AF6F</fullName>
                <label>C. conf a 60 días (10,25)</label>
            </value>
            <value>
                <fullName>AF6G</fullName>
                <label>C. conf a 60 días (10)</label>
            </value>
            <value>
                <fullName>AF6I</fullName>
                <label>C. conf a 65 días (25)</label>
            </value>
            <value>
                <fullName>AF6J</fullName>
                <label>C. conf a 60 días (12,27)</label>
            </value>
            <value>
                <fullName>AF6K</fullName>
                <label>C. conf a 60 días (12,26)</label>
            </value>
            <value>
                <fullName>AF6L</fullName>
                <label>C. conf a 60 días (20)</label>
            </value>
            <value>
                <fullName>AF6M</fullName>
                <label>C. conf a 60 días (5,20)</label>
            </value>
            <value>
                <fullName>AF6N</fullName>
                <label>Confirminf a 60 días, día fijo 30</label>
            </value>
            <value>
                <fullName>AF6O</fullName>
                <label>C. conf a 60 días (17)</label>
            </value>
            <value>
                <fullName>AF70</fullName>
                <label>C. conf a 70 días</label>
            </value>
            <value>
                <fullName>AF75</fullName>
                <label>C. conf a 75 días (5,15,25)</label>
            </value>
            <value>
                <fullName>AF7A</fullName>
                <label>C. conf a 75 días (5,20)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OM_VID_SalesOrganizations__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_SalesOrganizations__c</fullName>
    <label>Sales Organizations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VD10</fullName>
            </value>
            <value>
                <fullName>VD50</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customers.recordType-meta.xml
<RecordType>
    <fullName>Customers</fullName>
    <active>true</active>
    <description>Past or Present</description>
    <label>Customers</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/OM_VID_Idioma__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Español</fullName>
            </value>
            <value>
                <fullName>Portugués</fullName>
            </value>
            <value>
                <fullName>Francés</fullName>
            </value>
            <value>
                <fullName>Inglés</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/OM_VID_AgreedTerms__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_AgreedTerms__c</fullName>
    <description>Shows Related Account&apos;s agreed terms</description>
    <formula>TEXT( Opportunity.Account.OM_VID_AgreedTerms__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Agreed terms de la cuenta relacionada</inlineHelpText>
    <label>Agreed Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OM_VID_DetallesAdicionales__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_DetallesAdicionales__c</fullName>
    <label>Detalles Adicionales</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OM_VID_Idioma__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Idioma__c</fullName>
    <description>Guarda el valor del campo Idioma de la Oportunidad relacionada</description>
    <formula>TEXT(Opportunity.OM_VID_Idioma__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Fórmula que guarda el valor del idioma de la Oportunidad relacionada</inlineHelpText>
    <label>Idioma</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OM_VID_Oferta_Enviada__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Oferta_Enviada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oferta Enviada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OM_VID_QuoteTRGHandlerMethods_Test.cls
@isTest
public class OM_VID_QuoteTRGHandlerMethods_Test {
    
    @isTest
    static void quoteFieldsTranslation(){
        
       
        
        Id standardPBId = Test.getStandardPricebookId();
        
        Id customerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customers').getRecordTypeId();

        Account acc = new Account(
        Name = 'Test Account',
        SAP_Account_Number__c = '11268',
        RecordTypeId = customerRecordTypeId,
        OM_VID_SalesOrganizations__c = 'VD10',
        OM_VID_AgreedTerms__c = 'ZD',
        OM_VID_PaymentMethods__c = 'AF6C' 
    );
    	insert acc;

        Product2 prod = new Product2(Name = 'Test Product', IsActive = true);
        insert prod;

        PricebookEntry standardEntry = new PricebookEntry(
            Pricebook2Id = standardPBId,
            Product2Id = prod.Id,
            UnitPrice = 100,
            IsActive = true,
            UseStandardPrice = false
        );
        insert standardEntry;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Introduction',
            CloseDate = Date.today().addDays(10),
            OM_VID_Idioma__c = 'Español',
            AccountId = acc.Id
        );
        insert opp;
        
        opp.StageName = 'Quotation';
        update opp;

        OpportunityLineItem oppLine = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Quantity = 1,
            PricebookEntryId = standardEntry.Id,
            UnitPrice = 100
        );
        insert oppLine;
        
        String QuoteRTFiftyId = [SELECT Id FROM RecordType WHERE SObjectType = :OM_VID_Constants.quoteName AND DeveloperName = :OM_VID_Constants.quoteRTFifty LIMIT 1].Id; 
        
        Quote q = new Quote(
        Name = 'test',
        OpportunityId = opp.Id,
        RecordTypeId = QuoteRTFiftyId,
        ExpirationDate = Date.today() + 30,
        OM_VID_DetallesAdicionales__c = opp.Description
        );
            
        OM_Utils.shouldSkipTriggerGlobal = false;
        
        Test.startTest();
        insert q;
        Test.stopTest();
	}
    
    @isTest 
    static void testByPassApexFlag() {
    
    OM_VID_QuoteTRGHandler.setbyPassApex(true);
    System.assertEquals(true, OM_VID_QuoteTRGHandler.getbyPassApex());

    
    OM_VID_QuoteTRGHandler.execute(
        new List<Quote>(), 
        new Map<Id, Quote>(),
        true,  
        false, 
        true,  
        false, 
        false  
    );

    OM_VID_QuoteTRGHandler.setbyPassApex(false);
    System.assertEquals(false, OM_VID_QuoteTRGHandler.getbyPassApex());
	}
    
    @isTest
    static void testCloseTasks() {

        Account acc = new Account(
            Name = 'Test Account',
            SAP_Account_Number__c = '11268'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Introduction',
            CloseDate = Date.today().addDays(30),
            AccountId = acc.Id
        );
        insert opp;

        Task task = new Task(
            Subject = OM_VID_Constants.taskSubjectSendQuotation,
            Status = 'Open',
            WhatId = opp.Id
        );
        insert task;

        Quote quote = new Quote(
            Name = 'Test Quote',
            OpportunityId = opp.Id,
            OM_VID_Oferta_Enviada__c = false
        );
        insert quote;

        quote.OM_VID_Oferta_Enviada__c = true;
        update quote;

        Map<Id, Quote> oldMap = new Map<Id, Quote>{ quote.Id => quote };
        List<Quote> newQuotes = new List<Quote>{ quote };

        Test.startTest();
        OM_VID_QuoteTRGHandlerMethods.closeTasks(newQuotes, oldMap);
        Test.stopTest();

        Task tUpdated = [SELECT Status FROM Task WHERE Id = :task.Id];
        System.assertEquals(OM_VID_Constants.taskStatusCompleted, tUpdated.Status, 'El Task debe haberse cerrado');
    }
}