force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bottle__c/Bottle__c.object-meta.xml
<CustomObject>
    <description>Unique Product Identifiers and Descriptions</description>
    <label>Bottle</label>
    <nameField>
        <label>Bottle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bottle__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <description>Product Code</description>
    <externalId>true</externalId>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>Bottle Identifier</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dispatch__c/Dispatch__c.object-meta.xml
<CustomObject>
    <description>Dispatch records created by the daily batch load</description>
    <label>Dispatch</label>
    <nameField>
        <label>Dispatch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispatches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Reference to Bottle Description</description>
    <label>Bottle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bottle__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <formula>Bottle__r.Bottle_Identifier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bottle Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Month__c</fullName>
    <formula>TEXT(Month__r.Calendar_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calendar Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Dispatch_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Date__c</fullName>
    <description>Date of the dispatch</description>
    <label>Dispatch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Dispatch_ID__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_ID__c</fullName>
    <description>Semi-unique identifier of Dispatch; requires the addition of Pack Specification to make it unique</description>
    <externalId>true</externalId>
    <label>Dispatch ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <description>Delivery forecast by account, month and product</description>
    <label>Forecast</label>
    <referenceTo>Forecast__c</referenceTo>
    <relationshipLabel>Dispatches</relationshipLabel>
    <relationshipName>Dispatches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Planned_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Delivery_Date__c</fullName>
    <label>Planned Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Tonnage__c.field-meta.xml
<CustomField>
    <fullName>Tonnage__c</fullName>
    <description>Weight of dispatch in tonnes</description>
    <inlineHelpText>Weight of dispatch in tonnes</inlineHelpText>
    <label>Tonnage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>Unique combination of Dispatch ID and Pack Specification</description>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dispatch__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>Quantity of units in thousands</description>
    <inlineHelpText>Quantity of units in Thousands</inlineHelpText>
    <label>Units</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <description>Delivery Forecasts by Account, Month and Product (Bottle)</description>
    <label>Forecast</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Month__c</fullName>
    <formula>TEXT(Month__r.Calendar_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calendar Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Forecast</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Product this Forecast refers to</description>
    <label>Product</label>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>Month__r.Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Late_Load__c/Late_Load__c.object-meta.xml
<CustomObject>
    <description>Process Improvement Reporting which contains Early Loads, Late Loads, Collapsed Loads and Health and Safety Issues.</description>
    <label>PIR</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PIR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Late_Load__c/fields/Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Month__c</fullName>
    <formula>TEXT(Dispatch__r.Month__r.Calendar_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calendar Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Late_Load__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>(Early or) Late Loads</relationshipLabel>
    <relationshipName>Early_or_Late_Loads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Late_Load__c/fields/Dispatch__c.field-meta.xml
<CustomField>
    <fullName>Dispatch__c</fullName>
    <label>Dispatch</label>
    <referenceTo>Dispatch__c</referenceTo>
    <relationshipLabel>(Early or) Late Loads</relationshipLabel>
    <relationshipName>Late_Loads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Late_Load__c/fields/Dispatch_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Date__c</fullName>
    <formula>Dispatch__r.Dispatch_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dispatch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Late_Load__c/fields/New_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>New_Delivery_Date__c</fullName>
    <description>New Delivery Date resulting from Early or Late Load</description>
    <inlineHelpText>New Delivery Date resulting from Early or Late Load</inlineHelpText>
    <label>New Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Late_Load__c/fields/Planned_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Delivery_Date__c</fullName>
    <formula>Dispatch__r.Planned_Delivery_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Planned Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Late_Load__c/fields/Reason_for_Delay__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Delay__c</fullName>
    <description>Reason for Late Delivery</description>
    <label>Reason for Delay</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Traffic</fullName>
            </value>
            <value>
                <fullName>Haulier - Planning</fullName>
            </value>
            <value>
                <fullName>Haulier - Breakdown</fullName>
            </value>
            <value>
                <fullName>Haulier - Driver Error</fullName>
            </value>
            <value>
                <fullName>Haulier - Driver Hours</fullName>
            </value>
            <value>
                <fullName>Encirc - Stock Availability</fullName>
            </value>
            <value>
                <fullName>Encirc - System Issues</fullName>
            </value>
            <value>
                <fullName>Encirc - Stock Issues</fullName>
            </value>
            <value>
                <fullName>Encirc - Loading Delay</fullName>
            </value>
            <value>
                <fullName>Encirc - Planning</fullName>
            </value>
            <value>
                <fullName>Customer - Planning</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Breakdown</fullName>
                <isActive>false</isActive>
                <label>Breakdown</label>
            </value>
            <value>
                <fullName>Delays at loading point</fullName>
                <isActive>false</isActive>
                <label>Delays at loading point</label>
            </value>
            <value>
                <fullName>Driver Called in Sick</fullName>
                <isActive>false</isActive>
                <label>Driver Called in Sick</label>
            </value>
            <value>
                <fullName>Driver held up at previous drop</fullName>
                <isActive>false</isActive>
                <label>Driver held up at previous drop</label>
            </value>
            <value>
                <fullName>Driver held up looking for correct address</fullName>
                <isActive>false</isActive>
                <label>Driver held up looking for correct address</label>
            </value>
            <value>
                <fullName>Driver issues</fullName>
                <isActive>false</isActive>
                <label>Driver issues</label>
            </value>
            <value>
                <fullName>Driver stuck in motorway traffic</fullName>
                <isActive>false</isActive>
                <label>Driver stuck in motorway traffic</label>
            </value>
            <value>
                <fullName>Driving Hours</fullName>
                <isActive>false</isActive>
                <label>Driving Hours</label>
            </value>
            <value>
                <fullName>External warehouse issues</fullName>
                <isActive>false</isActive>
                <label>External warehouse issues</label>
            </value>
            <value>
                <fullName>Ferry Issues</fullName>
                <isActive>false</isActive>
                <label>Ferry Issues</label>
            </value>
            <value>
                <fullName>Haulier did not book the load</fullName>
                <isActive>false</isActive>
                <label>Haulier did not book the load</label>
            </value>
            <value>
                <fullName>Haulier did not make changes to the load</fullName>
                <isActive>false</isActive>
                <label>Haulier did not make changes to the load</label>
            </value>
            <value>
                <fullName>Load involved in Traffic accident</fullName>
                <isActive>false</isActive>
                <label>Load involved in Traffic accident</label>
            </value>
            <value>
                <fullName>Mix up with load references</fullName>
                <isActive>false</isActive>
                <label>Mix up with load references</label>
            </value>
            <value>
                <fullName>Stock not released on time</fullName>
                <isActive>false</isActive>
                <label>Stock not released on time</label>
            </value>
            <value>
                <fullName>Wrong load sent in</fullName>
                <isActive>false</isActive>
                <label>Wrong load sent in</label>
            </value>
            <value>
                <fullName>Wrong type of trailer sent in</fullName>
                <isActive>false</isActive>
                <label>Wrong type of trailer sent in</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Late_Load__c/recordTypes/Collapsed_Load.recordType-meta.xml
<RecordType>
    <fullName>Collapsed_Load</fullName>
    <active>true</active>
    <description>Load collapsed on delivery</description>
    <label>Collapsed Load</label>
</RecordType>

force-app/main/default/objects/Late_Load__c/recordTypes/Early_Load.recordType-meta.xml
<RecordType>
    <fullName>Early_Load</fullName>
    <active>true</active>
    <description>Delivery early and not collapsed</description>
    <label>Early Load</label>
</RecordType>

force-app/main/default/objects/Late_Load__c/recordTypes/Late_Load.recordType-meta.xml
<RecordType>
    <fullName>Late_Load</fullName>
    <active>true</active>
    <description>Delivery late but not collapsed</description>
    <label>Late Load</label>
</RecordType>

force-app/main/default/classes/TestApexControllers.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        TestApexControllers.cls
   Description: Test Visualforece Page Controllers
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Dec 2017     1.0     M.Witchalls(Ciber)  Initial Release 
------------------------------------------------------------------------------------------------------------------------ */        
@isTest
private class TestApexControllers { 
    private static String lateRecordType = 'Late_Load';
    private static String earlyRecordType = 'Early_Load';
    private static String collapsedRecordType = 'Collapsed_Load';
    
    @testSetup static void setup() {
        // create one Account
        List<Account> aList = TestDataFactory.createAccountsWithMonths(1, 10001);
        String acctNum = aList[0].SAP_Account_Number__c;
        ID accountId = aList[0].Id;
   
        // create 12 Forecasts
        List<Forecast__c> fList = TestDataFactory.createForecasts(1, acctNum, 800, 1000);
        // Create a dispatch record for the current month
        Integer i = System.today().month() - 1;
        List<Dispatch__c> dispatches = TestDataFactory.createDispatches(1, accountId, fList[i], 500); 
    }    
    
    @isTest static void testNewLateLoad() {
        // Fetch a dispatch record
        Dispatch__c d = [
            SELECT Id, Name, Customer__c, Bottle__c, Dispatch_ID__c, Unique_ID__c, Year__c, Calendar_Month__c, Bottle_Identifier__c, 
                Dispatch_Date__c, Planned_Delivery_Date__c, Units__c, Tonnage__c
            FROM Dispatch__c LIMIT 1
        ];

        Schema.DescribeFieldResult fr = Schema.SObjectType.Late_Load__c.fields.Reason_for_Delay__c;
        String reason = fr.getPickListValues()[0].getValue();
        
        PageReference pageRef = Page.NewLateLoad;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', d.Id);
       
        ApexPages.StandardController stdcon = new ApexPages.StandardController(d);
        NewLateLoadExtensionController con = new NewLateLoadExtensionController(stdcon);
        con.getReadOnlyFields();
        con.getLateLoadFields();
        con.getEarlyLoadFields();
        con.getCollapsedLoadFields();
        con.getCustomerInformedFields();
        con.getLinesDownFields();
        con.getReplacementFields();
        
        con.load.New_Delivery_Date__c = d.Planned_Delivery_Date__c + 1;
        con.load.Reason_for_Delay__c = reason;
        con.save();
        
        con.replacementChange();
        con.customerInformedChange();
        con.linesDownChange();
    }
    
    @isTest static void testNewLateLoadOverride() {   
        PageReference pageRef = Page.NewLateLoadOverride;
        Test.setCurrentPage(pageRef);
       
        ApexPages.StandardController stdcon = new ApexPages.StandardController(new Late_Load__c());
        NewLateLoadOverrideExtension con = new NewLateLoadOverrideExtension(stdcon);
        con.abortAction();
        con.cancel();
    }
    
    @isTest static void testNewMonthForecastForYear() {   
        PageReference pageRef = Page.NewMonthForecastForYear;
        Test.setCurrentPage(pageRef);
        Account a = [SELECT Id, SAP_Account_Number__c FROM Account LIMIT 1];
        ApexPages.currentPage().getParameters().put('id', a.Id); 
              
        ApexPages.StandardController stdcon = new ApexPages.StandardController(a);
        NewMonthForecastExtensionController con = new NewMonthForecastExtensionController(stdcon);
        con.isUK = TRUE;
        con.isItaly = TRUE;
        con.isSpain = TRUE;
        con.check();
        con.contin();
    }
    
    @isTest static void testMonthForecastList() {   
        PageReference pageRef = Page.MonthForecastList;
        Test.setCurrentPage(pageRef);
        Account a = [SELECT Id, SAP_Account_Number__c FROM Account LIMIT 1];
        ApexPages.currentPage().getParameters().put('id', a.Id); 
              
        ApexPages.StandardController stdcon = new ApexPages.StandardController(a);
        MonthForecastListController con = new MonthForecastListController(stdcon);
        con.getRecords();
    }
    
    @isTest static void testProductForecastList() {     
        Account a = [select Id, SAP_Account_Number__c from Account];    
        PageReference pageRef = Page.ProductForecastUnits;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('customerNo', a.SAP_Account_Number__c);
        
        ProductForecastListController con = new ProductForecastListController();
        ApexPages.StandardSetController setCon = con.setCon;  
        con.getRecords();
        con.getTotals();      
    }
    
    @isTest static void testDailyComparatives() {       
        DailyComparativesComponentController con = new DailyComparativesComponentController();
        con.getUnits();
        con.getTonnage();     
    }
    
    @isTest static void testDailyOTIF() {       
        // Fetch a dispatch record
        Dispatch__c d = [ 
            SELECT Id, Name, Customer__c, Bottle__c, Dispatch_ID__c, Unique_ID__c, Year__c, Calendar_Month__c, Bottle_Identifier__c, 
                Dispatch_Date__c, Planned_Delivery_Date__c, Units__c, Tonnage__c
            FROM Dispatch__c LIMIT 1
        ];

        Schema.DescribeFieldResult fr = Schema.SObjectType.Late_Load__c.fields.Reason_for_Delay__c;
        String reason = fr.getPickListValues()[0].getValue();
        String objectName = Schema.SObjectType.Late_Load__c.Name;
        RecordType rtll = [SELECT Id FROM RecordType WHERE SObjectType = :objectName AND DeveloperName = :lateRecordType];
        RecordType rtel = [SELECT Id FROM RecordType WHERE SObjectType = :objectName AND DeveloperName = :earlyRecordType];
        RecordType rtcl = [SELECT Id FROM RecordType WHERE SObjectType = :objectName AND DeveloperName = :collapsedRecordType];

        // Create late load records
        Late_Load__c l1 = new Late_Load__c(
            RecordTypeId = rtll.Id,
            Customer__c = d.Customer__c,
            Product__c = d.Bottle__c,
            Dispatch__c = d.Id,
            New_Delivery_Date__c = d.Planned_Delivery_Date__c.addHours(1),
            Reason_for_Delay__c = reason,
            Status__c = 'Late',
            Collapsed__c = false        
        );
        Late_Load__c l2 = new Late_Load__c(
            RecordTypeId = rtel.Id,
            Customer__c = d.Customer__c,
            Product__c = d.Bottle__c,
            Dispatch__c = d.Id,
            New_Delivery_Date__c = d.Planned_Delivery_Date__c.addHours(-1),
            Reason_for_Early_Delivery__c = reason,
            Status__c = 'Early',
            Collapsed__c = false                        
        );
        Late_Load__c l3 = new Late_Load__c(
            RecordTypeId = rtcl.Id,
            Customer__c = d.Customer__c,
            Product__c = d.Bottle__c,
            Dispatch__c = d.Id,
            New_Delivery_Date__c = d.Planned_Delivery_Date__c,
            Status__c = 'On Time',
            Collapsed__c = true     
        );
        insert new List<Late_Load__c>{l1,l2,l3};        
        
        DailyOTIFComponentController con = new DailyOTIFComponentController();
        con.getRecords();
        con.getLast48hourLateReportLink();
        con.getLast48hourEarlyReportLink();
        con.getLast48hourCollapsedReportLink();
        con.getLateLoadReportLink();
        con.getEarlyLoadReportLink();
        con.getCollapsedLoadReportLink();
    }
    
}