force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Fifty Annual budget details</description>
    <label>Budget</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>This is the month in figures</description>
    <label>Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <description>Delivery Forecasts by Account, Month and Product (Bottle)</description>
    <label>Forecast</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Budget_Tonnage__c.field-meta.xml
<CustomField>
    <fullName>Budget_Tonnage__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Updated by workflow from Budget Units</description>
    <label>Budget Tonnage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Forecast</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Forecast_Tonnage__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Tonnage__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Updated by workflow from Forecast Units</description>
    <label>Forecast Tonnage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Is_Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Month__c</fullName>
    <formula>Month__r.Is_Current_Month__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Current Month?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>Forecast at Month level within Account</description>
    <label>Month</label>
    <referenceTo>Month__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>Month__r.Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Month__c/Month__c.object-meta.xml
<CustomObject>
    <description>Delivery Budgets and Forecasts by Account and Month</description>
    <label>Month Forecast</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <summarizedField>Forecast__c.Budget__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Budget_Tonnage__c.field-meta.xml
<CustomField>
    <fullName>Budget_Tonnage__c</fullName>
    <label>T Budget</label>
    <summarizedField>Forecast__c.Budget_Tonnage__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to related customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Months</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/First_Monday_of_Month__c.field-meta.xml
<CustomField>
    <fullName>First_Monday_of_Month__c</fullName>
    <description>Date of first Monday of month (could be in previous month)</description>
    <formula>DATE(VALUE(Year__c), VALUE(RIGHT(Unique_ID__c,2)), 1) +
  CASE(MOD(DATE(VALUE(Year__c), VALUE(RIGHT(Unique_ID__c,2)), 1) - DATE(2000, 1, 3), 7),
    1, -1,
    2, -2,
    3, -3,
    4, -4,
    5, -5,
    6, -6,
    0
  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Monday of Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast</label>
    <summarizedField>Forecast__c.Forecast__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Forecast_Tonnage__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Tonnage__c</fullName>
    <label>T Forecast</label>
    <summarizedField>Forecast__c.Forecast_Tonnage__c</summarizedField>
    <summaryForeignKey>Forecast__c.Month__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Is_Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Month__c</fullName>
    <description>Is the month of the year equal to yesterday&apos;s month of the year?</description>
    <formula>IF($Setup.Current_Month__c.Month__c &gt; 0,
  AND(
    VALUE(Month_Number__c) == $Setup.Current_Month__c.Month__c,
    VALUE(Year__c) == $Setup.Current_Month__c.Year__c
  ),
  AND(
    VALUE(Month_Number__c) == MONTH(TODAY() - 1),
    VALUE(Year__c) == YEAR(TODAY() -1)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Current Month?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Sales_Organization_Text__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization_Text__c</fullName>
    <formula>CASE(
 TEXT(Sales_Organization__c ),
 &quot;EN60&quot;,&quot;UK&quot;,
 &quot;VD30&quot;,&quot;Italy&quot;,
 &quot;VD10&quot;,&quot;Spain&quot;,
 &quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>Utilised for the daily load process</description>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <customValue>
        <fullName>2032</fullName>
    </customValue>
    <customValue>
        <fullName>2033</fullName>
    </customValue>
    <customValue>
        <fullName>2034</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/MonthForecastListController.cls
/* ---------------------------------------------------------------------------------------------------------------
   Name:        MonthForecastListController.cls
   Description: Controller Class for MonthForecastList Page
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ----------------------------------------------------------------------
   Mar 2017     1.0     Michael Witchalls   Initial Release 
   Sep 2024     1.1     Globant             Code Refactoring and Added Comments
------------------------------------------------------------------------------------------------------------------ */        
   
public with sharing class MonthForecastListController {

    private static final Integer PAGESIZE = 24;
    
    public Account theAccount {get; set;}
    public String accountId {get; set;}
    
    // Filter picklist
    public List<SelectOption> statusSelectList {get; set;}
    
    /**
     * Constructor for MonthForecastListController.
     * Initializes the account details based on the provided account ID.
     * 
     * @param stdController - The standard controller instance for the page.
     */
    public MonthForecastListController(ApexPages.StandardController stdController) {

        accountId = ApexPages.currentPage().getParameters().get('id');
        
        if (String.isBlank(accountId)) {

            return;
        }

        theAccount = [SELECT Id, Name, SAP_Account_Number__c FROM Account WHERE Id = :accountId LIMIT 1];
    }   
     

    /**
     * Retrieves an instance of ApexPages.StandardSetController for handling pagination and record retrieval.
     * 
     * @return ApexPages.StandardSetController - Controller for managing and displaying month forecast records.
     */
    public ApexPages.StandardSetController monthSetController {
        get{
            if (String.isBlank(accountId)) {

                return null;
            }

            if (monthSetController == null) {

                String currentYear = String.valueOf(System.today().year());
                monthSetController = new ApexPages.StandardSetController(
                    Database.getQueryLocator([
                        SELECT 
                            Id, Name, Sales_Organization_Text__c, Year__c, Budget__c, Forecast__c, Budget_Tonnage__c, Forecast_Tonnage__c, OwnerId
                        FROM 
                            Month__c 
                        WHERE 
                            Customer__c = :accountId
                            AND Year__c = :currentYear
                            AND First_Monday_of_Month__c <= :System.today()
                            AND Is_Current_Month__c = TRUE
                        ORDER BY Unique_ID__c DESC
                        LIMIT 24
                    ])
                );
                monthSetController.setPageSize(PAGESIZE);
            }
            return monthSetController;
        } private set;
    }
    
    /**
     * Retrieves the list of month forecast records managed by MonthSetController.
     * 
     * @return List<Month__c> - The list of Month__c records.
     */
    public List<Month__c> getRecords() {

        if (monthSetController == null) {

            return new List<Month__c>(); 
        }

        return (List<Month__c>)monthSetController.getRecords();
    }
}



// TODO remove once it has been tested/validated/QA-ed
/*public with sharing class MonthForecastListController {
    private static final Integer PAGESIZE = 24;
    
    public Account theAccount   {get; set;}
    public String accountId     {get; set;}
    
    // Filter picklist
    public List<SelectOption> statusSelectList {get; set;}
    
    public MonthForecastListController(ApexPages.StandardController stdController) {
        accountId = ApexPages.currentPage().getParameters().get('id');
        theAccount = [select Id, Name, SAP_Account_Number__c from Account where Id = :accountId];       
    }   
     
    public ApexPages.StandardSetController MonthSetController {
        get {
            String currentYear = String.valueOf(System.today().year());
            if(MonthSetController == null) {
                MonthSetController = new ApexPages.StandardSetController(
                    Database.getQueryLocator([
                        SELECT 
                            Id, Name, Sales_Organization_Text__c, Year__c, Budget__c, Forecast__c, Budget_Tonnage__c, Forecast_Tonnage__c, OwnerId
                        FROM 
                            Month__c 
                        WHERE 
                            Customer__c = :accountId
                            AND Year__c = :currentYear
                            AND First_Monday_of_Month__c <= :System.today()
                            AND Is_Current_Month__c = TRUE
                        ORDER BY Unique_ID__c DESC
                        LIMIT 24
                    ])
                );
            }
            MonthSetController.setPageSize(PAGESIZE);
            return MonthSetController;
        }
        private set;
    }
    
    public List<Month__c> getRecords() {
        return (List<Month__c>)MonthSetController.getRecords();
    } 
}*/