force-app/main/default/objects/Account/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <description>Account number from SAP</description>
    <externalId>true</externalId>
    <label>SAP Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/Actual_Sales_History__c.object-meta.xml
<CustomObject>
    <description>Historic report to store, display and report on historic deal summaries with customers</description>
    <label>Actual Sales History</label>
    <nameField>
        <displayFormat>Deal Summary No. {0000}</displayFormat>
        <label>Deal Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Sales History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Actual_Sales_History__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bottle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bottle__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>Actual Sales History</relationshipLabel>
    <relationshipName>Actual_Sales_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Actual_Sales_History__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SAP Material Code</label>
    <referenceTo>SAP_Material_Code__c</referenceTo>
    <relationshipLabel>Actual Sales History</relationshipLabel>
    <relationshipName>Actual_Sales_History_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bottle__c/Bottle__c.object-meta.xml
<CustomObject>
    <description>Unique Product Identifiers and Descriptions</description>
    <label>Bottle</label>
    <nameField>
        <label>Bottle Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bottle__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <description>Product Code</description>
    <externalId>true</externalId>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>Bottle Identifier</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Code__c</fullName>
    <label>SAP Material Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bottle__c/fields/Weight_per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Weight_per_Unit__c</fullName>
    <description>Weight per unit in grams</description>
    <label>Weight per Unit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OM_Product_Code_SIP__c.field-meta.xml
<CustomField>
    <fullName>OM_Product_Code_SIP__c</fullName>
    <externalId>true</externalId>
    <label>Product Code SIP</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/SAP_Material_Code__c.object-meta.xml
<CustomObject>
    <label>SAP Material Code</label>
    <nameField>
        <label>SAP Material Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Material Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Material_Code__c/fields/Bottle__c.field-meta.xml
<CustomField>
    <fullName>Bottle__c</fullName>
    <label>Bottle</label>
    <referenceTo>Bottle__c</referenceTo>
    <relationshipLabel>SAP Material Codes</relationshipLabel>
    <relationshipName>SAP_Material_Codes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/Bottle_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Bottle_Identifier__c</fullName>
    <label>Bottle Identifier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Material_Code__c/fields/Material_Code_Key__c.field-meta.xml
<CustomField>
    <fullName>Material_Code_Key__c</fullName>
    <description>Copy of SAP Material Code Name</description>
    <externalId>true</externalId>
    <label>Material Code Key</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OM_BW_InsertActualSalesHistory_Test.cls
@isTest
public class OM_BW_InsertActualSalesHistory_Test {

    @TestSetup
    static void setupData() {
        
        Account acc = new Account(Name='Test Account', SAP_Account_Number__c='12516');
        insert acc;
        
        Product2 prod = new Product2(Name='Test Product', OM_Product_Code_SIP__c='221004B');
        insert prod;
        
        Bottle__c bot = new Bottle__c(Name='Test Bottle', Bottle_Identifier__c='1', Weight_per_Unit__c=1);
        insert bot;
        
        SAP_Material_Code__c mat = new SAP_Material_Code__c(Name='Test Mat', Bottle__c=bot.Id, Material_Code_Key__c='18403');
        insert mat;
    }

    @IsTest
    static void testCreateJsonBWWrapper() {
        String jsonOutput = OM_BW_InsertActualSalesHistory.createJsonBWWrapper('2024', '2025', '01', '12', 'VD50', 'GRP1');
        System.assert(String.isNotBlank(jsonOutput), 'El JSON debería haberse generado correctamente.');
    }

    @IsTest
    static void testactualSalesHistoryCalloutBW() {
        OM_BW_Wrapper.BWFilter testFilter = new OM_BW_Wrapper.BWFilter('2024', '2025', '01', '12', 'VD50', 'GRP1');
        Test.setMock(WebServiceMock.class, new OM_SapFunctionsMockActualSalesH_Test());
        
        Test.startTest();
        try {
            OM_BW_InsertActualSalesHistory.actualSalesHistoryCalloutBW(testFilter);
            System.assert(true, 'La ejecución del callout fue exitosa.');
        } catch(Exception e) {
            System.assert(false, 'El método falló con la excepción: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    static void testInsertActualSalesHistory() {
        String jsonStr = '{"yearFrom": "2024", "yearTo": "2025", "monthFrom": "01", "monthTo": "12", "salesOrganization": "VD50"}';
        Test.setMock(WebServiceMock.class, new OM_SapFunctionsMockActualSalesH_Test());
        
        Test.startTest();
        try {
            OM_BW_InsertActualSalesHistory.insertActualSalesHistory(jsonStr);
            System.assert(true, 'El proceso de inserción se ejecutó correctamente.');
        } catch(Exception e) {
            System.assert(false, 'El proceso de inserción falló: ' + e.getMessage());
        }
        Test.stopTest();
        
        Integer created = [SELECT count() FROM Actual_Sales_History__c];
        System.debug('Registros creados en test: ' + created);
    }
}