force-app/main/default/objects/Consumer_Complaint__c/Consumer_Complaint__c.object-meta.xml
<CustomObject>
    <description>Consumer Complaints Object</description>
    <label>Consumer Complaint</label>
    <nameField>
        <label>Consumer Complaint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumer Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consumer_Complaint__c/fields/Complaint_Type_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Type_Confirmed_Date__c</fullName>
    <description>This Date field is populated when any of; 1-Manufacturing Fault Present, 2-Legal or 3-Injury have Yes selected</description>
    <label>Complaint Type Confirmed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Injury__c.field-meta.xml
<CustomField>
    <fullName>Injury__c</fullName>
    <description>Consumer Injury</description>
    <label>Injury</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Legal__c.field-meta.xml
<CustomField>
    <fullName>Legal__c</fullName>
    <label>Legal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Manufacturing_Fault_Present__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Fault_Present__c</fullName>
    <description>Is there a Manufacturing Fault Present?</description>
    <label>Manufacturing Fault Present</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumer_Complaint__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <description>The Plant related to this complaint</description>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elton</fullName>
            </value>
            <value>
                <fullName>Derrylin</fullName>
            </value>
            <value>
                <fullName>Corsico</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConsumerComplaintsHandler.cls
public with sharing class ConsumerComplaintsHandler {

    public static void evaluateRecordsInsert(List<Consumer_Complaint__c> ccs) {
        Map<String, List<Consumer_Complaint__c>> applicable = new Map<String, List<Consumer_Complaint__c>>();
        applicable.put('QD_AM', new List<Consumer_Complaint__c>());
        applicable.put('QM_Unk', new List<Consumer_Complaint__c>());
        applicable.put('QM_Elt', new List<Consumer_Complaint__c>());
        applicable.put('QM_Der', new List<Consumer_Complaint__c>());
        applicable.put('QM_Cor', new List<Consumer_Complaint__c>());

        for(Consumer_Complaint__c cc : ccs) {
            if(cc.Complaint_Type_Confirmed_Date__c != null && (cc.Manufacturing_Fault_Present__c == 'Yes' || cc.Legal__c == 'Yes' || cc.Injury__c == 'Yes')) {
                
                applicable.get('QD_AM').add(cc);

                switch on cc.Plant__c {
                    when 'Unknown' {
                        applicable.get('QM_Unk').add(cc);
                    }
                    when 'Elton' {
                        applicable.get('QM_Elt').add(cc);
                    }
                    when 'Derrylin' {
                        applicable.get('QM_Der').add(cc);
                    }
                    when 'Corsico' {
                        applicable.get('QM_Cor').add(cc);
                    }
                }
            }
        }
        if(applicable.get('QD_AM').size() > 0) {
            System.enqueueJob(new ConsumerComplaintsEmailQueue(applicable));
        }
    }

    public static void evaluateRecordsUpdate(List<Consumer_Complaint__c> ccs, Map<Id,Consumer_Complaint__c> oldCcs) {
        Map<String, List<Consumer_Complaint__c>> applicable = new Map<String, List<Consumer_Complaint__c>>();
        applicable.put('QD_AM', new List<Consumer_Complaint__c>());
        applicable.put('QM_Unk', new List<Consumer_Complaint__c>());
        applicable.put('QM_Elt', new List<Consumer_Complaint__c>());
        applicable.put('QM_Der', new List<Consumer_Complaint__c>());
        applicable.put('QM_Cor', new List<Consumer_Complaint__c>());

        for(Consumer_Complaint__c cc : ccs) {
            if(cc.Complaint_Type_Confirmed_Date__c != null 
                && oldCcs.get(cc.Id).Complaint_Type_Confirmed_Date__c != cc.Complaint_Type_Confirmed_Date__c 
                && cc.Complaint_Type_Confirmed_Date__c > System.now().addDays(-2) //remove this line for deploy
                && (cc.Manufacturing_Fault_Present__c == 'Yes' || cc.Legal__c == 'Yes' || cc.Injury__c == 'Yes')) {
                
                applicable.get('QD_AM').add(cc);

                switch on cc.Plant__c {
                    when 'Unknown' {
                        applicable.get('QM_Unk').add(cc);
                    }
                    when 'Elton' {
                        applicable.get('QM_Elt').add(cc);
                    }
                    when 'Derrylin' {
                        applicable.get('QM_Der').add(cc);
                    }
                    when 'Corsico' {
                        applicable.get('QM_Cor').add(cc);
                    }
                }
            }
        }
        if(applicable.get('QD_AM').size() > 0) {
            System.enqueueJob(new ConsumerComplaintsEmailQueue(applicable));
        }
    }
}