force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product Field That gets updated with product information</description>
    <inlineHelpText>CAMPO NO EDITABLE - RECOGE EN AUTOMATICO LOS PRODUCTOS DEL CONTACTO QUE VIENE A TRAVES DEL CATALOGO VIRTUAL. POR FAVOR NO ESCRIBIR NADA MANUALMENTE</inlineHelpText>
    <label>Product</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Volume_Pallets__c.field-meta.xml
<CustomField>
    <fullName>Volume_Pallets__c</fullName>
    <description>How many pallets</description>
    <label>Volume Pallets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Volume_Pallets_Web_Capture__c.field-meta.xml
<CustomField>
    <fullName>Volume_Pallets_Web_Capture__c</fullName>
    <description>Used to capture the number of pallets  by comma eliminated list</description>
    <label>Volume Pallets Web Capture</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Volume_Units_000__c.field-meta.xml
<CustomField>
    <fullName>Volume_Units_000__c</fullName>
    <label>Volume Units (000)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Volume_Units_Web_Capture__c.field-meta.xml
<CustomField>
    <fullName>Volume_Units_Web_Capture__c</fullName>
    <description>Comma deliminated field to capture web information  (123, 456, 789)</description>
    <label>Volume Units Web Capture</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/Lead_Product__c.object-meta.xml
<CustomObject>
    <description>A Junction Object created between to lead and product objects to capture the</description>
    <label>Lead Product</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Lead Product No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Product__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead product is seleacted on</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Products</relationshipLabel>
    <relationshipName>Lead_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Products</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lead Products</relationshipLabel>
    <relationshipName>Lead_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Volume_Pallets__c.field-meta.xml
<CustomField>
    <fullName>Volume_Pallets__c</fullName>
    <label>Volume Pallets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Volume_Units__c.field-meta.xml
<CustomField>
    <fullName>Volume_Units__c</fullName>
    <label>Volume Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadHandler.cls
/**
* @author Jamie Kennedy <jamie.kennedy@cloudshiftgroup.com>
* @date 2021-10-01
* @group CloudShiftGroup
* @description This handler class is to be used with the Lead trigger.
*
* Date              Author              Change Description
* -----------------------------------------------------------------------------------
* 2021-11-01        Jamie Kennedy      	Created Classz
**/

public class LeadHandler {

   /**
     *  @desc	To be used with the after Insert trigger, will loop through comma separated 
     * 			values and create Lead_Product__c records for each comma separated value. 	     
     *  @param  List<Lead> leadList
     *  @return void
     */
    public void processWebProducts(List<Lead> leadList) {
        
        if(leadList == null || leadList.isEmpty()) {
            return;
        }

        List<Lead> leadUpdates = new List<Lead>();
        List<Lead_Product__c> leadProductInserts = new List<Lead_Product__c>();
        
        for(Lead lead : leadList) {
            
            if (String.isBlank(lead.Product__c)) {
                continue;
            }

            List<String> lstProducts = lead?.Product__c.split(',');
            List<String> lstVolPallets = lead?.Volume_Pallets_Web_Capture__c.split(',');
            List<String> lstVolUnits = lead?.Volume_Units_Web_Capture__c.split(',');
            
            if (lstProducts.isEmpty() || lstVolPallets.isEmpty() || lstVolUnits.isEmpty() || 
                lstProducts.size() != lstVolPallets.size() || lstProducts.size() != lstVolUnits.size()) {
                continue;
            }
            
            Integer totalUnits = 0;
            Integer totalPallets = 0;
            
            Map<String, Id> productMap = new Map<String, Id>();
            
            List<Product2> allProducts = new List<Product2>([SELECT Id, ProductCode FROM Product2]);
            
            for(Product2 product : allProducts) {
                productMap.put(product.ProductCode, product.Id);
            }
            
            if(productMap.isEmpty()) {
                continue;
            }

            for(Integer i = 0; i < lstProducts.size(); i++) {
                
                if (!productMap.containsKey(lstProducts[i])) {
                    continue;
                }
                
                Lead_Product__c newLP = new Lead_Product__c(); 
                
                newLP.Lead__c = lead.Id; 
                newLP.Volume_Units__c = Integer.valueOf(lstVolUnits[i]);
                newLP.Volume_Pallets__c = Integer.valueOf(lstVolPallets[i]);
                
                newLP.Products__c = productMap.get(lstProducts[i]);
                
                totalUnits += Integer.valueOf(lstVolUnits[i]);
                totalPallets += Integer.valueOf(lstVolPallets[i]);
                
                leadProductInserts.add(newLP);
            }
            
            if (!leadProductInserts.isEmpty()) {
                leadUpdates.add(new Lead(
                    Id = lead.Id,
                    Volume_Pallets__c = totalPallets,
                    Volume_Units_000__c = totalUnits
                ));
            }
        }
        try{
            if(leadProductInserts.Size() > 0) {
            	insert leadProductInserts;
        	}           
        } catch(DmlException e){
          	throw new CustomException('Error inserting Lead_Product__c records: ' + e.getMessage());

        }
        

        try{       
            if(leadUpdates.Size() > 0) {
                update leadUpdates;
            }
        } catch(DmlException e){
            throw new CustomException('Error inserting Lead_Product__c records: ' + e.getMessage());

        }
    }
    public class CustomException extends Exception {}

}




/*public class LeadHandler {

   /**
     *  @desc	To be used with the after Insert trigger, will loop through comma seperated 
     * 			values and create Lead_Product__c records for each Comma seperated value. 	     
     *  @param  List<Lead> leadList
     *  @return void
     */
    /*public void processWebProducts(List<Lead> leadList) {
        
        List<Lead> leadUpdates = new List<Lead>();
        List<Lead_Product__c> leadProductInserts = new List<Lead_Product__c>();
        
        for(Lead lead : leadList) {
            
            if(!String.isBlank(lead.Product__c)){

                // split the input strings into lists, seperated by Comma. 
                List<String> lstProducts = lead?.Product__c.split(',');
                List<String> lstVolPallets = lead?.Volume_Pallets_Web_Capture__c.split(',');
                List<String> lstVolUnits = lead?.Volume_Units_Web_Capture__c.split(',');
                
                if(lstProducts.Size() > 0) {
                    
                    // Integers to count up our total values
                    Integer totalUnits = 0;
                    Integer totalPallets = 0;
                    
                    // creating a ProductName to Id Map so we can retrieve the Product Id. 
                    Map<String, Id> productMap = new Map<String, Id>();
                    
                    List<Product2> allProducts = new List<Product2>([SELECT Id, ProductCode FROM Product2]);
                    
                    // looping through our Product to put values into the Map.
                    for(Product2 product : allProducts) {
                        productMap.put(product.ProductCode, product.Id);
                    }
                    
                    // looping through the products list to create Lead_Product__c records. 
                    for(Integer i = 0; i < lstProducts.Size(); i++) {
                        
                        Lead_Product__c newLP = new Lead_Product__c(); 
                        
                        newLP.Lead__c = lead.Id; 
                        newLP.Volume_Units__c = Integer.ValueOf(lstVolUnits[i]);
                        newLP.Volume_Pallets__c = Integer.ValueOf(lstVolPallets[i]);
                        
                        newLP.Products__c = productMap?.get(lstProducts[i]);
                        
                        totalUnits = totalUnits + Integer.ValueOf(lstVolUnits[i]);
                        totalPallets = totalPallets + Integer.ValueOf(lstVolPallets[i]);
                        
                        leadProductInserts.add(newLP);
                    }
                    
                    if(leadProductInserts.Size() > 0) {
                        // after we've gone over our Products update the parent Lead with total values. 
                        leadUpdates.add(new Lead(
                            Id = lead.Id,
                            Volume_Pallets__c = totalPallets,
                            Volume_Units_000__c = totalUnits
                        ));
                    }
                }
            }
        }
        
        // after we've looped through all leads, update Leads and insert Lead_Product__c
        if(leadProductInserts.Size() > 0) {
            insert leadProductInserts;
        }
        if(leadUpdates.Size() > 0) {
            update leadUpdates;
        }
    }
}*/