force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product Field That gets updated with product information</description>
    <inlineHelpText>CAMPO NO EDITABLE - RECOGE EN AUTOMATICO LOS PRODUCTOS DEL CONTACTO QUE VIENE A TRAVES DEL CATALOGO VIRTUAL. POR FAVOR NO ESCRIBIR NADA MANUALMENTE</inlineHelpText>
    <label>Product</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Volume_Pallets_Web_Capture__c.field-meta.xml
<CustomField>
    <fullName>Volume_Pallets_Web_Capture__c</fullName>
    <description>Used to capture the number of pallets  by comma eliminated list</description>
    <label>Volume Pallets Web Capture</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Volume_Units_Web_Capture__c.field-meta.xml
<CustomField>
    <fullName>Volume_Units_Web_Capture__c</fullName>
    <description>Comma deliminated field to capture web information  (123, 456, 789)</description>
    <label>Volume Units Web Capture</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/Lead_Product__c.object-meta.xml
<CustomObject>
    <description>A Junction Object created between to lead and product objects to capture the</description>
    <label>Lead Product</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Lead Product No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeadHandlerTest.cls
/**
* @author Jamie Kennedy <jamie.kennedy@cloudshiftgroup.com>
* @date 2021-10-01
* @group CloudShiftGroup
* @description This handler test class for the Lead trigger.
*
* Date              Author              Change Description
* -----------------------------------------------------------------------------------
* 2021-11-01        Jamie Kennedy      	Created Class
**/


@isTest
public class LeadHandlerTest {
    
    private static Integer leadCount = 3;
    private static Integer leadProductCount = 2;
    private static Integer productsToCreate = leadCount * leadProductCount;

    @testSetup
    static void testSetup() {
        
        List<Lead> leadList = new List<Lead>();
        List<Product2> leadProduct = new List<Product2>();
             
        for(Integer i = 0; i < leadCount; i++) {
            leadList.add(new Lead(
                FirstName = 'LeadProcessWebProducts',
                LastName = 'Test: ' + i,
                Status = 'Active',
                Company = 'Test Company'
            ));
        }

        for(Integer i = 0; i < productsToCreate; i++) {
            leadProduct.add(new Product2(
                Name = 'test product name ' + i,
                ProductCode = '1123-' + i,
                Description = 'Test Item'
            ));
        }
        
        insert leadProduct;
        insert leadList;
    }
    
    @isTest
    static void testprocessWebProducts() {
        
        List<Lead> leads = [ SELECT Id, Product__c, Volume_Pallets_Web_Capture__c, Volume_Units_Web_Capture__c
                           	 FROM Lead
                           	 WHERE FirstName = 'LeadProcessWebProducts' ];
        
        List<Product2> products = [ SELECT Id, ProductCode
                                    FROM Product2 
                                    WHERE ProductCode != null ];
        Integer loopCount = 0;
        
        System.Test.startTest();
        
        for(Lead lead : leads) {
            
            lead.Product__c = '';
            lead.Volume_Pallets_Web_Capture__c = '';
            lead.Volume_Units_Web_Capture__c = '';
            
            for(Integer i = 0; i < leadProductCount; i++) {
                
                if(!(i + 1 < leadProductCount)) {
    				//last iteration
    				lead.Product__c += products[loopCount].ProductCode;
                    lead.Volume_Pallets_Web_Capture__c += i;
                    lead.Volume_Units_Web_Capture__c += loopCount;
  				}
                else {
                    lead.Product__c += products[loopCount].ProductCode + ',';
                    lead.Volume_Pallets_Web_Capture__c += i + ',';
                    lead.Volume_Units_Web_Capture__c += loopCount + ',';
                }
                
                loopcount++;
            }
        }
        
        update leads;
        
        LeadHandler testHandler = new LeadHandler();
		testHandler.processWebProducts(leads);
        
        System.Test.stopTest();
        
        List<Lead_Product__c> insertedLeadProducts = [ SELECT Id FROM Lead_Product__c ];
        
        System.assertEquals(productsToCreate, insertedLeadProducts.Size(), 'checking total lead products');
    }
}

/*@isTest
public class LeadHandlerTest {
    
    private static Integer leadCount = 3;
    private static Integer leadProductCount = 2;
    private static Integer productsToCreate = leadCount * leadProductCount;

    @testSetup
    static void testSetup() {
        
        List<Lead> leadList = new List<Lead>();
        List<Product2> leadProduct = new List<Product2>();
             
        for(Integer i = 0; i < leadCount; i++) {
            leadList.add(new Lead(
                FirstName = 'LeadProcessWebProducts',
                LastName = 'Test: ' + i,
                Status = 'Active',
                Company = 'Test Company'
            ));
        }

        for(Integer i = 0; i < productsToCreate; i++) {
            leadProduct.add(new Product2(
                Name = 'test product name ' + i,
                ProductCode = '1123-' + i,
                Description = 'Test Item'
            ));
        }
        
        insert leadProduct;
        insert leadList;
    }
    
    @isTest
    static void testprocessWebProducts() {
        
        List<Lead> leads = [ SELECT Id, Product__c, Volume_Pallets_Web_Capture__c, Volume_Units_Web_Capture__c
                           	 FROM Lead
                           	 WHERE FirstName = 'LeadProcessWebProducts' ];
        
        List<Product2> products = [ SELECT Id, ProductCode
                                    FROM Product2 
                                    WHERE ProductCode != null ];
        Integer loopCount = 0;
        
        for(Lead lead : leads) {
            
            lead.Product__c = '';
            lead.Volume_Pallets_Web_Capture__c = '';
            lead.Volume_Units_Web_Capture__c = '';
            
            for(Integer i = 0; i < leadProductCount; i++) {
                
                if(!(i + 1 < leadProductCount)) {
    				//last iteration
    				lead.Product__c += products[loopCount].ProductCode;
                    lead.Volume_Pallets_Web_Capture__c += i;
                    lead.Volume_Units_Web_Capture__c += loopCount;
  				}
                else {
                    lead.Product__c += products[loopCount].ProductCode + ',';
                    lead.Volume_Pallets_Web_Capture__c += i + ',';
                    lead.Volume_Units_Web_Capture__c += loopCount + ',';
                }
                
                loopcount++;
            }
        }
        
        update leads;
        
        LeadHandler testHandler = new LeadHandler();
		testHandler.processWebProducts(leads);
        
        List<Lead_Product__c> insertedLeadProducts = [ SELECT Id FROM Lead_Product__c ];
        
        // we should have the same amound of productsToCreate in our above SOQL
        system.assertEquals(productsToCreate, insertedLeadProducts.Size(), 'checking total lead products');
    }
}*/