force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OM_VID_Idioma__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Español</fullName>
            </value>
            <value>
                <fullName>Portugués</fullName>
            </value>
            <value>
                <fullName>Francés</fullName>
            </value>
            <value>
                <fullName>Inglés</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/OM_VID_Idioma__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Idioma__c</fullName>
    <description>Guarda el valor del campo Idioma de la Oportunidad relacionada</description>
    <formula>TEXT(Opportunity.OM_VID_Idioma__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Fórmula que guarda el valor del idioma de la Oportunidad relacionada</inlineHelpText>
    <label>Idioma</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OM_VID_EmailControllerTest.cls
/**
* @description       :
* @author            : mmadridp@omegacrmconsulting.com
* @group             :
* @last modified on  : 17-04-2024
* @last modified by  : mmadridp@omegacrmconsulting.com
**/
@isTest
public with sharing class OM_VID_EmailControllerTest {
    @TestSetup
    static void makeData(){
        OM_VID_TestUtils.createAccountsWithContacts(1);
        OM_VID_TestUtils.createQuotes(1);
    }

    @isTest
    static void sendEmailTest(){
        Contact c = [SELECT Id, Email FROM Contact LIMIT 1];
        Quote q = [SELECT Id, Opportunity.OwnerId, Name, Opportunity.Contact__c, OM_VID_Idioma__c FROM Quote LIMIT 1];
        String templateName = 'ES' + OM_VID_Constants.fiftyTemplateName;

        ContentVersion cvl = new Contentversion(); 
        cvl.Title = 'CZDSTOU'; 
        cvl.PathOnClient = 'test'; 
        cvl.VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body');
        List<ContentVersion> cvList = new List<ContentVersion>();
        cvList.add(cvl);
        insert cvList;

        Test.startTest();
        String s = OM_VID_EmailController.sendQuoteEmail(templateName, q, cvList);
        Test.stopTest();

        System.assertEquals('Ok', s, 'Esperabamos Ok pero hemos recibido un error: ' + s);
    }
}