force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OM_VID_NumQuotes__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_NumQuotes__c</fullName>
    <label>Número de ofertas</label>
    <summaryForeignKey>Quote.OpportunityId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Pallet_Volume__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Volume__c</fullName>
    <label>Pallet Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Price_Includes_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Price_Includes_Delivery__c</fullName>
    <description>Define whether the price being offered includes delivery, and if not which ex-works location the price refers to the description above is legacy this field was repurposed by Fifty there is a automation linked to it.</description>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAP</fullName>
                <default>true</default>
                <label>DAP</label>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>EX WORKS</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/OM_VID_DetallesAdicionales__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_DetallesAdicionales__c</fullName>
    <label>Detalles Adicionales</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/OM_VID_Quote_Fifty.recordType-meta.xml
<RecordType>
    <fullName>OM_VID_Quote_Fifty</fullName>
    <active>true</active>
    <description>Record Type para las Quotes de Omega</description>
    <label>OM Quote Fifty</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/OM_VID_Incoterms__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Incoterms__c</fullName>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAP</fullName>
                <default>true</default>
                <label>DAP</label>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>EX WORKS</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/OM_VID_Pallet_Volume__c.field-meta.xml
<CustomField>
    <fullName>OM_VID_Pallet_Volume__c</fullName>
    <label>Pallet Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OM_VID_GenerateOffersController.cls
public class OM_VID_GenerateOffersController {
    
    @AuraEnabled
    public static String createQuote(Id opportunityId) {
        try {
            Opportunity opp = [
                SELECT Id, Name, OM_VID_NumQuotes__c, RecordTypeId, Description, Contact__c 
                FROM Opportunity 
                WHERE Id = :opportunityId 
                LIMIT 1
            ];
            
            List<OpportunityLineItem> oppLineList = [
                SELECT Id, Quantity, PricebookEntryId, Product2Id, UnitPrice, Description, TotalPrice, OpportunityId, Price_Includes_Delivery__c, Pallet_Volume__c 
                FROM OpportunityLineItem 
                WHERE OpportunityId = :opportunityId
            ];
            
            RecordType rt = [
                SELECT Id, DeveloperName 
                FROM RecordType 
                WHERE DeveloperName = 'OM_VID_Quote_Fifty'  
                LIMIT 1
            ];
            
            Quote q = new Quote();
            q.Name = opp.Name + '_v' + opp.OM_VID_NumQuotes__c;
            q.OpportunityId = opp.Id;
            q.RecordTypeId = rt.Id;
            q.ExpirationDate = Date.today() + 30;
            q.OM_VID_DetallesAdicionales__c = opp.Description;
            q.ContactId = opp.Contact__c;
            insert q;
            
            List<QuoteLineItem> quoteLines = new List<QuoteLineItem>();
            for (OpportunityLineItem oppLine : oppLineList) {
                QuoteLineItem qLine = new QuoteLineItem();
                qLine.OpportunityLineItemId = oppLine.Id;
                qLine.QuoteId = q.Id;
                qLine.Quantity = oppLine.Quantity;
                qLine.PricebookEntryId = oppLine.PricebookEntryId;
                qLine.Product2Id = oppLine.Product2Id;
                qLine.UnitPrice = oppLine.UnitPrice;
                qLine.Description = oppLine.Description;
                qLine.OM_VID_Incoterms__c = oppLine.Price_Includes_Delivery__c;
                qLine.OM_VID_Pallet_Volume__c = oppLine.Pallet_Volume__c;
                quoteLines.add(qLine);
            }
            insert quoteLines;
            
            return 'Quote creada correctamente';
            
        } catch(Exception e) {
            throw new AuraHandledException('Error al crear la Quote: ' + e.getMessage());
        }
    }
}