force-app/main/default/objects/Forecast_Risk_Upside__c/Forecast_Risk_Upside__c.object-meta.xml
<CustomObject>
    <description>Holds risks and upsides for the monthly forecasts</description>
    <label>Forecast Risk/Upside</label>
    <nameField>
        <displayFormat>FR{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Risks/Upsides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Risk_Upside__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New - Unsubmitted</fullName>
                <default>true</default>
                <label>New - Unsubmitted</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Risk_Upside__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>lookup to month object</description>
    <label>Month</label>
    <referenceTo>Month__c</referenceTo>
    <relationshipName>Risks_Opps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Risk_Upside__c/fields/Revised_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Revised_Forecast__c</fullName>
    <formula>Month__r.Forecast__c - Risks__c + Upsides__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revised Forecast</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast_Risk_Upside__c/fields/Risks__c.field-meta.xml
<CustomField>
    <fullName>Risks__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Negative impact to forecast</description>
    <label>Risks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast_Risk_Upside__c/fields/Upsides__c.field-meta.xml
<CustomField>
    <fullName>Upsides__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Positive impact to forecast</description>
    <label>Upsides</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast_Risk_Upside__c/recordTypes/Approved_Rejected.recordType-meta.xml
<RecordType>
    <fullName>Approved_Rejected</fullName>
    <active>true</active>
    <description>Records that have been approved or rejected</description>
    <label>Approved/Rejected</label>
</RecordType>

force-app/main/default/objects/Forecast_Risk_Upside__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Records that have not yet been approved or rejected</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Month__c/Month__c.object-meta.xml
<CustomObject>
    <description>Delivery Budgets and Forecasts by Account and Month</description>
    <label>Month Forecast</label>
    <nameField>
        <label>Month Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Month__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to related customer account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Months</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Revised_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Revised_Forecast__c</fullName>
    <description>Revised forecast taking into consideration total risks and opps</description>
    <formula>Revised_Forecast_Roll_Up__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revised Forecast</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Risks__c.field-meta.xml
<CustomField>
    <fullName>Risks__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Approved Risks for this Customer and Month</description>
    <label>Risks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Month__c/fields/Upsides__c.field-meta.xml
<CustomField>
    <fullName>Upsides__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Approved Upsides for this Customer and Month</description>
    <label>Upsides</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestRiskUpsideApproval.cls
/* -----------------------------------------------------------------------------------------------------------------------
   Name:        TestRiskUpsideApproval.cls
   Description: Test transfer of approved Risk/Upside record values to Month Revised Forecasts
                    
   Date         Version Author              Summary of Changes 
   -----------  ------- ------------------  ------------------------------------------------------------------------------
   Dec 2017     1.0     M.Witchalls(Ciber)  Initial Release 
------------------------------------------------------------------------------------------------------------------------ */        
@isTest
private class TestRiskUpsideApproval {
    private static String rowCause = 'Apex__c';
    private static String encircProfile = 'Encirc Standard User';
    private static List<User> encircUsers = [SELECT Id FROM User WHERE Profile.Name = :encircProfile AND IsActive = true LIMIT 2];
    private static String approvedRecordType = 'Approved_Rejected';
     
    @isTest static void testRiskUpside() {  
        // create one Account with 12 Month Forecasts
        List<Account> aList = TestDataFactory.createAccountsWithMonths(1, 10001); 
        List<Month__c> mList = aList[0].Months__r;
        
        String objectName = Schema.SObjectType.Forecast_Risk_Upside__c.Name;
        Schema.DescribeFieldResult fr = Schema.SObjectType.Forecast_Risk_Upside__c.fields.Approval_Status__c;
        String status = fr.getPickListValues()[0].getValue();
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = :objectName AND DeveloperName = :approvedRecordType];
        
        // create some Risk/Upside records
        List<Forecast_Risk_Upside__c> fruList = new List<Forecast_Risk_Upside__c>();
        for (Month__c m: mList) {
            Forecast_Risk_Upside__c fru = new Forecast_Risk_Upside__c(
                Approval_Status__c = status,
                Month__c = m.Id,
                Risks__c = 300,
                Upsides__c = 500
            );
            fruList.add(fru);
        }
        insert fruList;
        
        // Approve them
        for (Forecast_Risk_Upside__c fru: fruList) {
            fru.RecordTypeId = rt.Id;
            fru.Approval_Status__c = 'Approved';
        }
        update fruList;
        
        Month__c m = [SELECT Id, Revised_Forecast__c FROM Month__c WHERE Id = :mList[0].Id];
        
        //system.assertEquals(200, m.Revised_Forecast__c);              
    }   
    
}